source/cli.coffee
https://github.com/DanielXMoore/Civet/commit/1eabc4908e07124938d86bf6a395c355c7a436c2 fixed interactive input handling, and works perfectly on Linux.  Sadly, on Windows, there's apparently no automatic detection of EOF (via ^D or ^Z); this needs to be handled by the application.  The general recommendation seems to be to use Node's builtin `readline` interface, which seems to work well for file inputs as well as interactive inputs. This PR does that.
=> Rewrite cli to use readline interface

TODO.md
Just making sure we don't forget this.
=> CoffeeScript export to-do

README.md
~~In particular add official Discord invitation link.~~
Oops, I see there's already an official link. That was fast. 🙂
But still some fancy badges if you want them.
=> Add Discord link and NPM badges

lsp/source/server.mts
Currently civet lsp client does not update diagnostics for other files when a file is updated. This often results in inconsistent diagnostics when for example file foo.civet imports a non-existent function from bar.civet. Later if I update bar.civet adding this function, foo.civet continues to show an error until I edit foo.civet itself which is not ideal. 
This PR makes the assumption that a user will usually not have hundreds of files open and just updates diaganostics for all open files rather than hooking into dependency analysis. Other extensions like volar also make similar assumption.
=> LSP: Update other documents asynchronously when content gets updated

source/parser.hera, test/autolet.civet
All effects are shown in the test.
NOTES: 
+ Assignment children process missed. I can’t construct a legal case.
+ How to handle type?
=> Add autolet

source/parser.hera, test/types/satisfies.civet
=> support typescript `satisfies`

README.md, source/parser.hera, test/jsx/attr.civet
As suggested by Oren on Discord
=> JSX `...foo` shorthand for `{...foo}`

source/parser.hera
I'm planning some future changes that make even more global refs. This is a refactor to make this very easy.
=> Refactor ref making

source/parser.hera, test/jsx/test.civet
https://twitter.com/srsholmes/status/1593891832307634182
=> Support type parameters in JSX tag names

README.md
This question was asked in the Solid Discord; current wording is ambiguous.
I tried to come up with a good example; feel free to improve.
=> Clarify that comma operator works in `for`

source/parser.hera, test/autolet.civet
Attention: This PR changed contents of `gatherRecursive`.
=> Fix autoLet will redeclare the variable explicit declared

lsp/source/server.mts
This improves lsp support for monorepos and other projects where there may not be a single tsconfig at the root. 
Instead of spawning a single tsserver at the time of workspace initialization, this updates the impl to instead locate the tsconfig on a per file basis and spawns a tsserver per located tsconfig.
=> Better support for multi-tsconfig projects

README.md, civet.dev/getting-started.md
Mainly revising the Getting Started docs here.
In particular this is the first mention of the REPL in docs.
=> Improve CLI documentation

README.md, civet.dev/cheatsheet.md
* Arrays
* Triple-quoted strings
* More functions
* `autoVar` and `autoLet`
* CoffeeScript compatibility
=> Several more examples for docs

source/parser.hera, test/types/import.civet, test/types/js.civet
=> Support `import`/`export` `type`/`{type}`

.github/workflows/static.yml, package.json
As suggested by @Argeento 
Also remove a deleted file from `package.json`
=> `yarn build` before building docs locally

source/main.coffee, source/parser.hera, test/array.civet
Fixes #147 by adding a no-cache rule.
I'm not totally sure why this works (or rather why it wasn't working) but it does. 😅
=> Fix array parsing bug

source/parser.hera, test/if.civet
=> Fix inline ifs

source/parser.hera, test/try.civet
Fixes #128
E.g.
```civet
foo := try potentiallyErroringThing() catch(e) {...} finally {...}
```
=> Try expression

civet.dev/cheatsheet.md
=> Synonyous -> synonymous

civet.dev/.vitepress/components/Playground.vue, civet.dev/.vitepress/utils/compileCivetToHtml.ts
=> Docs: Fix mobile playground

civet.dev/.vitepress/components/Playground.vue, civet.dev/public/playground.worker.js
=> Docs: Enhance playground error handling

source/parser.hera, test/compat/coffee-prototype.civet
=> Moved :: behind coffeePrototype config flag

Civet-from-CoffeeScript.md, README.md, notes/Comparison-to-CoffeeScript.md
Modified the README and extracted out the CoffeeScript focused parts to appeal to a broader audience.
=> Moved CoffeeScript focus into separate document

civet.dev/.vitepress/components/Playground.vue, civet.dev/.vitepress/components/PlaygroundFull.vue
- Fix textarea positioning
- Fix console output format
=> Docs: Fix playground

source/parser.hera, test/types/interface.civet
Fixes #157
I need this for an app I'm working on so accelerated this particular feature. 🙂
=> Support TypeScript `interface extends`

source/cli.coffee
Fixes #217. Tested on MacOS.
* Was previously overwriting `filename` and then trying to read it
* Use `readline` exactly in TTY mode
* Outside TTY mode, new "chunk" reader to read directly from `process.stdin`
* Re-enable `-` command-line option for reading stdin (was previously disabled by helpful error message)
=> Fix CLI behavior especially on Unix

CONTRIBUTING.md
Based on Daniel's recent message in Discord
=> Contributing document for getting started with Civet

source/parser.hera, test/binary-op.civet
* `operator a, b, c` to bless already existing functions into infix operators
* `import {operator x} from ...` to import and bless an imported function
* `operator op(a, b) ...` to define and bless a new function
* `operator {min, max} := Math` or any lexical declaration to simultaneously bless
* `op(a, b)` is always a function call
I haven't added to cheatsheet yet, but can do so later.
=> Identifier operators

README.md
I thought it might be useful, I wouldn't have known about the sponsorship possibility if not for _macaroni_'s post on Discord.
Feel free to reject the PR if for some reason you don't want it featured.
=> Added a sponsorship segment to the readme

source/parser.hera, test/strings.civet, test/template-literal.civet
As in CoffeeScript. Fixes #311
=> Tagged string literals become tagged template literals

civet.dev/cheatsheet.md, source/parser.hera, test/binary-op.civet
=> typeof shorthand

source/parser.hera, test/assignment.civet, test/binary-op.civet, test/compat/coffee-for-loops.civet, test/compat/coffee-not.civet, test/compat/coffee-of.civet, test/compat/examples.civet
=> Switch prelude declarations from const to var

source/parser.hera, test/pipe.civet
But allow nested pipelines in nested arguments
Part of #346
=> Pipelines lower precedence than implicit arguments

source/parser.hera, test/switch.civet
Still need to work on duplicate array element bindings.
=> duplicate bindings after rest work

civet.dev/.vitepress/config.js, civet.dev/comparison.md, civet.dev/config.md, notes/Comparison-to-CoffeeScript.md
I'm tempted to move the comparison to CoffeeScript in here too... What do you think?
=> Docs: Comparison to JavaScript/TypeScript

civet.dev/cheatsheet.md, civet.dev/comparison.md, civet.dev/index.md
This is kind of important so thought I'd put it to review instead of my usual direct docs updates/improvements. 😸 
I think it'd also be nice to move/copy the philosophy to the website, maybe as a page only linked from here and not in the topnav.  Thoughts?
(Also clean up some language about "Civet on the left")
=> Write an intro to Civet for the front page

source/parser.hera, test/pipe.civet
Fix comment from https://github.com/DanielXMoore/Civet/commit/a22e06c808fb8c6f1ff77f4813fecd86f1c5dcf5
=> Fix automatic async vs. pipe invocations

source/parser.hera, test/pipe.civet
This could probably use some more test cases but seems to work pretty well so far.
Fixes #423
=> Ampersand pipes

source/parser.hera, test/types/js.civet
=> @ type parameter with other parameters

source/lib.js, source/parser.hera, test/compat/coffee-for-loops.civet, test/for.civet, test/if.civet, test/while.civet
=> Declarations inside conditionals

source/lib.js, source/parser.hera, test/await.civet
https://github.com/tc39/proposal-await.ops
=> Fixes #293. Await ops

package.json, yarn.lock
=> source-map-support dependency

source/parser.hera, test/assignment.civet, test/class.civet, test/function.civet, test/if.civet, test/switch.civet
=> Call splice method directly

source/parser.hera, test/function.civet
=> Fix implicit async/* in functions with arguments

civet.dev/cheatsheet.md, source/lib.js, source/parser.hera, test/jsx/attr.civet
Part 2 of #238
In particular achieves https://github.com/DanielXMoore/Civet/pull/507#pullrequestreview-1386608989
=> JSX braceless call/member/glob expressions

source/parser.hera, test/types/type-declaration.civet
=> Support splats in type tuples

source/parser.hera, test/types/interface.civet, test/types/type-declaration.civet
Fixes #541
Also replaced some `__` with `NotDedented`
=> Fix readonly support in interfaces 

source/parser.hera, test/types/function.civet, test/types/interface.civet
=> Support new arrow function types

source/lib.js, test/switch.civet
=> Fix binary ops RHS in pattern matching switch

source/parser.hera, test/binary-op.civet
=> Support indented RHS after binary op

civet.dev/cheatsheet.md, source/lib.js, source/parser.hera, test/function.civet
=> No implicit return from async function: Promise<void>

source/parser.hera, test/types/type-declaration.civet
=> TypeScript named tuples

source/parser.hera, test/types/type-declaration.civet
=> Allow ?: with named elements in tuple types

source/main.coffee, test/array.civet, test/if.civet, test/object.civet
=> Cache fix for function calls within inline objects

civet.dev/cheatsheet.md, source/lib.js, source/parser.hera, test/for.civet
This is part 1 of "easier array iteration".  It lets you do
```js
for item, index of array
↓↓↓
let i = 0;for (const item of array) {
const index = i++;
```
Part 2 will be more efficient array-specific loops, as in CoffeeScript's `for..in`.
=> for item, index of list

source/lib.js, source/parser.hera, test/class.civet
=> Constructor prefix goes after super call

civet.dev/integrations.md
see more <https://www.npmjs.com/package/vite-plugin-civetman>
=> Docs add vite-plugin-civetman to Integration

source/lib.civet
=> Added void to improve types and opt out of implicit returns

source/parser.hera, test/array.civet, test/function-application.civet
Ended up not being to bad, thanks @edemaine for the previous starting point.
=> New try at indented application

source/lib.civet, source/parser.hera
This results in ~20% perf boost.
=> Underflowing arrays is a perf killer

README.md
- updates link to the bun plugin file
=> docs: Fix bun plugin link

source/cli.civet, source/main.civet
Convert to a more civet style.
Added propagation of `--inspect` to child process.
=> Cli update

source/parser.hera, test/function.civet
Partial fix to #760 (not sure whether to close it, or leave it open to remember to add indentation later)
=> Allow newline before ...rest parameter

source/parser.hera
Before:
```
Total: 3149657
_: 117054
NonNewlineWhitespace: 79545
InlineComment: 70712
EOS: 66676
Comment: 59745
__: 55837
CoffeeOfEnabled: 45099
Dot: 43692
QuestionMark: 43579
NonNullAssertion: 41793
JSMultiLineComment: 36664
MultiLineComment: 36662
JSSingleLineComment: 36639
...
daniel:~/apps/civet$ time ./node_modules/.bin/civet < source/lib.civet > /dev/null 
real    0m4.384s
user    0m6.496s
sys     0m0.970s
```
After:
```
Total: 2783505
_: 117054
EOS: 66676
__: 55837
InlineComment: 50009
CoffeeOfEnabled: 45099
Comment: 44351
Dot: 43692
QuestionMark: 43579
NonNewlineWhitespace: 43448
NonNullAssertion: 41793
Whitespace: 34265
OpenBracket: 31830
Identifier: 25265
...
daniel:~/apps/civet$ time ./dist/civet < source/lib.civet > /dev/null 
real    0m3.962s
user    0m5.945s
sys     0m0.731s …
```
=> ~10% perf boost by adding some short circuit assertions

package.json, source/parser.hera, yarn.lock
The `NonNullAssertion` moved into a choice of `OptionalShorthand` since they were always used together.
=> refactor property access patterns; 0.7% perf improvement

source/parser.hera, test/comment.civet
Preserve comments near Civet directives
xref [Discord discussion](https://discord.com/channels/933472021310996512/933472021310996515/1165013088697860146)
=> Allow comments near Civet directives

source/parser.hera, test/types/template-literal.civet
=> Type arguments in template literals

integration/unplugin/examples/esbuild/esbuild.js, integration/unplugin/src/index.ts
=> Fix sourcemap issue in unplugin (#846)

source/parser.hera, test/function.civet
=> Fix implicit generators in assigned -> functions

source/lib.civet, source/parser.hera, test/function.civet
=> Handle labeled loops

civet.dev/.vitepress/components/Playground.vue, civet.dev/.vitepress/components/Sponsors.vue, civet.dev/.vitepress/theme/custom.css
- Removed border radius
- Added shadows
- Fixed light mode code legibility
=> Update docs style

source/lib.civet, test/while.civet
=> Fix while(cond) without space

package.json, source/lib.civet, yarn.lock
=> Use .-1 notation in Civet source

civet.dev/.vitepress/components/Hero.vue, civet.dev/.vitepress/theme/custom.css, civet.dev/index.md
=> docs: Revise tagline, opening paragraph, and purple

source/parser.hera, test/for.civet, test/range.civet
=> `[a ... b]` is a range, `[a ...b]` is implicit call

civet.dev/reference.md, source/lib.civet, source/parser.hera, test/assignment.civet, test/binary-op.civet
As discussed in Discord. `++` is concat in Haskell and Elixir.
Also Unicode version ⧺
=> ++ concat operator

civet.dev/reference.md, source/lib.civet, source/parser.hera, test/types/function.civet, test/types/let-declaration.civet
Follow-up to #902 for function return values, plus some refactoring
=> Optional function return types

source/lib.civet, test/pipe.civet
=> Wrap thick pipes in parens

lsp/source/lib/typescript-service.mts
Fixes #920, at least in my simple testing.
There's still work to do in the resolution code, e.g. support for `rootDirs`. I've left TODOs accordingly.
Mixty also reports testing this and that it works.
=> Support TypeScript `paths` alias

lsp/source/lib/typescript-service.mts
More work on the LSP TypeScript resolver: now looks for `index.civet`/`index.hera`/etc. when the user attempts to import a directory. Technically, this should only happen when the TS `resolutionMode` has certain values. But if the user is importing a directory, this is likely what they mean.
This is still only a partial implementation of TS's resolver, but it's a feature requested on Discord.
I've tested this myself with `foo from ./` when there's an `index.civet` file, and it gets the right types.
This could also be an opportunity to test [my deployment of LSP](https://github.com/DanielXMoore/Civet/pull/921#issuecomment-1895794101) (but I'm also fine with you publishing 😸 )
=> LSP support importing directories with index.civet

integration/unplugin/src/index.ts
* Allow `undefined` sourcemap to be returned (previously we converted to empty string, and then tried to `JSON.parse` that string, which crashed)
* Force request of actual sourcemap from TypeScript when transpiling (only), which causes sourcemap to be returned without emitting a file.
=> Fix ts: 'tsc' behavior around sourcemaps

source/parser.hera, test/property-access.civet
=> Fix optional property access shorthand

source/lib.civet, test/pipe.civet
=> Fix ASI with pipes

source/parser.hera, test/types/let-declaration.civet, test/types/type-declaration.civet
=> Fix array of objects type

source/parser.hera, test/object.civet
Reported by @bbrk24 on Discord
=> Fix object getters with globs

source/parser.hera, test/class.civet
=> Fix private field glob getters

source/parser.hera, test/types/type-declaration.civet
=> Fix TS infer, extends, typeof

civet.dev/reference.md, source/parser.hera, test/switch.civet
=> Fix triple slash in pattern matching switch

source/parser.hera, test/object.civet
Fixes #995. Probably introduced during #976 — oops!
=> Allow multiple props per line in implicit object literals

source/lib.civet, test/compat/auto-var.civet
=> Don't create empty var decs with auto-var

lsp/source/lib/typescript-service.mts
I thought this might help with https://github.com/DanielXMoore/Civet/issues/925 and it might help a little but doesn't seem to be a big improvement.
If we do want better incremental parsing support in the future then we can build off of this.
=> Snapshots similar to how Vue language tools does

integration/unplugin/src/index.ts
I ran into the following unplugin bug when trying to put vitest tests into a `test` subdirectory in [this repo](https://github.com/edemaine/sliding-squares-puzzle):
* Recall `resolveId(id, importer)` is supposed to resolve a given `id` (path) relative to a given `importer` (source).
* `resolveId("C:/Users/edemaine/Projects/sliding-squares-puzzle/test/permutation.test.civet", "C:\Users\edemaine\Projects\sliding-squares-puzzle\index.html")` resolves to `"test\permutation.test.civet.tsx"`
* As designed, the unplugin is returning a path relative to the current working directory. This is a correct path.
* `resolveId("../src/permutation.civet", "test/permutation.test.civet.tsx")` resolves to `"src\permutation.civet.tsx"`
* As designed, the unplugin is returning a path relative to the current …
=> Don't relativize paths in unplugin

integration/unplugin/src/index.ts
I modified the Unplugin typechecking system to also transpile any dependencies that TypeScript explores when typechecking. This is necessary when a `.civet` file just contains types, and e.g. it's imported via `import type` so it never actually gets explored by the build system when generating JS. (esbuild does this in even more settings: if we never use an `import` except within types, then esbuild never even visits the imported file.)
This also required setting [composite: false](https://www.typescriptlang.org/tsconfig#composite), or else TypeScript complains about the growing list of files.
This should fix https://stackblitz.com/edit/vitejs-vite-gpjtap?file=package.json
As an added bonus, if you now `civet --typecheck filename.civet` and `filename.civet` depends on other Civet files, …
=> Typechecking allows for extra dependencies beyond build

integration/unplugin/src/index.ts
#1054 seems to be the wrong fix, because the esbuild dep scanning phase doesn't seem to understand [aliases](https://vitejs.dev/config/shared-options#resolve-alias).
This simpler fix seems to work. Specifically, we're triggering [this rule](https://github.com/vitejs/vite/blob/37af8a7be417f1fb2cf9a0d5e9ad90b76ff211b4/packages/vite/src/node/optimizer/scan.ts#L703). It would seem to make the `.civet` file act like `.ts` file, which would have `resolvedId === rawId`.
I still have limited understanding here. In particular, I can't tell whether I'm preventing Vite from doing its dependency scan on Civet files, which can cause some inefficiency. But at least it works, now also with aliases.
=> Tell Vite virtual module during dependency scanning

source/parser.hera, test/prologues.civet
=> Strings at start of file followed by pipe or access are not prologues

lsp/integration/project-test/a.civet, lsp/package.json, lsp/source/lib/util.mts, lsp/test/util.civet
Improved forward sourcemapping by resetting the best column when advancing the best line.
Also fixed lsp tests by removing reference to .coffee file in integration test.
Fixes #1053
=> Sourcemap improvement

source/parser.hera, source/parser/lib.civet, test/assignment.civet, test/try.civet
- Support for nested statement expressions.
- Consolidated StatementExpressions in grammar
- Fixed a test that wasn't wrapped in a test method
#202
=> Added support for nested statement expressions

civet.dev/reference.md, source/parser.hera, test/types/type-declaration.civet
=> Signed number literal types, including dropping +

source/parser.hera, test/types/class.civet
=> TS override support

source/parser.hera, test/compat/coffee-prototype.civet
=> Don't treat double colon as colon

civet.dev/reference.md, source/parser/op.civet, source/parser/types.civet, source/parser/unary.civet, test/binary-op.civet
Fixes #1114
* Fix `first` setting so that beginning of a second chain gets existence pulled out
* Process chains of length 1 for the same reason
* Cleanup and Civetify some code, add some typing
=> Fix relational chains

source/generate.civet, source/parser.hera, source/parser/for.civet, test/for.civet
Fixes #1126
Also fixed some debugging code that let me figure out what was going on in #1147
=> Infinite range [x..]

source/parser.hera, test/types/type-declaration.civet
=> `::#` type with `coffeePrototype`

.github/workflows/build.yml, .github/workflows/static.yml
=> Upgrade CI to Node.js 20

source/parser/comptime.civet, test/comptime.civet
Will almost certainly have a merge conflict once #1188 is merged
=> comptime `Object.create null`

source/parser/comptime.civet, source/parser/helper.civet, source/parser/op.civet, test/comptime.civet
=> Duplicate helpers in comptime blocks

source/parser/block.civet, source/parser/for.civet, test/compat/coffee-for-loops.civet, test/compat/examples.civet, test/for.civet, test/function.civet, test/if.civet, test/jsx/test.civet, test/switch.civet, test/while.civet
Fixes #1113 
90% of the effort here was fixing all the tests.
=> Don't emit newlines before block prefixes

civet.dev/reference.md, source/parser.hera, source/parser/lib.civet, source/parser/types.civet, test/try.civet
=> try else blocks

civet.dev/reference.md, source/parser.hera, source/parser/function.civet, source/parser/lib.civet, source/parser/types.civet, source/parser/util.civet, test/compat/coffee-do.civet
=> Argument magic with `coffeeDo`

source/parser/declaration.civet, source/parser/lib.civet, source/parser/types.civet, test/for.civet
=> Fix iteration expression unwrapping in splice assignment

package.json, source/cli.civet, yarn.lock
This should also fix CLI handling of `-co`, via #1261
=> Update Civet and use try..else feature

source/parser/function.civet, source/parser/pattern-matching.civet, test/function.civet, test/switch.civet
Fixes #1264
Also fix function declaration at end of loop
=> Fix empty block in pattern matching with implicit return

source/parser/function.civet, source/parser/lib.civet, test/function.civet, test/if.civet, test/property-access.civet, test/switch.civet
=> Fix hoistDec within if expression

civet.dev/getting-started.md, integration/unplugin/README.md, integration/unplugin/src/index.ts
This speeds up esbuild serve quite a bit on larger projects.
=> Added a cache based on mtime for watch/serve mode in esbuild

source/parser.hera, source/parser/function.civet, test/function.civet
Fixes #1277 (some missing cases from the rewrite in #1271)
=> Fix async detection in a few cases

source/parser/helper.civet, source/parser/string.civet, source/parser/traversal.civet, source/parser/util.civet, test/template-literal.civet
I think we can hit 100% coverage and remove all the type errors if we slowly chip away at it.
=> Fix some TS errors and increase code coverage

source/parser.hera, test/binary-op.civet, test/import.civet
=> Fix import looking like multiplication

source/parser.hera, test/conditional.civet
=> Fix indented chained ternaries

source/parser.hera, test/slice.civet
=> Fix .. slice operator precedence

source/parser.hera, test/assignment.civet, test/compat/coffee-div.civet
=> Assignment operators for div and mod

source/parser.hera, test/types/function.civet
Fixes #1322
This turned out to be really easy; `MaybeNestedType` just works.
=> Nested return type annotation

source/cli.civet
=> Fix CLI for globally installed Civet

source/parser.hera, test/types/interface.civet, test/types/namespace.civet
As reported by @bbrk24 on Discord
=> Allow empty `interface` and `namespace` blocks

source/parser.hera, test/function.civet
=> Fix arrow being treated as assignment in tight arrow functions

source/parser/lib.civet, test/partial-placeholder.civet
=> Fix placeholder expressions at head of pipeline

source/parser.hera, test/object.civet
As suggested by @bbrk24 on Discord
=> Support length shorthand `#` when defining objects

package.json
Just noticed [this was missing](https://www.npmjs.com/package/@danielx/civet?activeTab=code).
=> Include changelog in NPM release

source/parser.hera, source/parser/lib.civet, test/types/type-declaration.civet
=> Postfix `if`/`unless` in type declaration

source/parser.hera, source/parser/declaration.civet, source/parser/function.civet, source/parser/lib.civet, source/parser/types.civet, source/parser/util.civet, test/do.civet, test/for.civet, test/loop.civet, test/while.civet
Fixes #505
I couldn't push to @vendethiel's branch, so created this instead. Hopefully this is now ready to go.
TODO: Docs
=> `for*`, `loop*`, `while*` generator expressions

source/parser.hera, source/parser/auto-dec.civet, test/compat/auto-var.civet
=> Make `autoVar` skip `declare`d variables

source/parser/declaration.civet, test/if.civet
=> Add missing parens in `unless` declaration condition

source/parser.hera, source/parser/for.civet, test/for.civet, test/types/for.civet
=> Type specification in `for..of/in` loops

civet.dev/config.md, civet.dev/reference.md, source/parser.hera, source/parser/auto-dec.civet, test/compat/auto-var.civet, types/types.d.ts
=> `"civet globals"` directive to prevent some auto declarations

source/parser.hera, test/types/declare.civet
=> Support `export default` in `declare` blocks

source/parser.hera, test/pipe.civet
=> Allow pipes etc. in explicit function arguments

source/parser.hera, test/await.civet
=> Fix await with array member expression

civet.dev/reference.md, source/parser.hera, test/compat/examples.civet, test/for.civet
=> `for` loops can filter via `when` conditions (not just in CoffeeScript mode)

lsp/source/lib/util.mts, lsp/source/server.mts
Enhance document handling in LSP server by ensuring service availability and updating documents
=> LSP completions and hover info up-to-date instead of lagging

lsp/source/server.mts
=> `resolve` of `WithResolver` is not return A `Promise`

source/parser.hera, source/parser/lib.civet, source/parser/types.civet, source/parser/util.civet, test/types/type-declaration.civet
Fixes #1504
Also some more type AST nodes to enable detection of named tuple elements
=> `T?` type shorthand in named tuple elements

source/parser.hera, test/for.civet
=> Fix parenthesized `for` expression without body

source/parser/function.civet, test/function-block-shorthand.civet
=> Fix `for` loops over `&` placeholder

source/parser/lib.civet, source/parser/types.civet, test/function-block-shorthand.civet
=> Placeholders lift through reverse slice operators

source/parser/helper.civet, source/parser/lib.civet, test/function-block-shorthand.civet, test/slice.civet
=> Fix reverse slices handling of extreme indices, trailing member access

civet.dev/.vitepress/components/Playground.vue, civet.dev/.vitepress/components/PlaygroundFull.vue, civet.dev/.vitepress/utils/compileCivetToHtml.ts, civet.dev/public/playground.worker.js
=> Playground TypeScript toggle

source/parser/for.civet, test/for.civet
=> Fix range `for` loop with complex left-hand side

source/parser.hera, test/if.civet
=> Fix missing parentheses in one-line `if` condition

source/parser/pattern-matching.civet, test/switch.civet
=> Fix #1606 handle numeric object keys in pattern matching

civet.dev/public/playground.worker.js
=> Playground shows IIFE failures only when clicking Run

civet.dev/reference.md, source/parser.hera, test/pipe.civet
=> `yield*` in pipeline

source/parser.hera, test/jsx/attr.civet
=> Fix bind property shorthand in JSX

lsp/source/extension.civet, lsp/source/server.mts
Fixes #1700
Also remove `.clientrc` watching, which was just an example from https://code.visualstudio.com/api/language-extensions/language-server-extension-guide
=> Fix LSP when opening files without workspace

civet.dev/getting-started.md, lsp/README.md
Fixes #1699 I think.
I think we want a VSCode plugin option to disable type checking altogether, but I don't actually know how to disable type checking... 😅
=> Document how to use VSCode plugin

source/parser.hera, test/array.civet
=> Allow comment before bulleted array

source/parser.hera, test/types/type-declaration.civet
=> Support nested types in parentheses

source/parser/function.civet, source/parser/types.civet, source/parser/util.civet, test/function.civet, test/if.civet
=> Fix implicit returns in IIFEs with "civet -implicitReturns"

source/parser.hera, test/types/class.civet
=> Type-only class field declarations `declare field: T`

source/parser.hera, test/comment.civet
=> Fix CoffeeScript comments getting treated as `length` shorthand

source/parser/lib.civet, source/parser/types.civet, test/jsx/test.civet
=> Fix access detection in braced expressions
