DanielXMoore/Civet

build/test-compat.coffee

Current results on CoffeeScript source:
```
* browser.coffee
Unrecognized error message "Unknown node"
97.2% success (removed 3 out of 108 lines)
* cake.coffee
98.9% success (removed 1 out of 89 lines)
* grammar.coffee
98.6% success (removed 14 out of 1004 lines)
* optparse.coffee
81.3% success (removed 31 out of 166 lines)
* register.coffee
100.0% success (removed 0 out of 56 lines)
* repl.coffee
99.5% success (removed 1 out of 221 lines)
```
The other files not listed above crash with errors that don't contain line numbers. In some cases the error just needs to be replaced (e.g. `by clause not yet implement in non-range for in loops`) and in other cases they're probably bugs (`Cannot read properties of undefined`).

Add script for testing compatibility with CoffeeScript

---

README.md
source/parser.hera
test/compat/coffee-word-assignment.civet

* Remove "civet coffeeWordAssignment" configuration option
* Enable `and=` / `or=` always, by symmetry with `and` and `or`
* Small typo fix in README

Allow and= / or= by default (not just coffeeCompat)

---

lsp/source/lib/typescript-service.mts
lsp/source/server.mts

This fixes some lsp bugs on Windows, but sadly not all of them.
(It's still the case that updates to files don't trigger updates to the view. `getScriptSnapshot` seems to be returning the correct data (updated transpiled file), but as far as I can tell it's getting called *after* the TypeScript service returns results, which seems... wrong?)
Before merging, please test on other operating systems that this doesn't break anything.

More consistent use of paths vs. file URIs

---

README.md
source/parser.hera
test/export.civet

This PR adds support for `export x, y` shorthand for `export {x, y}`.  Also supports `export x as foo, y as bar`.
It's meant as a step toward `export x = 5` from CoffeeScript, but I haven't gotten there yet.  It seems useful by itself.  It feels like a natural extension to CoffeeScript's implicit object literals.
Also not yet supported:
* `export x, y from 'foo'`.  This seems like it should be supported by the grammar as I wrote it, but it won't parse. Any ideas?
* Multi-line implicit objects: (I couldn't quite figure out how this works with `ImplicitObjectLiteral`)
```
export x,
y
z
```
I'm also a little uncomfortable with why I needed to re-order `Declaration` and `NamedExports`. I thought both branches would try to parse...?

Support for unbraced `export x, y`

---

README.md
source/parser.hera
test/indent.civet

1. [Allow arbitrary spaces in indentation](https://github.com/DanielXMoore/Civet/commit/c6633644dc50c3bf5e2f3f5cac392c775bcdb086), instead of an even number of spaces. In particular allows for 3-space indent, or mixtures.
2. [Custom unification of tabs and spaces](https://github.com/DanielXMoore/Civet/commit/7e0619b10a18ed09add88a5d42489fc049c74973) via `"civet tab=NNN"` option.

Indentation flexibility

---

README.md
source/main.coffee
source/parser.hera
test/jsx/indent.civet

This is an attempt at implementing basic auto-closing JSX tags via indentation, while co-existing with explicitly closed tags, as discussed in #20.
Here's an example:
```coffee
return
<div>
<b>
Bold
<i>
Italic
console.log 'hi'
```
But it currently compiles to:
```js
return
<div>
<b>
Bold
</b>
<i>
Italic
</i>
</div>
console.log('hi')
```
The issue is that the added closing tags aren't indented properly. @STRd6 Could you explain how I'm using `IndentIndent` incorrectly? I haven't been able to figure it out, despite matching the `Nested` (as far as I can tell). Is the function associated with the `JSXElement` rule just called too late, and I need to add an `InsertClosingTag` rule? If so, how would I give it the opening tag?

Indentation-based JSX

---

source/parser.hera
test/jsx/objects.civet

Support any object literal as a JSX attribute:
* `{foo}` as shorthand for `foo={foo}`
* `{foo, bar}` is shorthand for `foo={foo} bar={bar}`
* `{foo: bar}` is shorthand for `foo={bar}`
* Multiple `...rest` supported
* Methods get converted into functions
* Computed property names and `get`/`set` methods supported via `{...rest}` JSX notation
~~Oops, `[foo]: bar` isn't supported yet.~~

JSX object shorthand

---

source/parser.hera
test/array.civet

Support for indentation after the first line of items in an array, e.g.:
```coffee
[1, 2, 3
4, 5, 6
7, 8, 9]
```
Fixes #27 (at least for arrays — maybe there are other cases of indentation-in-the-middle that we need to find).
This is still a lot more strict than CoffeeScript, which allows some weird things:
```coffee
[x
y
z
] → [x, y, z]
[x
y
z
w
] → [x, y, z, w]
[x
y: z
] → [x, {y: z}] (!)
[x
y
z: w
] → [x, y({z: w})]
```

Indentation in middle of arrays

---

source/main.coffee
source/parser.hera
test/jsx/indent.civet
test/jsx/test.civet

Mirroring similar support for opening tags like `<foo>`. Also more tests.
(Noticed this bug when testing support for elements/fragments as attributes, which I didn't realize was even a thing in JSX, but it's there in the standard.)

Support content on same line as <>

---

README.md
source/parser.hera

`[name]=value` translates into `{...{[name]: value}}`
This PR is relative to #38, because it also touches the file `test/jsx/attr.civet`; I can rebase once #38 is merged.

Support computed JSX attribute names

---

README.md
source/parser.hera
test/block-strings.civet
test/jsx/attr.civet
test/strings.civet

* Fix output of `""` in `coffeeCompat` mode (previously was ``` `` ```)
* Oops, I never added `test/jsx/attr.civet` which had been testing past features
* Add support for whitespace-free JSX attributes, including unary, binary, call, attribute expressions. This involved refactoring unary processing to avoid duplicating that code.
* Fix support for strings in JSX attributes (previously, `coffeeInterpolation` would have broken things)

Support whitespace-free JSX attributes

---

source/parser.hera
test/types/function.civet

As discussed in discord, `<T>(x) => x` is not valid TSX (but is valid TS).  Convert to `<T,>(x) => x` for safety.

Fix singleton TypeParameters compatibility with TSX

---

source/parser.hera
test/jsx/test.civet

Whitespace before `</>` accidentally wasn't allowed.

Fix multi-line JSX fragments

---

README.md

`source/esbuild-plugin.civet` could use some comments (like `source/esm.civet` does) about how to use the plugin, in particular from an NPM install (`@danielx/civet/...`). I don't know how to use it, though, so haven't attempted that here.

Link to Vite, esbuild, ESM plugins

---

source/parser.hera
test/property-access.civet

`super.foo` wasn't working (found while working on dynamic `import` without parens)

Super property access

---

source/parser.hera
test/binary-op.civet

This PR conservatively implements the Pipe operator as described in https://github.com/tc39/proposal-pipeline-operator. 
Advanced features like placeholders or other features from hack are still in flux and likely to cause compatibility problems in future.

Add support for |> pipelines

---

source/parser.hera
test/function-application.civet

Passing implicit (not brace delimited) object to a function as first parameter has some oddities currently. 
Something like this appears to work in basic example: 
```
foo
a: 10
```
```js
foo(
{a: 10},)
```
But if one more property is added things get weird: 
```
foo
a: 10
b: 20
```
```js
foo(
{a: 10(
{b: 20},)},)
```
Making the function invocation explicit through parens doesn't help: 
```
foo(
a: 10
b: 20
)
```
```js
foo(
{a: 10(
{b: 20})}
)
```
But interestingly if I add a space, then it is parsed as an implicit function application whose argument is a parenthesized implicit object expression, which works: 
```
foo (
a: 10
b: 20
) 
```
```js
foo(( {
a: 10,
b: 20,
}
))
```
This PR adds an additional rule so the first two scenarios also behave as expected.

Fix function application with implicit object

---

README.md
source/main.coffee
source/parser.hera
test/class.civet
test/import.civet

With this PR, I believe `import foo` works as well as `import(foo)` currently does.
However, `import(foo).then(...)` doesn't currently work, and still doesn't work with this PR. Any ideas on how to fix? It doesn't seem to be a caching issue...

Implicit dynamic import()

---

.github/workflows/static.yml

I can disable the action on my fork, but it seems more polite to new contributors to not have this action run whenever they sync their repo with upstream.
I haven't tested this, but it seems correct from https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

Don't deploy civet.dev website from forks

---

README.md
source/parser.hera
test/jsx/attr.civet
test/jsx/indent.civet

Given that `<For each=items()>(item) => ...` isn't valid JSX because `>` isn't valid JSX text, I added support for automatically wrapping arrow functions like this in braces. This is convenient for SolidJS in particular which often uses function children.

JSX arrow functions don't need braces

---

source/main.coffee

Surprisingly, this is just 2x faster, but it's also easier to maintain (no more `\`s).
https://jsbench.me/y7lc9hbwze/1

Use Set to represent uncacheable rules

---

README.md
source/parser.hera
test/jsx/attr.civet
test/jsx/objects.civet
test/jsx/test.civet

* JSX `.class` shorthand, which stack together and with `class`/`className`
* JSX `#id` shorthand
* Improve JSX attribute space generation (fewer double spaces)
* Forbid JS comments in JSX (outside braces) — this never should have been allowed

JSX #id and .class shorthands

---

source/cli.coffee

* `process.stdout` needs to be given to `readline` for proper ^D/^C handling (at least on Windows)
* Avoid `undefined` from being output from ^C

Fix CLI behavior on Windows

---

source/parser.hera
test/jsx/attr.civet

Currently, JSX attributes `.class1 .class2 class={foo()}` compile to ``class={`class1 class2 ${foo()}`}``. This isn't what people expect when `foo()` returns `undefined` or `false`.
This PR instead compiles `.class1 .class2 class={foo()}` to `class={["class1 class2", foo()].filter(Boolean).join(" ")}`.

Filter combined JSX classes

---

build/build.sh
build/test-compat.coffee
source/cli.coffee
source/main.coffee
source/parser.hera
test/compat/examples.civet
test/examples.civet

* `-c`/`--compile` to compile specified `.civet` files to `.civet.tsx` or `.civet.jsx` files (according to `--js` flag)
* `-o`/`--output` lets you override the output directory/extension/filename
* Without `-c`, runs files directly (like `coffee`)
* `-` to run or compile stdin; `-o -` to output to stdout
* `civet <input >output` still works
* `civet` alone runs simple REPL with cute prompt: `🐱> `
I also made the main `compile` function turn on `coffeeCompat` by default (when no other `civet` directive) for filenames ending with `.coffee`. This currently messes up line numbers by 1 though... Ideally we'd have a way to send information to the parser, but I don't know how.
Builds on #96
TODO: `require` registration, so `require`s work (this is generally missing in Civet I think)
TODO: `civet …

New CLI including REPL

---

README.md
source/parser.hera
test/jsx/test.civet

Mentioned as idea 7 on https://github.com/lxsmnsyc/ideas/discussions/11
I've wanted this myself in the past, though partly because CoffeeScript's equivalent (`{### ... ###}`) is so verbose.
One use-case for `` comments is that they let you comment out a block of JSX that itself has `/*...*/` comments (similar to single vs. double quotes and their tripled forms).
(Of course this only works one level deep... you can't use `` to comment out a block that has other `` comments.)

XML comment support within JSX

---

source/parser.hera
test/jsx/attr.civet

* Single class doesn't get array/filter/join; instead use `|| ""`
* Single template literal class doesn't need `|| ""`

Class shorthand optimizations

---

README.md
source/parser.hera
test/function.civet

As suggested by @orenelbaum on Discord, this PR disables `implicitReturns` in functions that have a trailing semicolon.
I may not have dealt with all cases; I'm not sure what a trailing semicolon at the end of a `for` loop should mean, for example. But hopefully a useful enough start!

Avoid implicit return via trailing semicolon

---

README.md

* Semicolon implies no implicit return (difference from CoffeeScript)
* ECMAScript compatibility directive

Document implicit return features

---

source/parser.hera
test/autolet.civet

Fix missing let decs inner declaration.    
I'm not sure if it's needed to fix that breaking `return let` which won't happen on `auto Var` as autovar move all variables to top.

Auto let Fix

---

README.md
civet.dev/getting-started.md
source/cli.coffee

Previously, `civet foo bar` would try to run two scripts, `foo` and `bar`. This is not how `node` or `coffee` work.
With this PR, `civet foo bar` runs script `foo` with argument `bar` (via `process.argv`). This is exactly how `node` and `coffee` work.
Note that `civet foo.civet -c` will no longer compile `foo.civet` (it will run it with an argument of `-c`).  Now `-c` needs to come first, as in `civet -c foo.civet`.  I think this is a worthwhile tradeoff.

CLI support for running script with arguments

---

source/parser.hera

I searched for `[a-z]"(?!\s+NonIdContinue)(?![,:)\]])(?!$)` and found a bunch of missing `NonIdContinue`s.
I think the rest are OK, though there are some tricky ones like in `CallExpression` and `SuperProperty` where you need to think about it.

Add missing NonIdContinue after keywords

---

README.md
civet.dev/cheatsheet.md
source/parser.hera
test/binary-op.civet
test/compat/coffee-not.civet

* `is not` &rarr; `!==`
* `a not in b` &rarr; `!(a in b)` (like CoffeeScript, but with `in` instead of `of`; disabled when `coffeeOf` is on)
* `is in` and `is not in` are like CoffeeScript's `in` and `not in` but for general use
Open questions:
* Should we allow implicit arrays like `role is in 'admin', 'editor'` and `char is in 'a'..'f'`?
* Or float ranges like `0..1`?
* Should we use `includes` instead of `indexOf` with the new Civet `is [not] in` operators? (Daniel says CoffeeScript operators should probably stay as-is for compatibility. I'm not totally convinced...)

New operators: is not, is in, is not in, not in

---

README.md
civet.dev/cheatsheet.md
source/parser.hera
test/binary-op.civet

Fixes #127
Restructured `special` ops to use `call` instead of `ref`, so that it can work with or without `.call`, and to have `relational` flag as `%%` isn't relational.

Positive modulo operator %%

---

build/coffee-esm.mjs
build/esbuild.coffee
package.json
source/cli.coffee
source/generate.coffee
source/main.coffee
source/util.coffee
test/helper.civet
test/infra/esbuild.civet
test/integration.civet
test/sourcemap.civet
test/types/js.civet
test/util/locations.civet

* Add support for ESM `.coffee` files in `coffee-esm.mjs` (autodetection)
* Build new ESM version `dist/main.mjs`, which Vite seems to need in #125 (I've tested this in code I haven't yet pushed). (If I just told esbuild to convert the CJS code to ESM, you wouldn't be able to do `import {compile} from '@danielx/civet'`; only the default export gets preserved.)
* CoffeeScript code refactored to use ESM (but some things like Hera parser are still CJS)
* Note that default exports no longer have everything; need to `import *`

ESM build and refactoring

---

civet.dev/cheatsheet.md
source/parser.hera
test/jsx/attr.civet

Inspired by https://github.com/facebook/jsx/issues/134 but with both a true and false version matching LiveScript

JSX +- toggles like LiveScript object literals

---

source/parser.hera
test/class.civet

Fixes #142
Missing from [this unofficial grammar](https://github.com/frenchy64/typescript-parser/blob/master/typescript.ebnf) so I guessed the order requirements by playing in the Playground.

Support initializers in type parameters

---

README.md
civet.dev/getting-started.md
source/cli.coffee

* Previously, `civet -c` and `civet --ast` ran REPL but ignored options.
* Now `civet -c` runs an interactive transpiler (similar to Playground) and `civet --ast` runs an interactive AST parser.
* Initial message and prompt depend on mode.
* Also fail in case of invalid flag such as `--wrong`.

Compilation and AST modes for REPL

---

civet.dev/cheatsheet.md
source/parser.hera
test/function.civet
test/types/function.civet

Remove need for `()` in defining argumentless functions with `function`:
```coffee
function name
data?.part[0]?.name
function abort: void
process.exit 1
```
One catch is that I removed the ability to have newlines between the function name and the opening parenthesis of the arguments.  Otherwise we have issues with tracking indentation but also the following ambiguity:
```coffee
function f
(x)
```
I'd say this is an argumentless function `f()` that returns `x`.  But currently it parses as the TS function declaration `function f(x)`.
Note that JS does allow
```js
function f
(x)
{}
```
so this is technically an incompatibility with JS... Perhaps there should be a toggle?

Function declarations without parentheses

---

source/cli.coffee

For example, if `civet ... -o dist/.ts` was used and the `dist` directory didn't exist, this PR makes it so that Civet automatically creates it.

Create directory in `-o` option if it doesn't exist

---

source/main.coffee
types/types.d.ts

Utility function to provide a civet error typing

Add type guard function for compile errors

---

.github/workflows/build.yml

Add a job that tests that the docs build in a PR, *before* we merge and the docs fail to build/deploy.  Should be in parallel to running tests (though both jobs are redundantly running `build`).
I also noticed that the jobs were running twice on a PR, because they also counted as a `push` (at least for local branches). Now the `push` tests only run on `master`.

Confirm that docs build in CI for PRs

---

source/parser.hera
test/types/function.civet

This was fairly straightforward but had some nuance around the following situations:
```
a < b
a > b
---
a < b,
a >(b)
```
```
class A extends C<T> implements B {
x := 3
}
---
class A extends C<T>(implements(B)) {
x := 3
}
```
That's why I'm using `InlineTypeArguments` and added the `!"implements"` lookahead for implicit application.

Fixes #192

---

source/parser.hera
test/import.civet

This is the first step towards a unified `import` destructuring syntax.

#175 Added preliminary ':' -> 'as' improvement

---

source/cli.coffee
source/parser.hera
test/compat/coffee-for-loops.civet

Fixes #193
`CoffeeForDeclaration` was actually pretty broken: it modified the AST without duplicating the object! But it also removed the `Identifier` type.
Also fix a bug where CLI in `--ast` mode wasn't showing the full AST (just the first couple of levels like `console.log` does).

Fix identifier used only in coffee for loop

---

source/main.coffee
source/parser.hera
test/function.civet

There may still be some caching related improvements but adding this negative lookahead prevents the parens of an arrow function on the following line from being interpreted as arguments in a call expression.
When I added no-cache to many rules the parser became too slow. Probably need to do some Hera and caching improvements in the future to really optimize.

Fixes #205

---

source/parser.hera
test/for.civet
test/if.civet
test/switch.civet

Started cleaning up implicit return insertion.
Made `SingleLineStatements` match `[ws, statement, delimiter][]` interface.
Cleaned up `DefaultClause` and `ElseClause` block handling.
Added returnSymbol ref declaration.

`return` from expressionized blocks

---

source/parser.hera
test/helper.civet
test/types/function.civet
test/types/js.civet

Added support for `this: T` and `@: T` in function parameters. Also added a `js` mode option for `testCase`.

Fixes #228. `this` type in function parameters.

---

source/parser.hera
test/compat/examples.civet
test/function.civet
test/object.civet

We now wrap `ObjectExpression` at the statement level with parentheses. Sometimes this results in an implicit `return` returning an unnecessarily wrapped object but we can optimize that further later.

Wrap object expressions with parentheses at statement level

---

civet.dev/cheatsheet.md
source/parser.hera
test/types/import.civet

For consistency with regular `import` shorthand
(Noticed this while adding to docs.)

`type ... from ...` import shorthand

---

civet.dev/cheatsheet.md
source/parser.hera
test/import.civet

Fixes #243
* Add support for static `import` with assertions, including object literal shorthand.
* Dynamic import assertions already worked; add tests.

Import assertions

---

civet.dev/cheatsheet.md

Emphasizing the "better ES" features first. The goal is to ease
people into the language concepts by first presenting things that
most people feel are obvious, if minor improvements. Then as they
read further present more cool/powerful ideas. They might not
notice the shorthand until it is too late... and then down comes
the net.

Re-order docs to ease people into the Civet mindset

---

source/parser.hera
test/binary-op.civet
test/function-block-shorthand.civet

As discussed in Discord a while back:
Unlike `coffeeCompat`'s `in` operator, `is in` is not restricted by CoffeeScript backwards compatibility.  By mapping `a is in b` to `b.includes(a)`, we enable the ability for the user to override this operator, while still maintaining compatibility with arrays and `NodeList` which already have `includes` methods. Also, `in` is a prefix of `includes` so it's intuitive.
Breaking change: For strings, `is in` now checks for substrings instead of individual characters.  This is in line with Python's `in` operator (and how it's currently documented in the cheatsheet), but different from CoffeeScript's `in` operator.

Change `is in` operator to use `includes` method

---

source/parser.hera
test/types/type-declaration.civet

Fixes #158 
Added support for:
```typescript
type Point =
x: number
y: number
type Point = x: number, y: number
type Point =
x: a: number, b: number
y: c: [string], d: =>
```

Braceless type = and implicit inline braceless types

---

test/infra/import.civet

I realize I never `git add`ed these... Oops.
They do add something like 20% to the test execution time (on my machine, 8.5 seconds vs. 7.2 seconds or so).  Alternatively, we could add them with `.skip`...

Add simple export tests for require/import of package

---

source/parser.hera
test/types/class.civet
test/types/interface.civet

Fixes #254:
* `interface` support for multiple `extends`
* Fix `class` with `extends` and `implements`
I tried adding a `<<` shorthand for `implements`, but `class A < B << C` is currently treated as `class A extends (B << C)` and it seems a bit difficult to bypass (and maybe once we have operator overloading, we wouldn't want to?).  Let me know if you have thoughts on this.

Interface fixes

---

civet.dev/cheatsheet.md
source/parser.hera
test/types/class.civet

Here's my implementation of a shorthand for `implements`, as originally suggested in #254 and using the `<:` notation suggested in #274.
We might want to see if there are any better notations suggested before committing to `<:`.  Or we could merge this and change it later.

`<:` shorthand for implements

---

civet.dev/cheatsheet.md
source/parser.hera
test/for.civet
test/jsx/attr.civet
test/object.civet

Implements the following braced object literal shorthand (the first part of #238):
* `{props.name}` → `{name: props.name}` (and `name={props.name}` in JSX context)
* `{computed()}` → `{computed: computed()}`
* `{x.y?.z?()}` → `{z: x.y?.z?()}`
This PR newly forbids methods with no body. However, `method(){}` specifies an empty body.
Some potentially confusing behavior is that `{ console.log('hello', name) }` is now potentially an object literal (or a block), namely `{ log: console.log('hello', name) }`. This broke one test case that used a weird mix of `for` loop notation: no parens around the condition, but braces around the block:
```coffee
for [i, j] of x {
console.log(i)
}
```
This is still broken: doesn't parse, because `for` loop has no body. Proposal is that `for` loops should use …

Braced object literal shorthand

---

source/parser.hera
test/assignment.civet
test/autolet.civet
test/call-expression.civet
test/chained-comparisons.civet
test/compat/auto-var.civet
test/examples.civet
test/function.civet
test/jsx/indent.civet
test/parentheses.civet
test/types/class.civet
test/types/function.civet

Fixes #272.  As discussed there, this quick fix adds some extra semicolons, as it is based on input instead of generated code.  But I think I covered most if not all cases, including a potential object literal on the next line that might get parenthesized.

Insert semicolons between lines that JS would combine

---

source/parser.hera

Fix #279 by adding a `SimpleStatementDelimiter` that does not attempt automatic semicolon insertion, used just for prologues.

Fix Init being called too late

---

civet.dev/cheatsheet.md
source/main.coffee
source/parser.hera
test/object.civet

Fix `SingleLineStatements` to stay on the same line.
Also cleanup some duplicated code in the grammar.

Fix semicolon method body

---

civet.dev/cheatsheet.md
civet.dev/index.md

In line with some of @tomByrer's suggestions. Keeping cheatsheet simpler, moving "why Civet?" type features to the home page.

move beyond tc39 to home page, slight reorder

---

civet.dev/cheatsheet.md
source/parser.hera
test/property-access.civet

* `x.0.0` -> `x[0][0]`
* `x.-1` -> `x.at(-1)`
There was some discussion on Discord about whether `.5` should become uniformly `[5]` or `.at(5)` for all integers `5`.  I went with a pragmatic approach: `[]` property access is usually what you want, it's probably faster, it matches `."string"` notation, and it works with more objects; while `.-1` is clearly asking for the last element. It also makes sense in the grammar, because `-` is already not part of the integer literal but rather an operator.
(Counterargument would be that `.at` is more overridable, so maybe mapping everything to `.at` is interesting... but I'm not sure who would really want to override this operator.)
I also wondered about a generic `x@y` shorthand for `x.at(y)`, but Oren pointed out that `-1` is *the* main use of …

Integer property access

---

civet.dev/cheatsheet.md
civet.dev/index.md
notes/Comparison-to-CoffeeScript.md
source/parser.hera
test/binary-op.civet
test/chained-comparisons.civet
test/compat/coffee-not.civet
test/unary-expression.civet

* Make `not instanceof` always work, not just in `coffeeNot` mode. This mirrors existing `not in`, `is not`, etc.
* `!<?` shorthand for `not instanceof`
* Remove unneeded parens around `x <? y` expansion, which otherwise broke automatic semicolon insertion.
* Make `not` a reserved word, as we plan to add it in some form (paralleling `and` and `or` but maybe with different precedence than `coffeeNot`).

`not instanceof`, `!<?`, reserve `not`

---

civet.dev/cheatsheet.md
notes/Comparison-to-CoffeeScript.md
source/parser.hera
test/comment.civet

This started as a documentation commit, but I discovered that `###...###` didn't support `*/` inside. That matches CoffeeScript behavior but not the existing behavior of JSX `` comments, and it was an easy copy/paste to make it work in both.  I think it's nice to have a way to comment out a block of code that already has `/*...*/` comments.

Escape `*/` in `###...###`, document `###` and `coffeeBoolean`

---

civet.dev/cheatsheet.md
source/parser.hera
test/jsx/attr.civet
test/object.civet
test/strings.civet
test/template-literal.civet

Refactor StringLiteral vs. TemplateLiteral
* `StringLiteral` is now always a string literal; no more `BasicStringLiteral`
* `TemplateLiteral` now contains all CoffeeScript string interpolations (`"` and `"""` and even `'''` which transpiles to a template literal), though occasionally returns `StringLiteral` when there is no interpolation.
* Fixes #289
* Important to check for CoffeeScript double-quoted strings via `TemplateLiteral` before regular double-quoted strings via `StringLiteral`.
Bonus feature (separate first commit): add support for template literals as object keys (by wrapping in brackets).

Refactor StringLiteral vs. TemplateLiteral

---

source/parser.hera
test/switch.civet

Pattern matching is getting closer.

wip object pattern matching

---

civet.dev/cheatsheet.md
source/parser.hera
test/assignment.civet

This PR transforms `x op= y` into `x = op(x, y)`, with the idea that `op` is a user-defined binary infix operator.
However, I have not restricted this to identifiers that have been blessed via `operator`. It just works for all identifiers. I think this is a good idea, but it does have the following impact:
> `x y= z` used to parse as `x(y=z)` but now parses as `x=y(x, z)`
But note that spaces are required before and after `y=`, and the space before can't include a newline, which prevented falsely matching all existing tests.  For example, `x y=z` still means `x(y=z)`.
If we think this is too risky, we could protect it behind blessed operators with a one-line change.

operator= assignment

---

lsp/source/server.mts

Continuing discussion from #304:
* No more `setInterval`, so no work when idle
* Schedule updates to other documents after an entire batch completes
I tested and this seems to work well.  The delay of 50 does seem to be necessary though.

Improve LSP queuing behavior

---

source/parser.hera
test/class.civet
test/object.civet

* Make `super` property access more like general property access
* `super[i...j]` and other splice forms (calls `super.splice`)
* `{super.foo}` and `{super[foo]}` object literal shorthand

Improve super property support

---

civet.dev/cheatsheet.md
source/parser.hera
test/object.civet

* Fix (flip) renaming order: a.{b:c} -> {b: a.c}
* Allow a.{b.c} and other member/call expressions

Object globs, v2

---

civet.dev/cheatsheet.md
source/parser.hera
test/assignment.civet
test/binary-op.civet
test/compat/coffee-for-loops.civet
test/compat/coffee-not.civet
test/compat/coffee-of.civet
test/compat/examples.civet

As suggested by @samualtnorman:
* `^^` and `xor` are logical XOR operators (but `xor` is not a reserved word), to `^` as `||` is to `|`.
* `!^` and `!^^` and `xnor` are logical XNOR operators (logical equality), by analogy to `!=`/`!==`. (Should I add `not xor` too?)
* Assignment versions of all of the above, e.g., `xor=`
Normally I'd write these as `Boolean(a) !== Boolean(b)` and `Boolean(a) === Boolean(b)`, respectively. But `xor` has a much more clear meaning, and these should shortcut properly and use `a` or `b` as values instead of `true` and `false` whenever possible, similar to `&&` and `||`.
In a separate commit, added semicolons to prelude ref declarations; otherwise a `(` on the next line will prevent automatic semicolon insertion. For example, [`(x %% y)` in the first line …

xor/^^ and xnor/!^ operators

---

civet.dev/cheatsheet.md
source/parser.hera
test/object.civet

(More of part 4 of #238.)
`obj.{a, b, ...rest} = data` → `{a:obj.a, b:obj.b, ...obj.rest} = data`
* This is clearly the right thing.
`obj.{a, b, ...c}` → `{a:obj.a, b:obj.b, ...obj.c}`
* This is useful e.g. to merge subobjects: `obj.{...defaults, ...globals, ...user}` → `{...obj.defaults, ...obj.globals, ...obj.users}`
* Also clearly mirrors the assignment form.
* Originally I thought that `obj.{a, b, ...c}` should mean something like `{a, b, ...c} = obj, {a, b, c}`, i.e., extract the "rest" into `c` and make it into an attribute. But I think this is a little too magical, restricted to a single `...spread`, and isn't actually the intuitive thing for a non-assignment. The fact that the implemented syntax does this for actual assignments suggests it's the right thing in both cases.

Spreads in object globs

---

source/parser.hera
test/assignment.civet

One idea from #317:
```js
(obj[key] ?= 0) += 1
---
(obj[key] ?= 0), obj[key] += 1
```
Now though I wonder whether assignment expressions is actually the right time to do this, because another natural example `(x ?= 0)++` does not work.  (Well, Civet is fine with it and leaves it as is, but JS is not fine with it, as `x ?= 0` is not a valid LHS, which is what this PR is trying to fix.)  I'd appreciate suggestions on *where* to do this transformation.  Currently the AST doesn't have the ability to go to the parent node, which makes it hard to look at all assignments and then replace itself.  I guess the `AssignmentExpression` node could rewrite its own contents (and even become a different type of node), but I don't know how (or even where) to add the assignment operation as a "pre" …

Inner assignments within assignment chains

---

test/assignment.civet
test/conditional.civet
test/function-application.civet
test/function.civet
test/helper.civet
test/if.civet
test/indent.civet
test/jsx/attr.civet
test/jsx/indent.civet
test/jsx/test.civet
test/numbers.civet
test/object.civet
test/pipe.civet
test/regex.civet

While still offering backward-compatible mode of just code (still used in some batch tests)

Test helper `throws` supports description and ---

---

civet.dev/cheatsheet.md
source/parser.hera
test/assignment.civet

Sequel to #348 (further advancing #317) to also support update operators `++`/`--`. Some fun consequences like `++x++` → `++x, x++`.  Also realized that `x++ *= 2` should probably compile to  `x *= 2, x++`, i.e., putting the inner assignment *after* instead of before the outer assignment, to preserve typical post-`++` semantics.

 Allow assignments and update operators within assignments and update operators ++/--

---

source/parser.hera

`:label` or `$:` for Svelte
This is enough for Svelte compatibility (#351).
But we should also add label support to `break` and `continue`. I just think we should discuss the other potential uses mentioned in  https://github.com/DanielXMoore/Civet/discussions/312#discussioncomment-4832062 first.

Support for labeling statements

---

source/parser.hera
test/switch.civet

As discussed in Discord: a new flag!

Prevent `case:` from implicit object literal

---

source/cli.coffee
source/generate.coffee
source/parser.hera
test/compat/coffee-for-loops.civet
test/function.civet

I used what I learned from writing #359 to fix #361 and this time keep things particularly clean.
Extra features:
* Simpler global ref resolution from #359 (necessary if `return.value` is used within a loop, and `ret` is used only outside)
* Add parent pointers and `findAncestor` helper
* Remove parent pointers during prune
* CLI error handling when AST fails to `JSON.stringify` (helped figure out that I need the previous)
* `getIndent` helper extracted from `insertReturn`
* `gatherRecursive` gains a `skipPredicate` (not strictly necessary but convenient)
* `gatherRecursiveWithinFunction` to search just within this function (probably would simplify `autoVar` code)
* `isFunction` helper

return.value and return =

---

source/parser.hera
test/property-access.civet

Fixes #367
* Explicit braces re-enable everything
* Indented block re-enables everything
* Add tests for trailing member properties on/off

Trailing member properties in blocks

---

source/parser.hera
test/slice.civet

Fixes #365
I went with the CoffeeScript approach of just allowing `..`, not `...`, to avoid conflict with spreads, though we could add both...

x[..] slice

---

source/parser.hera
test/switch.civet

This aggregates duplicate bindings with the same identifier in pattern matching. Since there can only ever be one identifier with the same name in a scope merging more than one bindings into an array makes a lot of sense to me. Adding an implicit suffix seems like it would be hard to discover when adding or removing identifiers. TS should provide decent support and highlighting if you weren't expecting an array.
There are probably some other cases where this doesn't work but I'll fix those at a later time.
Part of #335

Aggregate duplicate pattern matching bindings

---

source/parser.hera
test/do.civet
test/switch.civet

Fixes #58, via the simpler approach. It's equivalent to wrapping in braces, unless it's used as an expression, in which case it gets an IFFE.
We can later explore the plan to remove IFFEs when possible, but this is nice for allowing declarations (even local `var`s) in the block. I think we also want to do this implicitly for `if` like CoffeeScript does, but that's (yet) another issue.
#202 tracks the issue that `return`s are forbidden within expressioned statements like this.

do expressions wrapping in iffe

---

source/parser.hera
test/function.civet
test/try.civet

This adds implicit `return`/`results.push` inside implicit catch blocks.
A couple things to note:
- CoffeeScript doesn't push for implicit catch so we may want to call that out in the docs.
- Truly implicit returns may imply that `->` should become `function(){return}` but I'll need to think it through a bit before committing to such a thing.

Fixes #369

---

source/parser.hera
test/pipe.civet

Fixed some things still more to do before it's perfect.
Also note: pipelines that add a `return` can't be used in expression position. I think a big follow up will be to normalize all the block expressionization. Also related to hoisting ref decs that end up used inside expressions.

#387. Improve thick pipe return; pipe after inline arrow expression

---

source/main.coffee
source/parser.hera
test/pipe.civet

Better dedent handling for binary ops and pipes.
The BinarOpRHS dedent change is unnecessary for this fix but it doesn't break any tests so far and it gets us closer to having the same rules for dedenting everywhere.

Fixes #387

---

source/parser.hera
test/types/class.civet
test/types/let-declaration.civet

`let foo!: T` and class members `foo!: T`
Reported missing in Discord

TypeScript non-null declarations

---

README.md
civet.dev/.vitepress/components/Hero.vue
civet.dev/index.md
civet.dev/philosophy.md

Also rename to Design Philosophy
I wasn't quite sure where to put the link from the README. It could go at the bottom where the philosophy was before, e.g. as a linked header. Currently I've put it at the top nest to documentation.

Move Philosophy to civet.dev

---

source/parser.hera

- Don't add parent pointers to arrays
- Update parent pointers after adjusting subtrees in pipe and pattern matching

Parent pointer cleanup

---

source/parser.hera
test/compat/coffee-for-loops.civet

Matches behavior of regular `for..of` loops, as well as CoffeeScript behavior: [example 1](https://coffeescript.org/#try:for%20x%20in%20y%0A%20%20z%3A%20w), [example 2](https://coffeescript.org/#try:for%20x%20in%20y%20by%20z%0A%20%20z%3A%20w), [example 3](https://coffeescript.org/#try:for%20x%20in%20y%20when%20z%0A%20%20z%3A%20w)

Prevent indented application in Coffee for loops

---

source/main.coffee
source/parser.hera
test/array.civet
test/if.civet

Matches [CoffeeScript behavior](https://coffeescript.org/#try:%5Ba%0A%20b%3A%20c%0A%5D%0A%0Aif%20%5Bfoo%0A%20%20a%3A%201%0A%5D%0A%20%20x%0A%20%20%0Aif%20%5B%0A%20%20foo%0A%20%20%20%20a%3A%201%0A%5D%0A%20%20x)

Forbid indented application in first line of array literal

---

source/parser.hera
test/binary-op.civet
test/do.civet
test/function-block-shorthand.civet
test/try.civet

Fixes #355 by replacing all IIFE code (that I could find anyway) with a new `module.wrapIIFE` helper that checks for `await` in the wrapped expression (without crossing a function boundary) and wraps accordingly.
One thing: I'm not sure what was meant by "Fix `catch { c }`" in #355. Is this about whether `catch` should return a value? Should we split that off into a separate issue?

Automatically await/async expressionized statements with await

---

civet.dev/cheatsheet.md
source/parser.hera
test/do.civet
test/for.civet

`async` variation of iteration expressions, including simple `do`, which build a promise for the results by making the IIFE wrapper `async`.
For example, `async do` lets you build a Promise easily using `await` syntax:
```coffee
promise := async do
await f1()
await f2()
---
const promise = (async ()=>{ {
await f1()
return await f2()
}})()
```
Fixes #292 which shows a nice example of using this in a `for` loop to do `await Promise.all` in parallel.
Similarly, `async for` returns a promise that resolves to the returned array, once all `await`s are complete (in sequence):
```coffee
promise := async for x of y
await f(x)
---
const promise = (async ()=>{const results=[];for (const x of y) {
results.push(await f(x))
}; return results})()
```
Having this as an option is essentially what …

async do, async for

---

civet.dev/.vitepress/components/Playground.vue
civet.dev/.vitepress/store/ligatures.store.ts
civet.dev/.vitepress/theme/custom.css
civet.dev/.vitepress/utils/ligatures.ts

* Implement argeento's comments
* Put shared state in `civet.dev/.vitepress/store`
* Ligature toggle state remembered in localStorage (when possible)
* Clicking on "Ligatures" label toggles the checkbox
* No more blinking when toggling for the first time (while font loads)

Improve ligature toggles

---

source/parser.hera
test/jsx/attr.civet

Fixes #405 by not processing plain JSX strings at all.
> Another option would be to convert the `\n` to ` ` in JSX.
Interestingly, this is what [CoffeeScript does](https://coffeescript.org/#try:%3Cdiv%20class%3D%22hello%0A%0A%0Aworld%5Cn%5Ct%22%2F%3E). (It even seems to convert multiple newlines into a single space.)  I guess it's fine with `class`, but I like better the approach of just leaving the string alone in this case.
One inconsistency I noticed is that `\t` and other escape characters are normally ignored (the backslash remains a backslash) in JSX strings.  But if you use an interpolated string (CoffeeScript's `"#{foo}"` or Civet's always-available `"""#{foo}"""`), which turn into a braced template string, then the backslashes are processed.  This is [consistent with …

Leave plain JSX strings alone, including newlines

---

source/parser.hera
test/switch.civet

Allow pattern matching for reserved word keys by binding to inaccessible refs.
Link: #335

Pattern Matching

---

source/parser.hera
test/types/enum.civet

Fixes #227.
The fun part here is the JavaScript code generation.  I tried to (roughly) follow the rules in [the documentation](https://www.typescriptlang.org/docs/handbook/enums.html#computed-and-constant-members), but I didn't enforce as many rules because I believe these simple rules work whenever TS considers the enum valid, and we can rely on TS checking for validity.
Note that TS [doesn't generate back references for string values](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEEQBd4A8Bc8CuA7A1rgPYDuuANPAJ5Z6GkXwBmRRWUuVAsAFC8i5sAW3gARAJZwwycUVzwA3r3jwAqgAd4AXngAibOt3llYhtvgADYAwvGeKgDIgmqHQEY7KgEriA5gAtXPRg-QKNeAF9eIA) (and it doesn't support mixing strings with "computed" types, so we don't need to detect e.g. a variable of type `string`).
TS also puts all of this inside a …

enum support

---

source/parser.hera
test/for.civet
test/function-application.civet

I've long wanted to be able to do this (CoffeeScript doesn't allow it):
```coffee
func for x of y
x * 2
```
As @STRd6 suggested, this checks for `IterationExpression`s without any body (e.g. a single semicolon) and skips in that case to enable a postfix iteration. Seems relatively easy!
I am a little worried about weird interaction with caching if we end up parsing the iteration body multiple times and getting the indentation wrong the second time (which happened in #398)... but so far it seems to work in all cases. (And this would hopefully be fixed by #341.) A workaround if it ever happens would be to add an explicit semicolon after a postfix iteration.

Call with unparenthesized iteration expression argument

---

source/cli.coffee
source/parser.hera
test/comment.civet
test/top-level.civet

* Enforce consistent indentation at the top level.
* Allow comments at the beginning of statements.
This was surprisingly difficult to get right, especially while producing output compatible with the past.
I explored redoing statements into actual AST nodes like `{type: "Statement", indent: "  ", statement: <statement without indentation>, children: [eos, indent, leadingComments, statement]}` instead of relying on `[indent, ...rest]`, but it was getting to be a rather huge effort.

New top-level statement system

---

source/parser.hera
test/block-strings.civet
test/template-literal.civet

In the string processing we weren't pulling the backslash escaped characters with the backslash so they ended up double escaping.

Fixes #416: Fix handling of backslash escapes inside strings that convert to template strings

---

source/parser.hera
test/types/class.civet

This allows decorators in TS "before export" and TC39 "after export" positions and doesn't try to do anything smart about it yet.
I added another state flag for when we are inside `Decorators` to prevent `@@decorator class ...` from being treated as an implicit call passing a class expression to the decorator function. If someone really wants to do that they'll need to use parentheses and be explicit.

Fixes #420 Decorate exported class

---

source/lib.js
source/parser.hera
yarn.lock

Proof of concept using Hera's new codeblocks support. Now we can `require` any other source file. This will make it much easier to split out the complicated processing steps from the AST parsing and we can even get typechecking or use .civet for our transforms soon.

Codeblocks!!!!!

---

source/parser.hera

TrailingComment includes // comments and those can't appear in the middle of a single line statement (it would comment out the rest of the line). So now we only check for inline comments in most places except statement delimiters which should have the rest of line trailing comments attached to them so they don't get attached to enclosing blocks.

Replace TrailingComment* with _? except after statement delimiters.

---

CONTRIBUTING.md

It looks like `grammar.hera` is deprecated and `parser.hera` has taken its place, this PR removes references to `grammar.hera` in `CONTRIBUTING.md`

♻️ change grammar.hera to parser.hera

---

source/esbuild-plugin.civet
source/lib.js
source/parser.hera
test/class.civet
test/compat/coffee-classes.civet
test/function.civet
test/infra/esm.civet
test/infra/import.civet
test/object.civet

- Implicit async for functions, arrow functions, and methods.
- Implicit generator for functions, thin arrows, and methods.
Fixes #427

Implicit `async` and `*` for functions and methods

---

civet.dev/cheatsheet.md
source/lib.js
source/parser.hera
test/compat/coffee-for-loops.civet
test/for.civet

Fixes #412 and fixes #440
* Factor out RangeLiteral loop generation code into `lib.js` (new `forRange` helper)
* Cleanup ref handling with new `needsRef` and `maybeRef` helpers
* Fix missing use of ref for `asc` and `step` (previously would shadow/use the wrong variables)
* Fix `blockPrefix` mechanism with bare block (#440)
* Optimize `for x of [a..b]` in the same way that we did for CoffeeScript `for x in [a..b]` (#412)
* Support `for [a..b]` (a CoffeeScript feature) both inside and outside `coffee-compat` mode (#412)

For loop optimizations and generalizations

---

source/parser.hera
test/if.civet

`a; b` was supported at the top level but not in deeper blocks, e.g., within an `if`!
This adds support to both regular blocks and if/else expressions.  It also refactors the top-level support to be cleaner, before I copied it two more times.

Semicolon-separated statements in blocks

---

source/lib.js
source/parser.hera
test/class.civet
test/compat/auto-var.civet
test/compat/coffee-for-loops.civet
test/compat/coffee-of.civet
test/compat/examples.civet
test/examples.civet
test/for.civet
test/function.civet
test/top-level.civet
test/while.civet

A lot of the block additions are more consistent now and mostly improved. One liners remain one liners (so we have to insert more semi-colons). Indentation is mapped from a statement in the block into the statements in `blockPrefix`.

Refactor block indentation

---

source/main.coffee
source/parser.hera
test/await.civet

Fixes #473
I tried just adding support directly to `AwaitOp`:
```diff
diff --git a/source/parser.hera b/source/parser.hera
index 77ab5ec..ae55026 100644
--- a/source/parser.hera
+++ b/source/parser.hera
@@ -2850,7 +2850,7 @@ UnaryOp
AwaitOp
-  Await:a ( Dot IdentifierName )?:op ( _ / &OpenParen ):ws ->
+  Await:a ( Dot IdentifierName )?:op ( &OpenParen / _ / IndentedFurther ):ws ->
if (op) {
return {
...a,
```
But `UnaryExpression` only allows `UpdateExpression` children, but we need `ExpressionizedStatement`.  So I've added part of `NonAssignmentExtendedExpression` (which already had nice `Nested` logic) as a possible child for `UnaryExpression`.

Indentation after await operator

---

README.md
civet.dev/getting-started.md
civet.dev/integrations.md
source/cli.coffee
source/esm.civet

* `civet filename.civet` now works with code that `import`s `.civet` or `.js` files (in new ESM mode)
* `@danielx/civet/esm` now transpiles with `js: true` so we don't *always* need ts-node

CLI can run ESM scripts via import

---

source/main.coffee
source/parser.hera
test/export.civet
test/object.civet

Fixes #478 by forbidding commas at the end of an inline object literals or implicit `export` list.
The intuition is that commas indicate a continuation onto the next line in these cases, so we can't have arbitrary content on the next line, only more items.
These are now forbidden:
```coffee
a: 1,
b: 2,
```
```coffee
a: 1, b: 2,
```
This matches CoffeeScript behavior, which [forbids](https://coffeescript.org/#try:a%3A%201%2C) [both](https://coffeescript.org/#try:a%3A%201%2C%0Ab%3A%202%2C).
**Open question:** I'm not sure that the above really need to be forbidden, when at the top level like this.  Mainly I want to forbid the second one in an inline context like function arguments.
Non-inline object literal with extra commas are still allowed, [as in …

Inline implicit object literals can't end with comma

---

source/parser.hera
test/jsx/test.civet

Implicit JSX elements.
Defaults to `div` but can be set with `"civet defaultElement=span"` etc.
```
<.main>
```
```
<div class="main" />
```
```
"civet defaultElement=span"
<.app>
```
```typescript
<span class="app" />
```
Currently limited to requiring `.class` or `#id` because it could be ambiguous with some JSX attributes.

implicit JSX element

---

register.js
source/cli.coffee
source/esm.civet
source/main.coffee
source/util.coffee

* Install `@cspotcode/source-map-support` in CJS mode via `register.js`, including `hookRequire: true` flag needed for CJS mode
* Fix `esm` loader to use correct cache filename and thereby enable `@cspotcode/source-map-support` to find source maps
* Modify `SourceMap.remap` to just use our sourcemap when downstream code has no sourcemap (e.g. no further loaders). Avoids "No source map found in code" error.
* Refactor code to only encode SourceMap in one place (using new `SourceMap.remap`)

Fix sourcemap support from CLI

---

source/esm.civet

Fixes #490
Good point in https://github.com/DanielXMoore/Civet/issues/490#issuecomment-1493166386 that we can remove `.tsx` after finishing the transpilation chain.
`process.argv[1]` now gets set to a valid file, so `process.argv[1] === url.fileURLToPath import.meta.url` works!

Remove tsx after ESM transpilation

---

civet.dev/cheatsheet.md
source/parser.hera
test/jsx/attr.civet
test/jsx/test.civet
test/property-access.civet

As discussed in Discord:
* `x@y` and `x@.y` → `x.y.bind(x)`
* `@@x` and `@@.x` → `this.x.bind(x)`
* Longer chains, optional property access, and non-null assertions also work
* No shadowing of `@@` decorators (this came for free, I guess because they are checked first)
* (No refs yet)
I also noticed that a bunch of updates to how properties work hadn't made it to the JSX fork. So I also fixed unbraced attribute values with:
* Additional access or calls for `super` properties and dynamic `import`
* Object globs
* New bind shorthand
* Bug fix: `<input checked/>` didn't work because of our "assert there's a following space" (to avoid invalid class name shorthand) didn't allow for `/>`

x@y and @@x bind shorthand, plus JSX fixes

---

civet.dev/cheatsheet.md
source/lib.js
source/parser.hera
test/jsx/attr.civet

As suggested in https://github.com/DanielXMoore/Civet/pull/506#pullrequestreview-1386556568

JSX unbraced @ and @@ shorthand

---

source/lib.js
source/parser.hera
test/switch.civet

This fixes duplicate binding merging for ArrayBindingPatterns and adds support for merging with BindingRestElement as well.

Pattern matching gather duplicate bindings

---

source/parser.hera
test/types/type-declaration.civet

This is probably the least important thing I could do, but it was bugging me slightly, so...
Maybe it's a model for other whitespace tweaks.

Small whitespace fix for trailing splat

---

civet.dev/getting-started.md

It [looks like](https://github.com/DanielXMoore/Civet/blob/b57e75e6c6dbd8acbbf542c7e67cc017958fbecd/lsp/build/build.civet#L19) `civetPlugin` is a function. I changed the documentation accordingly. 
ciao!

Fix a typo when loading `civetPlugin`

---

source/lib.js
source/parser.hera
test/types/class.civet
test/types/function.civet

Following up on #540 discussion, this PR makes `function`s also have an implicit empty block when they're used in an expression context (e.g. not a `declare` block, and not a braced object literal), similar to methods behavior added in #540. Also added tests for both.

Function implicit bodies

---

source/parser.hera
test/class.civet
test/property-access.civet

Fixing #539 turned out to be easier than expected because we already had a flag. The code was buggy though. 😅 
Fixes #539, and fixes `ClassImplicitCall` rules which used the wrong flag and were backwards. Whoops!

Fix implicit calls with bind and decorators

---

build/build.sh
build/esbuild.coffee
lsp/package.json
lsp/source/lib/typescript-service.mts
lsp/yarn.lock
package.json
source/cli.coffee
source/config.coffee
source/main.coffee
source/parser.hera
types/types.d.ts

Add `--config` option to specify a config file,
otherwise looks for a `config.civet`, `.civetconfig`, or `civet.json` file in the current directory and all parent directories. If found, it is loaded and used to override the default options.
config.civet and .civetconfig get compiled & run, but can't import other civet files.
- `export default`s the config object
civet.json is just parsed as json

Implement config file

---

source/parser.hera
test/types/type-declaration.civet

I'm pretty sure this is the correct place in the grammar because of this example: https://www.typescriptlang.org/play?experimentalDecorators=true#code/C4TwDgpgBAKlC8UCuA7A1ig9gdxQKFEigFUEoBnYAJwEsUBzPAY0xUqgA8AuKAMligAfEmQBEITKKA

Added optional prefixed union syntax for TypeScript. Fixes #544

---

notes/Comparison-to-CoffeeScript.md
source/lib.js
source/parser.hera
test/assignment.civet
test/object.civet
test/unary-expression.civet

* Add support for `not x` → `!x` in all cases, not just coffeeCompat
* Note that `not` was already a keyword; it just didn't do anything by itself, only in `is not`, etc.
* Fix `not: 1` (using `not` as an object property, which was previously broken in coffeeCompat mode)
* Fix `not  x` (previously didn't support more than one space)
* Keep support for `not op` except in coffeeCompat mode
* Some code cleanup
Spun off from #548 as suggested in https://github.com/DanielXMoore/Civet/pull/548#issuecomment-1601149303

`not` support outside coffeeCompat mode

---

civet.dev/cheatsheet.md
source/parser.hera
test/binary-op.civet
test/function.civet

For fun, here are some simpler and less controversial Unicode operators from #555.
The only one I'm less sure about is `≡` mapping to `===`. But given that `≠` makes `!=` and `≢` makes `!==`, this feels natural. And anyway it's good to encourage `===` over `==`. Alternatively, we could use `≣` for `===` and `≡` for `==`...
Incidentally, TIL there are symbols for double and triple equals: `⩵` and `⩶`.
Going forward:
* I'm less sure about the symbols with equals and such because they look like comparisons to me, but Civet uses them as assignments.
* I think the power operators, specifically `²`, would be handy, but that's a little more complicated, so left for the future.
* If there are other Unicode operators you think I should add now, let me know!

Unicode operators ≤≥≠≢≡≣⩶⩵«»⋙‖⁇∈∉∋∌▷‥…≔→⇒

---

source/lib.js
test/object.civet

Fixes #566
I wonder if we can craft a helper function, as parenthesization for refs is done in a couple places (e.g. `processPatternMatching`, which currently seems to add parens even if there are no refs — not sure whether that can be improved).

Add missing parentheses to glob assignments with refs

---

source/parser.hera
test/function.civet
test/if.civet

Fix #559 as discussed in https://github.com/DanielXMoore/Civet/issues/559#issuecomment-1624411555
`{}` will be treated as an empty block if it starts on the same line as the `if`, and if it's on an unindented line.  But if it's on an indented line, it will be treated like an object literal.
I feel like this is sufficiently JS compatible, because the difference between doing nothing and creating an empty object literal (and similarly for doing something vs. creating an object literal with that something) only matters when interacting with implicit returns or `if` expressions, which are already differences from JS anyway.
I also ran into a weird bug with `if (x) {} else {}`, but that's for another issue/PR.

Fix empty objects in if statements

---

source/parser.hera
test/if.civet

Fixes #572
This makes me wonder the following: is it safe to modify `$0` in place?  In this case it isn't pretty (`$0.splice(2, 0, expressions)`) but often we want to just replace a specific item in `$0` with a wrapped version.

Fix missing closing braces

---

civet.dev/cheatsheet.md
source/lib.js
source/parser.hera
test/compat/examples.civet
test/examples.civet
test/existential.civet
test/function-block-shorthand.civet
test/if.civet

* Chaining logical operators with existence operator `x?` (but without `null` being chained)
* As discussed in Discord
* Matches CoffeeScript
* Support `&?`
* Fix `!.x?`
* Fewer parentheses given unary context
* New `Existence` AST node
* `UnaryExpression` AST nodes more consistently
* `ParenthesizedExpression` has `implicit` property if auto-generated
* Documentation

Existence operator chaining and cleanup

---

source/parser.hera
test/types/function.civet

1. Fix #562 (again) by supporting `abstract new`. See https://www.typescriptlang.org/docs/handbook/2/classes.html#abstract-classes-and-members
2. Fix #579 by supporting `asserts` and `is` predicates in arrow types (previously was supported only in `function` colon annotations).

Arrow function types fixes: `abstract new` and `asserts`/predicates

---

source/parser.hera
test/binary-op.civet

Fixes #511 by forbidding custom infix operators to start at beginning of lines; must be strictly indented. 
By contrast, regular operators like `+` can appear at the start of lines.  I also allowed `not op` at the beginning of a line for a custom infix operator `op`, as that seems more intentional (but not totally sure about this).

Fix weird custom operator behavior

---

source/lib.js
source/parser.hera
test/for.civet
test/if.civet

Fixes #582 by allowing on-their-own-line not-dedented `CallExpressionRest` after all `ExpressionizedStatement`, if `TrailingMemberPropertyAllowed` is true.
We had a facility for `TrailingMemberExpressions` but not for `TraillingCallExpressions`.  This sufficed in the past because the trailing member was previously used in a `CallExpression` context, so the call part got captured there.  Here we haven't started a `CallExpression` so I had to build some more rules.
This PR allows for this form from https://github.com/DanielXMoore/Civet/issues/582#issuecomment-1636989322:
```coffee
sorted :=
for item of list
item.toString()
.sort()
```
In the third commit, I also modified the indentation rules in `NestedNonAssignmentExtendedExpression` to allow the originally requested indentation of #582: …

Allow trailing CallExpression after ExpressionizedStatement

---

source/lib.js
source/parser.hera
test/types/function.civet

Fixes #591 introduced by #542: exported functions should never get an implicit empty block.
Also refactored some ancestor finding code. (At some point I used the refactored code for this purpose, but then realized I didn't really need to recurse, only check parent. Still, should be useful for more hoisting later.)

Fix export functions getting implicit empty blocks

---

source/parser.hera
test/switch.civet

* Allow same-line bodies after `case ...:` and `default` (`else` already worked)
* No longer allow `case 1:, 2:` (which seems pretty weird)
* Fix #593 by forbidding same-line object literals too
* New `InsertColon`, `IgnoreColon`, and `BareBlock` rules
Thanks to the `CaseExpression → PropertyName &Colon` rule for #593, all tests now pass if we remove `ForbidMultiLineImplicitObjectLiteral`/`RestoreMultiLineImplicitObjectLiteral` from the `CaseExpressionList` rule. This is the only place this rule is used. Can you think of another context where it would be useful, or should I remove the entire `ForbidMultiLineImplicitObjectLiteral` mechanism?

`switch` fixes

---

source/lib.js
test/auto-let.civet
test/compat/auto-var.civet

autoVar/autoLet should treat `=>` and methods same as functions

---

civet.dev/cheatsheet.md
source/parser.hera
test/property-access.civet

Inspired by [this tweet](https://twitter.com/judofyr/status/1685580152565055488), [this follow-up thread](https://twitter.com/nicuveo/status/1685745407421284352), and [_hyperscript](https://hyperscript.org/expressions/possessive/), via Discord: `'s` followed by whitespace simulates `.`.
```js
mario's brother's name
↓↓↓
mario.brother.name
```
In Unicode, `’s` works too.
I think there are contexts (such as the example above) where this improves readability of code, so seems like a generally good thing. Of course, this might deserve some discussion about whether this feature is a good idea.
The one thing this breaks is template strings starting with `foo's `. Previously, `foo's s'` compiled to ``foo`s s` ``. My sense is that this is not a big deal though; single-quoted template strings …

Possessive object access

---

source/lib.js
source/parser.hera
test/auto-let.civet
test/examples.civet
test/function.civet
test/if.civet
test/switch.civet

In the spirit of "everything is an expression", and e.g. `if x := 5`
BREAKING CHANGE: `x := 5` now implicitly returns `x`
More complex example:
```js
->
let x = 5, y = x
↓↓↓
function() {
let x = 5, y = x;return y
}
```
Oren motivates it as giving a name to the return value, which helps define a semantic meaning.  It can't really have much other purpose.
I'm pretty sure I remember @STRd6 saying he preferred this behavior. Could be worth a minor version bump though given that it would break some code that uses declarations to prevent return (but this seems like bad practice).
Also fix a bug in `names` computation for `var` declarations. If we don't merge this PR, we should at least fix that.

Implicit returns of (last) declaration

---

source/parser.hera
test/types/type-declaration.civet

Fix #534 again
This was tricky to debug. The trouble is that `foo: bar,` is a valid type (equivalent to `{foo: bar,}`, as in CoffeeScript), which meant that `Type DotDotDot` was matching `foo: bar, ...` where the `...` is from the next tuple entry!  To avoid this, this PR checks for all possible named tuple entries first, and only upon failure checks for `Type DotDotDot?`.
I also moved `TypeTuple` up in the `TypePrimary` list, as it should fail early via the initial OpenBracket. Just a hunch that this is more efficient.

Fix tuple-matching behavior

---

source/parser.hera
test/switch.civet

Fix #607
I forgot we had this flag. 😅 Made this really easy to fix!

Forbid binary op after newline within SingleLineStatements (e.g. `then`)

---

source/lib.js
source/parser.hera

Replaced by #594 (as discussed there)

Remove forbidMultiLineImplicitObjectLiteral

---

source/parser.hera
test/object.civet

Fix #589
I should probably redo `ArrayLiteralContent` in a similar way. Currently, it forbids an indented block from starting after a comma (it can only start after an implicit comma from a newline).

Revamp braced object literals

---

civet.dev/cheatsheet.md
source/lib.js
source/parser.hera
test/for.civet

This is the equivalent of CoffeeScript's `for key, value of object`.
It should properly use refs, and supports when `key` is actually a pattern (see tests).

for key, value in object

---

civet.dev/cheatsheet.md
source/lib.js
source/parser.hera
test/for.civet

Sequel to #621: more efficient array-specific loops, as in CoffeeScript's `for..in`.
Also some code cleanup via new `makeRef` helper function.

for each..of

---

source/lib.js
source/parser.hera
test/do.civet
test/for.civet

Fixes #624
* `hoistRefDecs` needed to happen after expressionizing
* Parent pointers needed updating after `wrapIIFE` so that new wrapping block gets discovered.
* In these situations, `hoistDec` needs to work with raw expressions that lack `[ws, exp, delim]` format.
* Remove some extra array wrapping

Fix hoisting around IIFE

---

source/parser.hera
test/object.civet

Fix #628 using the "right" interpretation for both 1 and 2-property indented implicit object literals.  This turned out to be a one-line change. But it differs from CoffeeScript's interpretation for 1 property.
I didn't make the change for "inline" object literals (which uses `SnugNamedProperty`) because it would change the interpretation of this test from CS's `lexer.coffee`:
```coffee
addTokenData token, initialChunk: yes if i is 0
```
and generally seems dangerous.  Unfortunately, this means that the following doesn't do what you'd expect:
```coffee
function f()
a: 1 if hasA
b: 2 if hasB
```
(This is treated as two top-level statements, the second of which gets implicitly returned.)

Postfix expressions inside indented implicit object literals

---

source/parser.hera
test/object.civet

Followup to #630 based on the discussion there. I found a way to handle postfix expressions in inline object literals, as long as the prop isn't the only prop. I also required a newline (`Nested`) after the postfix; commas seem like they could be ambiguous.

Postfix expressions inside inline object literals

---

civet.dev/cheatsheet.md
source/lib.js
source/parser.hera
test/binary-op.civet
test/class.civet
test/function.civet

Added shorthand for `#a` -> `this.#a` except in the case of branded `in` check.
Could use docs.

Added private this shorthand. Fixes #633

---

source/lib.ts
source/parser.hera

This is the very beginning of switching `lib.js` -> `lib.ts`
I probably won't have the fortitude to finish it all in one go but it works as is and we can continue to improve it bit by bit.
We're no worse off than without the typechecking even if it is so noisy as to not be useful yet.
If we merge this then we can keep adding types and eventually it will be good.

source/lib.js -> source/lib.ts

---

civet.dev/cheatsheet.md
notes/Comparison-to-CoffeeScript.md
source/lib.ts
source/parser.hera
test/compat/coffee-for-loops.civet
test/for.civet

Yet another feature from CoffeeScript for loops:
```js
for own key in object
↓↓↓
for (key in object) {
if (!Object.hasOwn(object, key)) continue;
```
I also switched from `Object.prototype.hasOwnProperty` to `Object.hasProp` (still without using `Object` as an explicit name),
as recommended in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn
Also fixed up types some around this code (but there are still errors).

for own..in

---

source/bun-civet.coffee

The Bun-related instructions are outdated since [Bun 0.5.8](https://bun.sh/blog/bun-v0.5.8).
Couple things:
1. With the "new" loader support .civet files can now be loaded "organically" (`bun file.civet`), there's no need to have a `ts` file where you include your first .civet file that includes the rest 🥰
2. Apart from the steps I included at the top of the file, there's also a way to skip `bunfig` and just pass a `preload` param to the `bun cli` (described in the blog post), but I couldn't make that work. So I only included instructions for the `bunfig` option.
3. We could mention the Bun compatibility and the instructions in the README. I would do it, but I wasn't sure you wanted to, so it's not part of this PR

Updated the Bun-related how-to

---

source/lib.ts
source/parser.hera
test/auto-const.civet

This is about 80% of auto-const by modifying the existing auto-let.
When the assignment appears in an expression it may be very difficult to actually enforce it as const without possibly heavily rewriting the parse tree.
There are still some simple cases that we could improve for both auto-let and auto-const.
This will work great for common situations.
Fixes #527

Initial auto-const

---

source/parser.hera
test/types/enum.civet

Since we're not following up the enum erasure with replacing with the literal values we should generate them in JS too in the meantime.

Fix #564 Implement basic const enums in --js mode

---

lsp/build/build.civet
lsp/package.json
lsp/source/lib/typescript-service.mts
lsp/yarn.lock
package.json
yarn.lock

I think this pull is breaking change so please review it carefully.
- use `typescript@5`: some newly `.ts` file will error when lsp use `typescript@4`. For example type only import `.d.ts` without actual `.ts` file, this technique use by [svelte-kit generated `./$types`](https://kit.svelte.dev/docs/types#generated-types).
- use `esbuild@0.16`: after `esbuild@0.17` api will [break](https://github.com/evanw/esbuild/releases/tag/v0.17.0) on watch mode. so use version that not break.
- print typescript version that civet-lsp use, for clearly say that typescript is come from civet  extension it self.
Before `civet-lsp 0.37`
After `civet-lsp 0.38 (this pull)`
If you need reproduce for this problem just tell me.
By the way. Love this project 😁🎉

Use Typescript 5

---

source/esbuild-plugin.civet

This lets us use `civetPlugin = require "@danielx/civet/esbuild-plugin"` instead of needing to use `.default`.
We can pick it up in `esbuild.civet` after publishing.

Allow more ergonomic require of cjs esbuild plugin

---

source/parser.hera
test/assignment.civet
test/unary-expression.civet

The previous code generated from `test/assignment.civet` wasn't valid JS so this seems somewhat better.

Fix #629: Unary op with late assignment

---

build/esbuild.civet
source/esbuild-plugin.civet

It's still a bit hacky, but at least it doesn't cause esbuild to generate a loud warning.
Tested:
* `require('./dist/esbuild-plugin.js')` in `node` CLI (produces function)
* `import plugin from './dist/esbuild-plugin.js'` in a file `test.mjs` (produces function)
* `yarn test`
Based on https://github.com/egoist/tsup/issues/572#issuecomment-1060599574. Also, it looks like if we used `tsup` for this (we already do for the unplugin), there's a cleaner solution: https://tsup.egoist.dev/#interop-with-commonjs

Warning-free hack for ergonomic require of cjs esbuild plugin

---

source/lib.civet
source/parser.hera
test/compat/coffee-for-loops.civet
test/if.civet

There's some possible follow on discussion/work to do.
Should
```civet
if {x} := y
...
```
also add a condition check for x being non-falsey?
What about:
```
if {x, y} := z
...
```
Should x and y be non-falsey?

Unify pattern matching and declaration conditions

---

source/lib.civet
test/binary-op.civet

I went to try
```civet
x and y is not in z
```
and found out it was busted.
Here's the fix.

Fix 'not in' after logical binop

---

source/config.civet

Before:
```
export default `"%20"`
```
gets imported as " "
Now it gets correctly imported as `"%20"`

properly encoding js import source

---

lsp/.gitignore
lsp/.vscode/launch.json
lsp/NOTES.md
lsp/build/build.civet
lsp/build/build.sh
lsp/integration/project-test/.civet/coffee-plugin.mjs
lsp/package.json
lsp/source/lib/typescript-service.mts
lsp/source/lib/util.mts
lsp/test/util.civet
lsp/yarn.lock

Using dependencies instead of bundling for the lsp's actual dependencies Added @danielx/civet and TypeScript to dependencies Using published @danielx/civet rather than linked
Sped up build by removing ts-node from build step
Removed CoffeeScript support (moved to plugin)
Greatly reduced bundle size by removing CoffeeScript (it pulled in babel which was > 5MB) Struggled to improve breakpoints from VS Code (still doesn't work but connecting Dev Tools debugger does)

LSP Build refactor

---

CONTRIBUTING.md
build/esbuild.civet
source/cli.civet
source/main.civet

It would be nice to be able to output a trace of all the rules including cache hit counts.
This is a start.

basic parser tracing

---

lsp/source/lib/typescript-service.mts
lsp/source/lib/util.mts
lsp/source/server.mts

This continues from lsp build refactor.
Now we reverse map the definitions after forward mapping to look them up in transpiled files.

Fix go to definition

---

lsp/.vscode/launch.json
lsp/.vscode/tasks.json
lsp/build/build.civet
lsp/build/build.sh
lsp/package.json

Later we could add / check the debug flag to mark eternal in when debugging so 200k lines of typescript.js don't lag out the dev tools.

Unbundled only works in debug mode

---

source/parser.hera
test/prologues.civet

In particular this lets `// @ts-nocheck` (which needs to come first) come before `"civet coffeeCompat"`, which was recently requested by @bbrk24.

Support comments before directives

---

source/lib.civet
source/parser.hera
test/block-strings.civet
test/template-literal.civet

Previously, indentation was removed from triple quoted strings based on the first indented line. Now it follows CoffeeScript's policy of removing the indentation shared by all lines. This is a little tricky in the case of tabs.
Once this gets released and we upgrade, it should fix the output of `civet --help`:
```
⟫ civet --help                          (quote-indentation ?$)
▄▄· ▪   ▌ ▐·▄▄▄ .▄▄▄▄▄
▐█ ▌▪██ ▪█·█▌▀▄.▀·•██       _._     _,-'""`-._
██ ▄▄▐█·▐█▐█•▐▀▀▪▄ ▐█.▪    (,-.`._,'(       |\`-/|
▐███▌▐█▌ ███ ▐█▄▄▌ ▐█▌·        `-.-' \ )-`( , o o)
·▀▀▀ ▀▀▀. ▀   ▀▀▀  ▀▀▀               `-    \`_`"'-
Usage:
```

Remove common indentation of triple quotes

---

source/lib.civet
source/parser.hera
test/array.civet
test/binary-op.civet
test/class.civet
test/compat/examples.civet
test/examples.civet
test/function-application.civet
test/function.civet
test/if.civet
test/jsx/attr.civet
test/jsx/indent.civet
test/jsx/test.civet
test/object.civet
test/types/function.civet
test/while.civet

Fixes #757
This ended up also fixing some `while` pattern matching tests, though I can't say I exactly understand why. 😅 (probably the old unwrapping of `condition.children`)

Parenthesize if expressions, remove other excess parens

---

lsp/source/lib/util.mts
source/ts-diagnostic.civet

This PR removes the dependency of `ts-diagnostic.civet` on vscode-specific dependencies as those are only required for the LSP and moves that code back to the lsp dir.

Make ts-diagnostic.civet independent of vscode dependencies

---

source/lib.civet
test/function.civet

Fixes #765
Also Civetify `processReturnValue` (though no types yet).

Default type for `return` declaration

---

integration/unplugin/src/index.ts

Without this change, `import o from "object-inspect"` crashes because of a `require` with explicit extension. unplugin's `transform` tries to load the file path, and without an extension, this crashes. Restricting via `transformInclude` fixes the problem.

unplugin transformInclude to avoid transforming unrelated files

---

integration/unplugin/examples/webpack/package.json
integration/unplugin/src/index.ts

This PR should fix #774 and also make #785 not required. `path.resolve` would not consider the parent path if the child path starts with `/`, which made paths like `/src/main.civet` be considered as system-absolute path instead of project-absolute. `path.join` should take them into account always, and make this work.
The only issue this would face is not supporting system-absolute paths for civet, though I'm not sure if that is a feature that is actually used that much

Fix unplugin path resolution (#774)

---

integration/unplugin/examples/esbuild/esbuild.js
integration/unplugin/examples/esbuild/package.json
integration/unplugin/examples/esbuild/src/main.civet
integration/unplugin/examples/esbuild/src/module.civet
integration/unplugin/examples/rollup/package.json
integration/unplugin/examples/webpack/package.json
integration/unplugin/src/index.ts

Together with https://github.com/unjs/unplugin/pull/345, this will fix eventually #773.
I have tested this (`yarn link`ing to my unplugin fork), using the new esbuild example code.
For now, it might fix watch mode on other build systems. But I wasn't able to test because e.g. Vite dev mode is currently broken (#775).
Update: The types don't work until the unplugin PR gets merged. So maybe we should wait for that.

unplugin calls addWatchFile

---

source/parser.hera
test/comment.civet

This is a followup to #783 implementing the suggestion in https://github.com/DanielXMoore/Civet/pull/783#discussion_r1367750148
I think the code is cleaner, in particular because it doesn't gobble up one or two newlines depending on context.
The new test passes with and without this change, though.

Simpler implementation of comments near Civet directives

---

source/lib.civet

After the initial parse and parent pointer setting, we modify the AST a lot, and rarely do we update the parent pointers.  This PR is a step in the right direction, in particular refining the `addParentPointers` call just added in #792.
This PR adds a lot of missing `updateParentPointers` (a shallow operation that just looks at immediate object children), including via a new helper `makeNode` that we should probably call every time we make a new AST node that has `children` set to something with objects.
> Note: An alternative would be to merge `updateParentPointers` and `makeNode`, by having `updateParentPointers` always return the node. Let me know if you have a preference!
At the more subtle level, I found some missing `addParentPointers` that are needed when we pull part of an AST …

Update more parent pointers along the way

---

source/lib.civet
source/parser.hera
test/binary-op.civet
test/function.civet
test/object.civet

Fixes #751 by making `NoComma` variations of `Statements` used in one-line thin and fat arrow functions.
Another option (which is what I actually implemented first) would be to forbid top-level comma operators (requiring parentheses, say), but this seemed a bit unnecessarily strict.
Also allow comma operator inside parenthesized expressions, which seems desirable in any case.
Also refactor `Expression` names a bit:
* `CommaExpression` allows comma operators; formerly this was called `Expression`, but we use `...Expression` all over to forbid commas, so old terminology was confusing.
* `AssignmentExpression` forbids comma operators (as before)
Also fix handling of `{},{}` which is not a valid JavaScript statement (needs to be `({}),({})`). Similarly for anonymous function expressions.

Forbid comma operator in one-line thin arrow functions

---

integration/unplugin/src/index.ts

This PR fixes a bug introduced in #786 where all absolute paths were considered to be absolute to project which broke vitest as it instead passed system absolute paths. The plugin now first checks for the existence of the path relative to the project, and then to the system.

Check for existence of absolute path in unplugin

---

source/parser.hera
test/assignment.civet
test/binary-op.civet

(Marking as Draft for now until I update xnor as well)
This PR corrects the typing of the xor operator to reflect the fact that it returns one of the arguments unless they're both truthy, as discussed on Discord.
The Discord discussion originally suggested to make it output:
```ts
var xor = <A, B>(a: A, b: B) => (a ? !b && a : b) as unknown as A extends Falsy ? B : B extends Falsy ? (A | B) : (A | B | false);
```
However, interleaving the types and code like this makes the hera code significantly harder to read, and there's already precedent for using `as any` (e.g. `is` being `Object.is as any`).

Update xor typing

---

source/parser.hera
test/function.civet

Fixes #814
We were setting `modifier.async` wrong in two places. 😅

Fix Promise<void> in non-async function

---

source/parser.hera
test/function.civet
test/types/function.civet

Rewrite NonEmptyParameters to include Nested forms.
Fixes #760.  Fixes #811.
As a bonus, functions now get rewritten to put their `this: ...` parameter up front, as required by TypeScript. This sort of handling was natural because all parameters get processed symmetrically now, so we needed to do some filtering anyway.

Indented function parameters

---

civet.dev/reference.md
source/parser.hera
test/function-block-shorthand.civet
test/pipe.civet

As discussed in Discord, it's nice to be able to assign to properties in a pipeline, especially fat, as an alternative to `..` cascade notation.  The DOM manipulation example at the top of reference.md is particularly compelling.

Assignments in & functions

---

build/esbuild.civet
civet.dev/getting-started.md
integration/unplugin/README.md
integration/unplugin/examples/nextjs/tsconfig.json
integration/unplugin/examples/rollup/rollup.config.js
integration/unplugin/examples/rollup/tsconfig.json
integration/unplugin/examples/vite-lib/tsconfig.json
integration/unplugin/examples/vite-lib/vite.config.js
integration/unplugin/src/index.ts
integration/unplugin/tsup.config.ts
tsconfig.json

This PR:
- Changes the basic `js: boolean` option to a more configurable `ts: civet | esbuild | tsc | preserve` option instead. I feel like changing `js` to `ts` here makes more sense—we're configuring the transformation of _typescript_ source instead of js.
The esbuild and tsc option both require a peer dependency which is lazily loaded if the option is used.
- Renames `dts` to `emitDeclaration`. With js renamed to ts, `dts` might be confusing naming. `emitDeclaration` follows naming similar to Typescript's compiler options which have `emitDeclarationOnly`

Fix unplugin Typescript builds and update API

---

source/lib.civet
source/parser.hera
test/switch.civet

Fixes #821 (pattern matching on enum values) by allowing two new patterns:
* General pinned expressions: `^x.y`, `^x()`, and more generally `SingleLineExpressionWithIndentedApplicationForbidden` expressions in pins. I can't see why pins need to be identifiers; they can be any expression. I tried to make something that resembles one-liners, though not totally sure I got it perfect.
* `x.y` (a new `ActualMemberExpression` that has at least one member access) acts as the pinned expression `^x.y`. Currently no calls are allowed, which is maybe not ideal. Suggestions for generalization welcome.

Generalize pin expressions to allow x.y and ^x.y

---

source/parser.hera
test/switch.civet

Part of #335, as suggested in #831.
I figured `NotDedented` would be too confusing - then you'd have indentation for both patterns and body. But same indentation level seems very clear.

Allow multiple patterns over multiple lines with comma

---

civet.dev/reference.md
source/parser.hera
test/import.civet

[TypeScript 5.3](https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/) introduces support for [stage-3 import attributes](https://github.com/tc39/proposal-import-attributes) such as
```ts
import obj from "./something.json" with { type: "json" };
```
This is a replacement for `assert`, but I think for compatibility we should support both, at least for now.

Import attributes

---

integration/unplugin/src/index.ts

Fix Vite dev mode file watching (#773).
This was a challenge to get working. I confirmed that it works on Windows when modifying `main.civet` or the dependent `module.civet` in `integration/unplugin/examples/vite`.

handleHotUpdate to fix Vite HMR (watch in dev mode)

---

civet.dev/getting-started.md
integration/unplugin/README.md
integration/unplugin/examples/esbuild/src/main.civet
integration/unplugin/examples/vite/src/main.civet
integration/unplugin/examples/webpack/main.civet
integration/unplugin/src/index.ts

Most bundlers support implicit `.ts`/`.js`/etc. extensions. It's reasonable to expect that `.civet` will be implicit as well, so this PR adds it as default behavior.  @Mokshit06 suggested there be an option to disable this behavior, though, so you can force explicit extensions via `implicitExtension: false`.
I've tested this in esbuild, Vite, Rollup, and Webpack.

Support implicit .civet importing unless implicitExtension: false

---

source/lib.civet
source/parser.hera
test/function.civet

Fixes #862
Also fix some bugs in `generator` attributes (not actually tested here, but they were needed for a removed addition of "don't implicit return in async generators").

Omit return with Iterator/Generator<*, void> type

---

civet.dev/.vitepress/theme/custom.css

I unified light and dark mode a bit; #871 introduced custom color branding for dark mode, but not light mode. I also tweaked the primary and secondary colors to be consistently light or dark to improve contrast.
Dark:
Light:

Color tweaks to improve contrast

---

source/lib.civet
test/switch.civet

Fixes #870
We could do better, e.g. detecting unreachable code in a situation like this:
```coffee
switch x
when 1
if y > 0
return +1
else
return -1
```
We can continue to extend `isExit` if this is needed.

Omit obviously unreachable breaks from switch

---

source/lib.civet
source/parser.hera
test/property-access.civet

I noticed that `x?.-1` doesn't work when writing this code:
https://github.com/DanielXMoore/Civet/blob/5d990f690f778f9a39225f69647bc7a4992739c5/source/lib.civet#L3030

Support x?.-1 and other optional fancy accesses

---

civet.dev/reference.md
source/parser.hera
test/function-block-shorthand.civet

`not` requested in #854
I replaced a hard-coded negative lookaheads in a regex with an early attempt to match `AmpersandFunctionExpression`. I *think* this works, and should be more robust (and with caching, minimal overhead). As a bonus, we get some fun uses with `delete` and `await` illustrated in the tests and docs.

Allow arbitrary unary operators before ampersand function notation

---

integration/unplugin/examples/esbuild/esbuild.js
integration/unplugin/examples/esbuild/src/main.civet
integration/unplugin/src/index.ts

Implement @imm's [suggestions](https://github.com/DanielXMoore/Civet/issues/893) for fixing `emitDeclaration`:
* Remove `mkdir` preceding `this.emitFile`; `this.emitFile` should do this already (indeed, unplugin does it explicitly for esbuild)
* Switch `emit` call from `async` to synchronous.
* Add warning when using esbuild and no `outdir` option (as our example was doing), which prevents us (technically, unplugin) from emitting declarations because don't know where to put them.
Additionally, I realized there were bugs specific to Windows, which I was seeing but @imm wasn't (presumably not being on Windows):
* `fsMap` was getting the wrong code for slashed versions of filenames: the Civet source instead of the compiled TS! So I was getting error messages like `main.civet.jsx:1:5 - error …

Fix unplugin emitDeclaration and Windows behavior

---

civet.dev/reference.md
source/lib.civet
source/parser.hera
test/assignment.civet

Add `++=` assignment operator that acts like `concat`: multi-push if given an array, single push if not. Thanks to Beberka for pointing out the [isConcatSpreadable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/isConcatSpreadable) interface.
Here's [verification of the `concatAssign` typing](https://www.typescriptlang.org/play?#code/G4QwTgBAxg9gdlEAXAggZzQSwOZwFwQA8AQgDQQoQCmAHklXACZoQDeADgK5oAWBAFEh6Y0BFOQBGBYgEoIAXgB8EYDEyMAvhAA+EfsWp0GzCJzgBrODADucANoBdCAH42XXgKEix5AHT+pCFkFZVV1LQI4KmAqMBlFfgAbHlEKcjAU6TklCgU9ZLR0lOzlfn4MlhBKuABPGWdfOwBlGoBbCRhE3xEAYXhEJCb2MCoQRhAJRKonVySUiCqF2plfdx5fEHZ2RJq5wogKheq6iAECo6W61e4ecuLyApkAbgAoF9gEZHQsXH47AEZSAAmUgAZgc5AALDJ3v0vhgcHA-oCQeDyHZIaQAKwOGEfAbfRHI4FgiEQABEEjG5LxcNQCN+AJJaIgdkp1NxQA).
I imagine the …

++= concat assignment

---

civet.dev/reference.md
source/lib.civet
source/parser.hera
test/types/let-declaration.civet

As suggested by unless on Discord:
```js
let x?: T
---
let x: undefined | T
```
...by analogy to function parameters (`f(x?: T)`) and object properties (`{ x?: T }`).
Future work: similarly for function return types (`function f()?: T`).

Optional let declarations

---

civet.dev/reference.md
source/lib.civet
source/parser.hera
test/types/let-declaration.civet
test/types/type-declaration.civet

As suggested by @esthedebeste on Discord, this PR allows for conditional (ternary) types to be given by `if`/`else` and `unless`/`else` expressions, with the usual support for then conditions (with condition delimited by parentheses, or then clause indented, or explicit `then`).
The `else` clause is optional, with a default value of `never`, which I find to be very common when writing conditional types.
Also added support for indenting a type specification in `let`.

Conditional types via if/unless

---

civet.dev/reference.md
source/lib.civet
source/parser.hera
test/types/function.civet
test/types/let-declaration.civet
test/types/type-declaration.civet

Fixes #144 according to recent proposal in Discord. Do we like it? `T?` → `T | undefined` is nicely consistent with TypeScript's other optional types, but `T??` → `T | undefined | null` corresponds to our runtime `x?` operator. Maybe the closest we can get, though.
Also remove some excess parentheses (finally) in this type manipulation.
I notice that our rules are of the form `TypeUnary` but our AST node `type` strings are of the form `UnaryType`. Not sure whether we should fix this...

`T?` → `T | undefined`; `T??` → `T | undefined | null`

---

civet.dev/reference.md
source/lib.civet
source/parser.hera
test/types/class.civet
test/types/type-declaration.civet

As requested by @esthedebeste on Discord, this PR adds:
* `<` shorthand for `extends` in type conditions, matching existing support in classes
* Negated forms `not extends`, `!<`, and `not<` (though the last is a little ugly), via the trick of swapping the then/else clauses.
* Tighten some `__` and change a `NotDedented` from last PR to `IndentedFurther`. Otherwise we accidentally think there is extension going on in e.g. this test:
```ts
type T = undefined
<div />
```
Support for `unless ... not extends ...` is my first legit use of logical `xor`. 😸

Extends shorthand `<` and negated forms

---

source/parser.hera
test/binary-op.civet
test/function-block-shorthand.civet

Extension of #912 as mentioned in https://github.com/DanielXMoore/Civet/pull/912#discussion_r1441907448
Also fixes complex operators like `is in` which currently crash the compiler.
This completes Level 2 of #791.

`(foo)` for custom operators `foo`

---

lsp/source/lib/util.mts
lsp/source/server.mts

I ported over more of [TypeScript's completion code](https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/completions.ts), resulting in these minor improvements:
* Show source of imports in completion description
* Optional completions get `?` suffix (e.g. completing `x.y` when `x` has type `{ y?: ... }`
* Deprecated completions get some kind of deprecation flag
* Respect `filterText`, `sortText`, `isRecommended`, `replacementSpan` (not sure if these are used though)
My original goal was #922, but I got kind of lost how to create a custom completion command to execute a follow-up query (`completionEntryDetails`) and get the additional edits to do. Do you know how to create a command …

LSP pass on more completion info

---

integration/unplugin/src/index.ts

When transpiling to JavaScript via `"tsc"` mode, we currently set the extension to `.jsx`, which makes sense, except that it breaks type checking.
Before this PR, we got messages like this:
```
vite v4.5.1 building for production...
✓ 2 modules transformed.
src/main.civet.jsx:3:15 - error TS8010: Type annotations can only be used in TypeScript files.
3 function f(b: number) {
~~~~~~
src/module.civet.jsx:1:15 - error TS8010: Type annotations can only be used in TypeScript files.
1 export var a: string = "a"
~~~~~~
```
After, we get messages like this:
```
vite v4.5.1 building for production...
✓ 2 modules transformed.
src/main.civet.tsx:7:15 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.
7 console.log(f(a))
~
```
```

Use .tsx extension for TypeScript type checking

---

integration/unplugin/README.md
integration/unplugin/src/index.ts

Failing on TypeScript errors is important for CI testing in particular.
With this PR, `typecheck: true` aborts the build with an error code whenever TypeScript generates "errors", which seems like a good default.
There's also a more (too?) complicated interface for specifying which diagnostic messages should abort the build (similar in spirit to `-Werror` in C compilers). Let me know what you think.

Fail on TypeScript errors, or specified types

---

source/parser.hera
test/binary-op.civet
test/types/function.civet

Fixes #939
This actually cleaned up the grammar some; before, we had to check for `TypeArguments` in every call scenario. Now it's part of `CallExpression`.
There's some fun ambiguity with tight comparison chains. But note that `x<y>(z)` was already treated like a function call, not a comparison chain. I preserved the working of `x<y>z` and `x<y>0` but there might be other more subtle cases that break...

Support TS instantiation expressions

---

civet.dev/reference.md
source/parser.hera
test/types/shorthand-const.civet
test/types/type-declaration.civet

Mainly this adds `T."x"` and related access to types, paralleling our existing support for this notation in expressions.
For consideration, I also added `T::x` shorthand for `T["x"]` when `coffeePrototype` is enabled. I think this intuitive for those who have this flag on (think of `T` as a class), though of course there isn't an actual notion of prototype here. I could also remove this if you think it's not ideal. (It still leaves our options for `::` open when `coffeePrototype` is off. I also don't think this conflicts with any of our current intentions for `::`.)

Shorthand for type indexed access

---

civet.dev/reference.md
source/parser.hera
test/binary-op.civet
test/compat/coffee-of.civet

On Discord, we've had a request for a `!in` operator as shorthand for `not in`.
I've added `!op` support wherever we had support for `not op` (assuming I didn't miss any).

`!op` shorthand for `not op`

---

source/lib.civet
source/parser.hera
test/function-block-shorthand.civet

#948 recursively processed all commas, which leads to some weird behavior:
```js
(+) f(x, y), z
↓↓↓
f(x) + y + z
```
This PR bites the bullet and cleans up all forms of `Arguments` so that you get one array with all the arguments and commas at the top level (similar to processing we do with top-level statements, IIRC). This lets us process commas without recursion.
Currently, whitespace is combined with some arguments and commas, so that the array really alternates between arguments and commas. Alternatively, we could allow whitespace at the top level of the array too. I guess this can be decided later.
I also changed the behavior of `(+)(1)` to expand to just `(1)`. This seems beneficial when you're working with complex nested prefix formulas, and you remove one item, expecting …

Cleanup Call arguments AST, fix (+) processing

---

source/cli.civet
source/config.civet
tsconfig.json

I ported the CLI code to more modern Civet, and added types so that TypeScript is happy with it. I tried testing all the options (but it wouldn't hurt to double-check – in particular, I've never used a config file, so I didn't test that).
There's still a bit of a mix of `require` and `import`, which works fine in practice. Currently, dynamic import of a JSON file generates a warning, which I'd like to avoid.
(This is in preparation for adding a `--typecheck` flag.)

Port CLI to more modern Civet

---

source/lib.civet
source/parser.hera
test/function-block-shorthand.civet
test/pipe.civet

* `&.foo |> bar` changed to mean `$ => bar($.foo)` instead of current behavior of `bar($ => $.foo)`. Motivations:
* `& |> bar` already means `$ => bar($)`, so this seems far more symmetric
* `-> foo |> bar` already puts `bar(foo)` inside function body (see #949 for mismatch with `=>`, but I think that's a bug)
* Generally, probably more useful to work with values than functions in a pipeline, until we introduce a composition operator
* Examples below
* `&: T` prefix allows you specify a type for `$` argument.  For example:
* `&: number` is an identity only for `number`s
* `&: number + 1` is a more explicit increment
* `&: number |> Math.floor` is where things get more interesting (TS sadly doesn't usually infer in cases like this)
* Note: This required changing precedence as above, …

Typed ampersand function improvements

---

source/parser.hera
test/assignment.civet
test/helper.civet

I made a small mistake when originally writing `concatAssign`: the value of `Array.prototype[Symbol.isConcatSpreadable]` is `undefined`, not `true`. Setting the value to `false` does make it no longer concat-spreadable, but if it's `undefined` we need to *also* check if it's an Array.
[Relevant section of the ECMAScript specification](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-isconcatspreadable):
> 1. If *O* [is not an Object](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-object-type), return **false**.
> 2. Let *spreadable* be ? [Get](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-get-o-p)(*O*, [@@isConcatSpreadable](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-well-known-symbols)).
> 3. If …

Fix concatAssign for arrays

---

source/parser.hera
test/types/export.civet
test/types/import.civet

This is necessary for working with TypeScript + CommonJS.  See https://www.typescriptlang.org/docs/handbook/modules/reference.html#export--and-import--require
Fixes #971 in a certain sense, in particular https://github.com/DanielXMoore/Civet/issues/971#issuecomment-1936853962

TypeScript's `import ... = require(...)` and `export = ...`

---

source/cli.civet
source/config.civet
source/main.civet
source/parser.hera
test/import.civet
types/types.d.ts

* Add `"civet rewriteCivetImports=.ext"` compiler option to rewrite `.civet` imports to `.ext`. This is useful when manually compiling everything.
* Set default CLI behavior (with `civet -c`) to rewrite to the extension for output files. (As specified by `-o`, or defaulting to `.civet.tsx`/`.civet.jsx`.) This should benefit those not using fancier build systems; it makes built code actually runnable.
* Add `--civet` command-line option to specify compiler flags, which e.g. makes it possible to override this extension rewriting behavior. (Also a lightweight alternative to config files.) This was fun because I wrote it by calling a small rule in the Hera compiler!
* Cleanup: I finally understand how config files are supposed to work: flags like `coffeeCompat` are supposed to go in a …

CLI import rewriting, --civet option, cleanup

---

source/parser.hera
test/object.civet

Fixes #968 as well as related [weird behaviors](https://civet.dev/playground?code=ZnVuYyBmb286IDEKYmFyOiAy):
```coffee
func foo: 1
bar: 2
↓↓↓
func({ foo: 1, bar: 2 });
```
The issue is that the following parses as an `InlineObjectLiteral` thus `ObjectLiteral` thus `PrimaryExpression`:
```coffee
foo: 1
bar: 2
```
---
This PR splits **implicit object literals** from two to three notions:
* `NestedImplicitObjectLiteral` (AS BEFORE): starts with an indent, arbitrary spacing
* `ImplicitObjectLiteral` (NEW): indentation already consumed, but can have multiple lines at same indentation level — assumed to be used only at beginning of lines
* `InlineObjectLiteral` (MODIFIED): can appear anywhere in an expression, so generally spans only one line, except that explicit trailing commas let you go to …

Nested vs. implicit vs. inline object literals

---

source/lib.civet
test/object.civet

We discovered that Civet currently can't be built by the latest version of Civet. This test is a MWE extracted from `insertTrimmingSpace`, plus a fix.

Fix spread bug extracted from lib.civet

---

civet.dev/reference.md
source/parser.hera
test/export.civet
test/types/export.civet

Fixes #965
Now all declarations (except `using`, which didn't seem particularly helpful...?) can be `export default`.
I also cleaned up / added some AST nodes to have a consistent `id` if there was a clear single id (e.g. class, interface, enum).

export default shorthand

---

source/parser.hera
test/types/enum.civet

Fixes #978
I made the `Nested` part of `NestedEnumProperty` optional, allowing it to be on the same line as the previous enum property. I also had to add `_?` or else it didn't allow whitespace after the commas.
I tried to make sure this doesn't inadvertently allow anything it shouldn't, like
```civet
enum E
A B // look ma, no comma!
```
still causes a syntax error. But there may have been something I forgot to check.

Allow enums on one line

---

civet.dev/public/playground.worker.js
test/switch.civet

* `"Error"` nodes in TS generation now display the error(s). (Not very pretty, but functional.) Fixes #979
* JavaScript-specific `"Error"` nodes don't crash until you click "Run"; then they log the specific error messages to our virtual console.

Support "Error" nodes in Playground

---

lsp/package.json
lsp/source/lib/typescript-service.mts
lsp/source/server.mts
lsp/yarn.lock

The LSP now reports parse errors. Unfortunately they don't have location information yet so they will only appear at the top of the file. Eventually we can add location info to error nodes, apply the sourcemapping, update the LSP to check for this location, and then they will appear in the proper place.

Report error nodes in LSP

---

source/parser.hera
test/pipe.civet

Makes `=>` and `->` behave the same with respect to pipes: pipelines go inside the function.
Fixes #949

Consistent arrow vs. pipe precedence

---

source/lib.civet
source/parser.hera
test/function.civet
test/types/function.civet

Fixes #952
Currently, we preserve one-line arrow functions with an expression body, as in `(x) => x+1`, to avoid wrapping with braces and then adding an implicit `return`. But this breaks our promise that `:void` return values do not implicitly return. So this PR wraps those expressions in braces. It's a little weird that `:void => null` ends up returning `undefined` instead of `null`, but it matches the behavior with multi-line arrows.
Note that this behavior only enables when `implicitReturns` is on. If you turn it off, fat arrows act as usual (both implicitly returning for single line, and not implicitly returning for multiline blocks, similar to JS).

Avoid implicit returns from fat arrows

---

source/parser.hera
test/examples.civet
test/export.civet
test/function.civet
test/jsx/indent.civet

Removing our transform of const declarations to function to keep them consistent with const semantics.
If people really want function semantics they can use the `function` declaration.

Fix #947 - Better const function semantics

---

source/parser.hera
test/compat/coffee-for-loops.civet
test/for.civet

Allow for checking arbitrary strings, and handle arbitrary `{}.constructor` type.
[TS playground example](https://www.typescriptlang.org/play?#code/G4QwTgBAFiDOAKYD2AHAXBAFAHgCoD5MkAjAKwFMBjAFw1wBoIVl0JFVyxqBPAaXO4BKCAF58EYkiQAbciAB2wkVgDeAXwB0lJPNjUwAVxpJIcCAqEaYsAPIB3eQG4AUM4AmVaeHIRQkEqQYKgAeGPIGALbEnIzcAPxhkdFgaq7autTmotBw7ChEZIwA5MFFgs4QlRAA9NUAenHO6XoS2dZ5BaTF3GUVVbUNTTotlG25LJ3FAF69VTX1cUA)
Fixes #1010; see [TS playground](https://www.typescriptlang.org/play?target=99#code/G4QwTgBAFiDOAKYD2AHAXBAFAHgCoD5MkAjAKwFMBjAFw1wBoIVl0JFVyxqBPAaXO4BKCAF58EYkiQAbciAB2wkVgDeAXwB0lJPNjUwAVxpJIcCAqEaYsAPIB3eQG4AUM8rS4sCADEpAERBqcghyAA8g+QATLwCgiBVnCAgAMylicFEIACIACQBLCABZJABbLJc1V21daggSChpM+XI7H39A8kxBF2dUyExqvQgAawEIPPk6sipqYQSkvOSsAEJrdhQiaZpGUaFhauoJg3IXJMGZcg1pJABzTF3u50qgA).

Fix hasProp type

---

civet.dev/reference.md
source/lib.civet
source/parser.hera
test/object.civet

Fixes #1012 by allowing unary prefix and postfix notation in braced literals shorthand properties in most cases. This allows for negation, type casting, and await.
Also add missing support for positive integers as property names.

Unary prefix and postfix in braced literal shorthand

---

source/parser.hera
test/class.civet

Fixes #1013
However, fixing this requires:
* There are some ambiguous situations like `class X<Y<Z>`; it could mean `class X extends Y<Z>` or `class X<Y extends Z>`. But I guess you're asking for trouble in this situation. Currently it means the latter because greedy.
* Forbidding space between a type and its parameters: `T<X>` is valid, but `T <X>` is invalid. This is contrary to TypeScript, but in line with our usual rules about whitespace I think? Potentially controversial, though TS documentation seems to consistently have no space.
* Alternatively, we could still allow spaces, but then `class X < Y<Z>` does not parse how we'd expect.

Support extends shorthand in type parameters

---

source/parser.hera
test/types/type-declaration.civet

Fixes #176 
Fairly straightforwards, adds `X ::= Y` as shorthand for `type X = Y`. For the tests I just picked a few existing tests using the `type` keyword and copied them but with `::=` instead.

Add type assignment shorthand

---

civet.dev/getting-started.md
integration/unplugin/src/index.ts
source/cli.civet
types/types.d.ts

Following up on https://github.com/DanielXMoore/Civet/issues/61#issuecomment-1921882118, I realized that we don't need to duplicate the functionality of the unplugin: we can call the unplugin directly from the CLI!  (with a small amount of unplugin emulation)
* New `--typecheck` option runs the TypeScript compiler on all specified source files and outputs all diagnostics.
* No sourcemapping to the original files; this is a missing feature in the unplugin. Added a TODO.
* You need to specify all `.civet` files in one command line to check everything. So something like `civet --typecheck src/**/*.civet`.
* Should `-t` be an alias for this? It seems important, but we might also eventually have a `--ts` feature to mirror the unplugin `ts` option, so maybe better to save it.
* New …

Typechecking CLI

---

source/parser.hera
test/object.civet
test/types/non-null-assertion.civet

* Remove `NonNullAssertion` from `OptionalShorthand`, as it was already in `MemberExpressionRest` and thus `CallExpressionRest`.
* Fix some lost comments.
* Prevent `foo()!!.bar` from parsing like a method definition.

Cleanup non-null assertion handling

---

integration/unplugin/src/index.ts

The unplugin and CLI `--typecheck` use `.tsx` extension for type checking, because Civet's output is generally in TSX syntax. But TypeScript issues an error in this case when importing and the user didn't set a `compilerOptions.jsx` option in `tsconfig.json`:
```
test.civet.tsx:2:17 - error TS6142: Module './yes.civet' was resolved to 'C:/Users/edemaine/Projects/Civet/yes.civet.tsx', but '--jsx' is not set.
2 import yes from './yes.civet'
```
This PR forces a `jsx` setting in tsconfig if the user didn't specify one, removing this stray error.

Automatic TS jsx setting in unplugin and CLI

---

source/parser/function.civet
source/parser/pattern-matching.civet
test/for.civet

Fixes #1040
I actually can't remember why we check for this in two different places. Perhaps one of them can be removed, and this code can be simplified? But not remembering why they're actually necessary, I left them both in and just made them interact better.

Avoid double semicolon in then clause

---

source/parser/string.civet
test/strings.civet

I converted `\r\n|\n|\r` all to `\n`. It seems like the right thing to do.

Fix #1047 - Properly escape newlines in multi-line strings

---

source/parser/pattern-matching.civet
test/if.civet

If the condition to an `if` or `while` statement is just an assignment and nothing else, this trips ESLint's `no-cond-assign` rule. While this should continue to trigger for Civet code like `if x = y`, `if x := y` feels intentional enough that it shouldn't trigger that error. ESLint allows you to suppress the error by doubling up the parens, so this PR doubles the parens in these cases.
The typings -- or, more frequently, lack thereof -- inside the compiler made this a little difficult to navigate at first, but I got there in the end.

Suppress ESLint `no-cond-assign` with `if const` etc

---

integration/unplugin/src/index.ts

Something about the absolute paths in #1046 broke Vite in dev mode. The problem seems to be that we're now triggering the [dep optimization phase](https://vitejs.dev/config/dep-optimization-options.html). I don't know exactly how it works, but I observe that it uses esbuild, and lo', we have an esbuild plugin. Installing that automatically in Vite config seems to fix the problem.

Add esbuild unplugin to Vite's optimizeDeps

---

integration/unplugin/src/index.ts

It seems that `emitDeclaration` isn't emitting `.d.ts` files, and hasn't been for some time. (I didn't track down exactly which version of Civet broke this, but it's at least 10 versions ago.) I guess we could really use unplugin tests...
Anyway, TypeScript seems to respond to [an `@internal` interface](https://github.com/microsoft/TypeScript/blob/1c0fd3122345bc342337089beb0b905d0ec0ddba/src/compiler/types.ts#L4727) to `forceDtsEmit`. Adding this fixes `.d.ts` emit.
This revealed a bug in esbuild, where unplugin creates the output directory but doesn't create the subdirectories in the `.d.ts` filenames. E.g., `src/index.civet` generates `dist/src/index.civet`, and unplugin makes the directory `dist` but not `dist/src`. I'll upstream this to unplugin, but meanwhile have a workaround here.

Force emitting dts files in unplugin

---

civet.dev/.vitepress/components/PlaygroundFull.vue
civet.dev/public/playground.worker.js
source/main.civet
source/parser.hera

* Fix preamble detection to not e.g. eat `"x"` in `"x" |> console.log`
* Fix detection of coffeeCompat mode
* Fix coffeeCompat `do` (needed to be wrapped in parens)
* Catch errors during promise and output them
* Format JS parse errors for output (escape \n)

Fix Playground around top-level await

---

civet.dev/cheatsheet.md
civet.dev/reference.md
source/parser.hera
test/length-shorthand.civet

This add `x.#` as a shorthand for `x.length`. It doesn't support without the `.` because our current implementation of private identifiers doesn't support that yet either. We can add it for both at some point in the future.
See #909

Add # length shorthand #909

---

source/parser.hera
source/parser/lib.civet
test/property-access.civet

Title. A weird side effect is that `x@y()` is now equivalent to `x@y`.
Closes #954

Allow arguments to property bind

---

source/parser.hera
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/examples.civet
test/function.civet
test/if.civet
test/switch.civet
test/try.civet

This is about 50% of #202 
Most of the work was refactoring `pushRef` to be more general `assignResults` to handle pushing to a collection or assigning to a ref.
Things remaining:
- iteration statement expressions
- if statement expression
- single assignment expression rhs
Much later:
- arbitrarily nested expressions (need to unwrap and maintain refs to keep execution order the same)
- arbitrarily chained assignments (ditto)

#202 - Don't wrap StatementExpressions in IIFE in declaration

---

source/parser.hera
source/parser/block.civet
source/parser/declaration.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/pattern-matching.civet
source/parser/types.civet
source/parser/util.civet
test/binary-op.civet
test/compat/examples.civet
test/do.civet
test/examples.civet
test/for.civet
test/function.civet
test/if.civet
test/jsx/indent.civet
test/switch.civet
test/try.civet
test/while.civet

This is probably good enough to merge in.
- Removed IfExpression as separate part of grammar
- Now get hoisted as StatementExpressions or wrapped in IIFEs similar to IterationExpression
- Made DeclarationConditions work with StatementExpressions
- Added more types
- Moved skipImplicitArguments check from parser to .civet file
- Moved declaration logic to parser/declaration.civet
- Handle simple assignments expressions
To add later:
- Extend wrap IIFE to handle return from outer function, yield.
Related: #380, #202

Statement expressions

---

source/parser.hera
source/parser/lib.civet
source/parser/types.civet
test/assignment.civet
test/update-expression.civet

Also added support for `x?.y?.z++`

Fix #54 - Optional chain in assignment lhs

---

README.md
civet.dev/getting-started.md
civet.dev/integrations.md
package.json
register.js
source/cli.civet
source/esm.civet
yarn.lock

* `@danielx/civet/register` now calls Node 20.6.0+'s `module.register` method to register ESM, in addition to CJS registration.
* New recommended method for ESM and CJS registration (for Node 20.6.0+):
`node --import @danielx/civet/register`
(avoids new warning ``ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()` ``)
* Removed duplicate CJS registration code from ESM loader; should use `@danielx/civet/register` for this
* CLI runs `@danielx/civet/register` even in REPL mode, so you can `require` or `import` Civet files interactively (one catch: I couldn't get `import` to work on Node <20.6.0)
* CLI provides `importModuleDynamically` to enable dynamic `import()`
* CLI supports top-level `await` (like Node CLI), based on previous code written …

Modern NodeJS register and CLI require/import fixes

---

civet.dev/reference.md
source/parser.hera
source/parser/declaration.civet
source/parser/function.civet
source/parser/lib.civet
test/function.civet
test/import.civet

Fixes #727:
* `import { getX } from library` → `const { getX } = await import('library')` if not at the top level
* `import lib, {getX} from library` → `const lib = await import('library'), {getX} = lib` if not at the top level
* `stuff := import { getX, getY } from library` → `const stuff = (await import('library')).{getX, getY}`
This complements existing functionality of `stuff := import 'library'` → `stuff := import('library')`. Note that `stuff := import library` has a different meaning than above (use the variable `library` instead of the string).
~~I haven't implemented `assert`/`with` yet. I probably should...~~ Import assertions via `assert`/`with` should work now.
Also fixes a bug where `{x: y} := obj` got implicitly returned as `{x}`, but it should be `{y}` (!).

Dynamic import declarations and expressions

---

civet.dev/public/playground.worker.js
source/cli.civet
source/generate.civet
source/main.civet
source/parser.hera
source/parser/block.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/util.civet
test/do.civet
types/types.d.ts

Previously, top-level `await` in the CLI or Playground caused code to get wrapped in a wrapper that hid all declared variables. This PR hoists those declarations into top-level `var`s so that they can get accessed in future operations. (It does lose the `const`/`let`ness of the variables, but this seems a far better loss, and `const` is mostly annoying in a REPL environment.)
As a bonus, top-level `import` declarations also get wrapped to use the new dynamic import declarations, so they appear to just work as usual. You can now `fs from fs` in the CLI and then access `fs.readFileSync` in the next operation. Take that, Node REPL! (`import fs from 'fs'` fails in Node, with an error message to suggest instead writing `const { default: fs } = await import("fs");`)
Along the way, I did some …

Hoist declarations out of async wrapper and other cleanup

---

civet.dev/reference.md
source/parser.hera
test/class.civet
test/length-shorthand.civet

Fixes #1125, and part of #909 
* `@#` → `this.length`
* `array#` → `array.length`
* `object#field` → `object.#field`

Optional dot before #

---

source/parser.hera
test/array.civet

Fixes #1132
The comment says `NOTE: Allow empty exp spread for destructuring` but I think this was before there was pattern matching, and a separate set of rules for left-hand sides where `...` is still allowed. For example, `function f([a, ..., b])` is still allowed, as is `[a, ..., b] = c`. The latter has a bug, which I'll raise separately (#1139).
Let me know if you see a way that this could be relevant. It's at least not breaking any tests.

Prevent `...` as array element in right-hand side

---

source/parser/function.civet
test/examples.civet
test/switch.civet

Missing insert return after pattern matching statement

---

civet.dev/reference.md
source/parser.hera
source/parser/declaration.civet
source/parser/types.civet
test/if.civet
test/while.civet

New functionality to check for nonnull instead of truthy assignment conditions:
```js
if number? := next()
↓↓↓
let ref;if (ref = next(), ref != number) {
const number = ref
```
Note that `number?: T :=` still means `const number: T | undefined =`. This is assigning a new meaning to the special case where `?` appears but no type annotation appears.
`if [x, y]? := foo` also works, but isn't really helpful, because the array test means that truthy and nonnull are the same. Similarly for `if {x, y}? := foo`. But they do parse fine and replace a truthy check with a nonnull check.
Fixes #1131

Nonnull checks in assignment conditions

---

source/parser.hera
test/binary-op.civet
test/unary-expression.civet

Fixes #1127 as described in comment there.
`Assignment` and `ArrowFunction` are both part of `AssignmentExpressionTail` so I kept the "assignment" naming scheme.
I also noticed that both `RHS` and `UnaryBody` both derive to `ParenthesizedAssignment`, but this seems to be redundant, unless we wanted unary operators to be pulled into the assignment, but that's not currently possible (e.g. `+x = 5` → `+(x = 5)` even now). So I removed the `RHS` derivation.

Late arrow functions like late assignments

---

civet.dev/reference.md
source/parser/for.civet
test/for.civet

Input:
```coffee
for i of [1..10]
(i)
```
Previous output:
```js
for (let i1 = 1; i1 <= 10; ++i1) {
const i; = i1;
(i)
}
```
Output with this PR:
```js
for (let i1 = 1; i1 <= 10; ++i1) {
const i = i1;
(i)
}
```

Fix ASI bug caused by unstructured blockPrefix

---

source/parser.hera
test/switch.civet

There may be a better way to handle the unification of unary numeric literals but this seems good for now.

Fix #1043 - Add missing unary numeric and undefined pin patterns in switch

---

source/parser.hera
source/parser/lib.civet
source/parser/traversal.civet
source/parser/types.civet
source/parser/util.civet
test/partial-placeholder.civet

`.` placeholder for partial function application.
Works for the common cases but `...` is a bit strange so I'll save that for a future iteration.

Partial application placeholders

---

README.md
civet.dev/getting-started.md
civet.dev/integrations.md
integration/unplugin/README.md
integration/unplugin/examples/astro/astro.config.mjs
integration/unplugin/src/astro.ts
integration/unplugin/tsup.config.ts
package.json

Today I was working on an Astro project with Civet integration via our Vite plugin and old instructions (which generally work great!), and I got confused about Astro's notion of **integration** vs. **Vite plugin**. Specifically, I was trying to add Astro's Solid *integration*, but I accidentally added it to the *Vite plugin* array where I had already added Civet. I think adding a manual Vite plugin isn't very "Astro-ey", so I added a simple Astro integration for Civet. This may also unlock deeper features we can add to Astro specifically in the future. (I dream of `.astro` files one day allowing for Civet code.)

Astro integration based on Vite plugin

---

build/build.sh
integration/unplugin/src/constants.ts
integration/unplugin/src/index.ts

It turns out the default behavior of our Vite unplugin disables all of Vite's default resolve extensions, including e.g. `.jsx` which was breaking a project I have that uses external JSX libraries (written in Solid, so distributes `.jsx` files).

Preserve Vite's default extensions

---

source/parser.hera
source/parser/function.civet
source/parser/pattern-matching.civet
source/parser/types.civet
source/parser/util.civet
test/function.civet
test/switch.civet

Fixes #1161 by extending `isExit` and using it to omit implicit `return`/`push`.
* Basic infinite loop detection in `isExit`: `loop`/`while(true)`/`do..while(true)` without contained `break`.
* Currently do not distinguish between `break` of this loop vs. other loops
* Do correctly ignore `break` inside nested functions
* Extend `isExit` to handle `if/else` statements.
* There might be other work to do here, e.g. `do` statements.
* Avoid implicit `return` of last statement when it is `isExit`.
We can continue to refine `isExit` to improve this mechanism.
One case I wasn't sure of: currently a block is considered `isExit` if its last statement is. So e.g. a block with a `break` in the middle but not end of the block is considered non-exiting. I don't *think* this case matters much, because …

Infinite loop detection and no return

---

source/parser/pipe.civet
source/parser/util.civet
test/pipe.civet

Allow for pipe assignment with index properties like:
```
body.children[1] |>= .filter [, e] => !exps.includes e
body.children.-1 |>= .filter [, e] => !exps.includes e
```

Pipe assignment to index

---

source/parser.hera
source/parser/block.civet
test/class.civet
test/jsx/solid.civet

* Run ASI algorithm in class bodies; previously they were `type: "ClassBody"` so completely ignored. Now they're `type: "BlockStatement"` with `subtype: "ClassBody"` (in case we need to know someday).
* Recurse into first non-null child/array element instead of just first, and add a string base case. This seems like a better-behaved recursion. Probably some cases of the `switch` could now be eliminated, but I didn't try.
Fixes #1169

Improve ASI algorithm

---

civet.dev/reference.md
source/parser.hera
test/function-block-shorthand.civet

A natural extension of Haskell-style operator sections to assignment operators. This seems quite useful, as in e.g. `new Promise (resolve =)`.

Assignment operator sections

---

source/parser/lib.civet
test/function-block-shorthand.civet

Fixes #1173 by removing stray `type: "Call"` node in AST (which should be eliminated during expansion of applied `(or)`).

Fix & in applied (operator)

---

civet.dev/reference.md
source/parser.hera
source/parser/declaration.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/pipe.civet
source/parser/types.civet
test/function-block-shorthand.civet
test/yield.civet

* Limit `&` lifting to stop at `return` and `yield`, as it's not useful to `return` or `yield` inside a generated wrapper.
* Add support for `yield`ing an indented expression, like we already do with `return`.
* AST node for `"YieldExpression"`
As this PR makes clear: Some AST nodes use property `exp` (e.g. `"AssignmentExpression"`, `"Initializer"`) while some use property `expression` (e.g. `"ReturnStatement"` and new `"YieldExpression"`). Could we unify on one or the other? Preference which?

Limit & to return/yield; support indented yield argument

---

source/parser/auto-dec.civet
source/parser/block.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/compat/coffee-prototype.civet
test/function-block-shorthand.civet
test/function.civet
test/types/function.civet

Fixes #1176 
I unified a place where we were manually bracing a block into a call to `braceBlock`. But they differed in the closing brace: the new use ended with ` }` while other instances ended with `}`. I'm somewhat tempted to switch to the spaced version throughout, which would lead to changes like this:
```diff
switch x
{a: y, b: y}
y
↓↓↓
if(typeof x === 'object' && x != null && 'a' in x && 'b' in x) {
const {a: y1, b: y2} = x;
const y = [y1, y2];
-    y }
+    y}
```
But this would involve changing ~70 tests. Do you think it's worth it?

Brace block improvements, including `&` statements

---

source/config.civet
test/infra/config.civet

Performance: `fs.opendir` stats every file in a directory, I believe. We only need to stat names that match `.config` or `civetconfig.*`. I've restructured to use `fs.readdir` which just gets the listing, and only stat files we care about. On some file systems, this can be orders of magnitudes faster.
Also, `stat` can throw, and we can't really catch that from `fs.opendir`. MIT's UNIX machines use AFS (Andrew File System) which is ... particular. The parent directory of my home directory has 500 subdirectories, and some of them fail to stat. In particular, *every time I run the Civet CLI* (without `--no-config`) I get this error:
```
node:internal/process/promises:288
triggerUncaughtException(err, true /* fromPromise */);
^
[Error: ENODEV: no such device, lstat 'xxx'] {
errno: -19,
code: …
```

Faster and robust config searching via `readdir` instead of `opendir`

---

source/parser/comptime.civet
test/comptime.civet

Fixes #1182 
I just realized while typing this that my first regex doesn't handle default values in arguments to arrow functions, and since the default value can be an IIFE, I would basically have to fully parse JS in order to handle that. That's not a task that regex is sufficient for, so I'm marking this as a draft pending advice on what to do in that scenario.

Insert "function" into ES6 methods

---

source/parser.hera
test/comptime.civet
test/do.civet
test/for.civet
test/if.civet
test/loop.civet
test/while.civet

I propose allowing for empty blocks in most settings. We already support them in `function`s, and `case`/`when`/pattern matching. This PR adds them to all loops, if/else, and for symmetry, do blocks and comptime.
CoffeeScript supports this in `if/else` expressions that have both `if` and `else`: [both empty](https://coffeescript.org/#try:if%20x%0Aelse), [empty if](https://coffeescript.org/#try:if%20x%0Aelse%0A%20%20y). I think this hints at why it is useful:
* Suppose you have code with an if/else construct, and you comment out the then or else block. Currently, that makes a parse error. Commenting out the else block is not too bad: just comment out the `else` keyword too. But commenting out the if block is hard: you need to comment out the `if` line, the `else` keyword, *and dedent the …

Allow empty body in loops, if/else, do, comptime

---

source/parser/comptime.civet
test/comptime.civet

Typed arrays were briefly discussed on the discord last night. While I didn't mention well-known symbols, they seem useful and were also pretty straightforward to implement.
I believe symbol-keyed properties in objects are still not serialized, but that can be a separate issue.

Serialize typed arrays and well-known symbols

---

source/parser/comptime.civet
test/comptime.civet

Fixes #1189 
Technically, this doesn't detect the case where a class's prototype is modified after initialization, i.e:
```civet
C := comptime do
class C {}
C.prototype.toString = -> 'C'
C
```
but I'm not 100% sure this is possible in the general case. In any case, the current behavior of creating `function class C {}` is definitely wrong.

Comptime classes and generators

---

package.json
source/parser/comptime.civet
test/comptime.civet

Serialize function properties for `comptime` using `Object.defineProperties`. We could afford to do this for properties that aren't `{ +configurable, +writable, +enumerable }` on `Object`s too, but that isn't covered in this PR. This PR also fixes a couple things with circular reference detection, now that functions can be circular.

Comptime function properties

---

source/parser/comptime.civet
test/comptime.civet

Even though it's not technically part of JS itself, `URL` is a global class in both browsers and Node.

Comptime URLs

---

civet.dev/reference.md
source/parser.hera
source/parser/block.civet
source/parser/declaration.civet
source/parser/for.civet
source/parser/function.civet
source/parser/helper.civet
source/parser/lib.civet
source/parser/op.civet
source/parser/pattern-matching.civet
source/parser/pipe.civet
source/parser/ref.civet
source/parser/types.civet
source/parser/util.civet
test/binary-op.civet

Fixes #391
Most of this PR is code cleanup:
* `getPatternConditions` no longer requires a third `conditions` argument; it starts as an empty array that gets returned
* This lets the condition combination code get simplified a lot (also thanks to the recent `.` feature)
* New `source/parser/ref.civet` to house ref helpers
* New `makeRefAssignment` to ease creation of `hoistDec` and `refAssignment`
* New `maybeRefAssignment` = `maybeRef` + `makeRefAssignment`
* New `flatJoin` to ease combining expressions with ` && ` or ` || `
* More types (but still incomplete)

"is like" pattern matching operator

---

source/parser.hera
test/compat/coffee-prototype.civet

Fixes #1191
Turn out this notation is [supported by CoffeeScript](https://coffeescript.org/#try:x%20%3D%205%0Ay%20%3D%20x%3F%3A%3Ay) (though implemented without `?.`, seems to work just the same), so it's also good for compatibility.

Optional ?:: for coffeePrototype

---

source/parser/block.civet
source/parser/declaration.civet
source/parser/pattern-matching.civet
source/parser/types.civet
test/if.civet
test/switch.civet
test/while.civet

Generally share more code between pattern matching and declaration conditions to fix the following:
* Fix declaration conditions with literals (fix #1147)
* Fix duplicate bindings in declaration conditions
* Bonus: Avoid refs in simple declaration conditions
* Added: Fix empty arrays in object pattern matching (fix #1201)

Pattern matching fixes

---

source/generate.civet
source/parser/pattern-matching.civet
test/switch.civet

Fix the issue mentioned here: https://github.com/DanielXMoore/Civet/pull/1200#discussion_r1583864309
This turned out to be tricky to figure out, as it had to do with the generator!  ArrayBindingPattern nodes have a `length` field which was zero in this case. We could instead remove `length` fields from AST node objects, but it seems like a useful field name (I'd rather have it *defined* for ObjectBindingPattern too so that code could be more symmetric), and maybe used a fair amount around array patterns, so changing the generator seemed better.  Note that empty arrays are still also removed, using the code down below.

Fix handling of empty arrays and objects in patterns

---

civet.dev/reference.md
source/parser.hera
test/binary-op.civet

Add support for `(is like ...)` sections. It's a special binary operator so this needs to be explicit. [I don't think `(... is like)` or `(is like)` sections can make sense, because the right-hand side needs to be parsed as a pattern.]
I forgot that I previously added `is not like`, this PR documents and tests  that as well.

(is like ...) section, document "is not like"

---

source/main.civet
test/function.civet

Fixes #1206
I verified that the second added test fails without this change. Not totally sure this is the right place for the `inlineMap` test, but `yield` in fat arrow is something we didn't already check for that generates an Error node, so it works.

Detect Error nodes in inlineMap mode

---

package.json
source/parser/function.civet
source/parser/lib.civet
source/parser/op.civet
source/parser/util.civet
yarn.lock

I think these show some nice examples of `is like`.
On the other hand, I currently can't get VSCode to parse these files with these changes (because it's refusing to use updated Civet in `node_modules`), so can't get TS feedback, so we might want to fix that first...

Use `is like` in some cases

---

lsp/source/lib/typescript-service.mts

This warning might help a future me when it seems like my local Civet isn't running. 🙂 
Also double checked that the LSP should work with the new async API (as well as the old API, as `await` never hurts).
If you like this, could you merge it and release the VSCode extension? Then (and only then) we can do a Civet release.

Add LSP warning about using dev Civet

---

source/parser/function.civet
test/function.civet

Motivation: Avoiding the following:
https://github.com/DanielXMoore/Civet/blob/bf76cb6e0a624c97a84f3180507aec12a84e5832/source/parser/op.civet#L289
This function has a `return` up top, then defines some hoisted functions. Without this semicolon, the last function gets a `return` before it. Hence the semicolon to avoid this.
All this seems ugly. Instead we can turn off implicit return if there is a guaranteed return or other exit earlier in the same block. We already have `isExit` to detect this, so this amounts to a one-line check.

Avoid implicit return when block guarantees exit

---

integration/eslint/esbuild.civet
integration/eslint/package.json
integration/eslint/source/index.civet
integration/eslint/yarn.lock

* Use `comptime` to inline package version
* Use `assert` instead of `with` for greater Node compatibility (at least until `assert` gets deprecated, but hasn't happened yet)
* Switch to unplugin. I'd like to do `emitDeclaration` too, but there are a lot of type errors right now. (Also not getting Civet's types to load correctly... maybe a bug, to be investigated.)

eslint: comptime for version, assert instead of with

---

build/esbuild.civet
integration/example/simple.json
source/browser.civet
source/cli.civet
source/parser/comptime.civet
test/comptime.civet

* Use a new shim approach for browser build, enabling Node `import`s to be at top level
* `comptime require` no longer needs Civet to be in async mode! Async mode is just necessary for promises made by the user, so this is more natural.
* Run comptime using `vm` in Node, just like `repl` (used by CLI). Still use `eval` on browser.
* This isolates global variables.
* Currently a bit painful to serialize... I might be missing something simpler here, but at least it seems to be working.
* Improve comptime errors and imports a bit
* comptime
Switching to `vm` actually makes dynamic `import` work too, on Node 21.7+. But it generates a warning, so I haven't added a test. Here's a demo:
```sh
$ civet -c --comptime                  (node-shim ?$)
Civet 0.7.5 REPL.  Enter a blank line to transpile …
```

More comptime

---

source/parser.hera
test/function.civet

Fixes #1123
The change in the if/else is debatable, but this change is definitely good for expressionizing that wraps in IIFEs.

Avoid expressionizing statements in fat arrow functions

---

civet.dev/reference.md
source/parser.hera
source/parser/declaration.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/pattern-matching.civet
source/parser/types.civet
source/parser/util.civet
test/comptime.civet

Most of the work here is refactoring `ElseClause` into its own AST object node, instead of the previous use of a tuple. I think this is worth doing; a little less magic working when working with these clauses. Also added missing `BlockStatement`s when generating these in pattern matching. Also cleaned up that pattern matching code a bit, which took a while.
Added feature: `comptime` blocks can specify an `else` block to specify a different thing to do when `comptime` mode is off. This can be useful for typing, especially `Promise` vs. non-`Promise`. It can also help with things like linting when `comptime` is off: you get to specify the effective code that should be linted.

comptime else blocks, else refactor

---

source/parser.hera
test/class.civet

Fixes #1223
This was actually [in the spec](https://262.ecma-international.org/#prod-ClassElement), just hard to see the ";" at the end.

Allow EmptyStatement in ClassBody

---

source/parser.hera
source/parser/lib.civet
source/parser/util.civet
test/if.civet

Fixes #1224. We didn't have `children` in the intermediate AST node, so all earlier steps of processing were skipping the contents.
Also noticed and fixed an issue with excess `ref`s in negative index access when there was prepended whitespace. (See first commit for the ugliness that resulted.)

Fix preprocessing of declaration conditions

---

civet.dev/reference.md
source/parser.hera
source/parser/declaration.civet
source/parser/traversal.civet
source/parser/types.civet
source/parser/util.civet
test/compat/examples.civet
test/function.civet
test/if.civet
test/switch.civet
test/types/function.civet
test/while.civet

So I implemented the idea that declarations of `unless` and `until` go after the block instead of inside:
```js
unless x := f()
return
console.log x
↓↓↓
let ref
if ((ref = f()) {
return
}
const x = ref
console.log(x)
```
However, I'm no longer sure this is a good idea. For example, what if we have an `else` block?
```js
unless x := f()
return
else
// should x be bound here?
// should x be bound here?
```
I'm pretty sure `x` should be bound inside the `else`, and for symmetry with the other situations, I think also afterward? So my temptation would be to put the declaration of `x` above the `unless` instead of after it, so that it's accessible everywhere. It doesn't seem particularly bad to expose it to the "then" clause — this is actually more symmetric with `if` — what's important is …

Declaration inside unless/until adds declaration after block

---

source/parser/pattern-matching.civet
test/switch.civet

Fixes #1230
I think these are all the cases where things aren't actually bound, but let me know if you think of something else. We currently don't seem to have a computation anywhere of the names that are bound to.

Fix duplicate property merging for props not actually bound

---

source/parser.hera
source/parser/lib.civet
test/function-block-shorthand.civet
test/partial-placeholder.civet

Fixes #1231 
* `&` with binary operators in assignments (e.g. `x = &+1`) previously didn't stop at the assignment
* `&` in if/else previously stopped because the then and else clauses are wrapped in blocks; now we continue up if the clause is a one-liner
* `&` in ternary: `cond ? & : 0` previously treated `: 0` as typing. Now we require no space before `: Type` to disambiguate from ternary
* `.: x` was previously treated as `[.]: x`. While this is cool, it prevented typing of `.` placeholders. I've gone ahead and made `.` consistent with `&`: it can now be typed via `: Type`.
I'm a little worried about if/else. I'm sure how to feel about this example:
```js
=>
if cond
&+1
else
&+2
// ↓↓↓ (currently)
() => {
if (cond) {
return $ => $ + 1;
} else {
return $1 => $1 + 2;
}
};
// OR (this PR) …
```

Ampersand fixes

---

source/parser.hera
source/parser/types.civet
test/do.civet
test/if.civet

Fixes #1244
Oddly [TypeScript complains](https://www.typescriptlang.org/play/?#code/CYUwxgNghgTiAEA3W8AeAueA7ArgWwCMQYBtAXQFgAoAMwHsZ4AKMOrAZwBd4BPeOmmgCUAbmoB3ABYBLCAiaoSABjIBqVaOrA6I+FNnzFKgLTHNVatMELlZeAB40JAIxkh8AN4BfaiAjsQMQsqK2YjO0dFV3M-AKcVdSCgA) about an `if` block being the empty statement `;`, but doesn't complain about `else` blocks or loops.
For symmetry, I changed both `if` and `else` blocks to use `{}` empty blocks instead of `;`, but left loops alone. Also cleaned up postfix detection.

Use {} for empty if and else blocks

---

source/parser.hera

Fix #1250 - source mapping for AtThis identifier

---

source/cli.civet

Fixes #1254 (without yet addressing #1258).
Potentially controversial: Ties up `-h` and `-v`. I could instead just add `-help` and `-version`. Some languages such as Python and Rust use `-V` for version, so we could instead opt for that.

Generous matching of --version, --help

---

civet.dev/public/playground.worker.js
package.json
yarn.lock

I did this originally to fix some of the Prettier bugs we've been seeing. It didn't end up helping, but will be useful in the future to upgrade the Playground worker to the new Prettier 3 async interface.

Upgrade Playground to modern Prettier

---

source/cli.civet

Fixes #1255
The `(3)` shows the return code.

Invalid command-line argument handling

---

source/parser/block.civet
source/parser/util.civet
test/assignment.civet
test/binary-op.civet
test/comment.civet

In particular fixes the reported issue with https://civet.dev/comparison#automatic-semicolon-insertion

Fix ASI by handling tokens

---

source/parser/lib.civet
source/parser/types.civet
test/property-access.civet

```js
lastChild := node.children.-1
```
```js
let ref;const lastChild = (ref = node.children[ref.length-1])
```
```js
let ref;const lastChild = (ref = node.children)[ref.length-1]
```
Civet doesn't work if built with current Civet because this line is compiling incorrectly:
https://github.com/DanielXMoore/Civet/blob/41ba011b4a506af1c0a08b22a838a46e9f637fd2/source/parser/binding.civet#L140
Hopefully this will allow us to upgrade Civet and fix the CLI according to #1261.

Fix complex negative property access

---

README.md
integration/example/error-cjs.civet
integration/example/error-esm.civet
register.js
source/esm.civet
test/infra/esm.civet
test/integration.civet

Our rewrite in ESM support to NodeJS's new `module` `register` function (#1128) messed up `@cspotcode/source-map-support`. It seems that the `register`ed module (`esm.civet`) runs in a separate Worker or other context, so it doesn't enable sourcemap support in the main thread. We had a second call to source-map-support for CJS, but it was broken because it didn't specify `retrieveFile`.
A result of this is we can't (easily) use a cache to share the compiled source code between the build for loading and the build for sourcemapping. I think this is fine, as we only need to recompile when dealing with an exception, which is presumably exceptional. But I kept a cache in the sourcemapping side, in case the user uses exceptions for a lot of logic or something.
Also fixed a bug in CJS …

Fix source-map-support import with new NodeJS register

---

source/parser/lib.civet
test/if.civet

Empty then blocks in `if` expressions currently produce invalid JS.  [Example](https://civet.dev/playground?code=eCA9IChpZiB5CmVsc2UgNSk%3D):
```js
x = (if y
else 5)
↓↓↓
x = ((y?
: 5))
```
This PR adds a missing `void 0`.

Fix empty then clause in if expressions

---

source/parser.hera
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/binary-op.civet
test/function.civet

* `async`/`*` now added in a postprocessing stage
* More code sharing
* Errors in `=>` now appear at `await` statements
* Fix support in `operator` (fixes #1248)
* Allow explicit `async` and `*` in `operator` definition (also #1248)

Revamp automatic async and generator, operator support

---

lsp/source/lib/typescript-service.mts
lsp/source/server.mts
source/sourcemap.civet
test/integration.civet

It turns out #1262 introduced a bug in sourcemaps, which caused the VSCode plugin to crash because of negative column numbers. 😦 The key fix in this PR is removing the `+` here:
```diff
-        sm.column += line.length
+        sm.colOffset = line.length
```
Fixing this restores correct behavior. This is fairly urgent because the VSCode plugin is currently broken.
I also added a feature to the LSP / VSCode plugin: if there are nonfatal errors (via `Error` nodes), so there's still a transpiled document, we still get TypeScript diagnostics. Example:

Sourcemap fix, show diagnostics with nonfatal parse errors

---

source/parser.hera
test/pipe.civet

Found this missing use case when looking at the TC39 pipe operator docs.

Pipe to dynamic import

---

source/parser.hera
test/if.civet

I was experimenting with #918 by trying to reduce recursion opportunities by avoiding rules that consume zero tokens. It didn't solve the issue but I think it's a good direction.

Replacing some instances of __ with stricter whitespace checking

---

source/parser.hera
test/function-application.civet
test/object.civet

Fixes #918 by preventing accidental double matching of different cases of arguments.
This does not fix one missing `PushIndent` mentioned in https://github.com/DanielXMoore/Civet/issues/918#issuecomment-2189107922, which I'll probably leave for another PR: We don't consider indented expressions that are normal expressions, only those that are expressionized statements. So `x =\n  if ...` is considered an indented expression, but `x =\n  y` isn't. I think this is broken. For example, `a =\n  x\n  y` probably shouldn't [parse as a function call](https://civet.dev/playground?code=YSA9CiAgeAogIHk%3D).

Fix argument parsing

---

integration/example/test.civet
source/bun-civet.civet

This was an attempt at #1286, but the Transpiler doesn't actually seem to work as desired (need to manually specify `tsconfig`, and even then, it doesn't seem to add the implicit `import`, and the result behaves weird if the module has no `import`/`export`). But the cleanup was a moderate improvement, so I'm submitting that:
* Modify example to include TypeScript type notation, for testing
* Use Bun's file interface instead of Node compatibility layer
* Use braced object notation for cleaner methods
* Commented out code for manual transpilation of JSX (doesn't work yet)

Cleanup Bun loader code

---

lsp/package.json
lsp/yarn.lock
package.json
yarn.lock

TypeScript 5.5 should save us from having to give explicit types for type predicates, so it's a worthy improvement to the LSP in particular.
I did a simple test (counting errors from `civet --typecheck source/**/*.civet`) and it went down from 863 to 836. Not a huge decrease but a good sign!
Side note: A bunch of these ~800 errors aren't "real" (don't show up in the LSP); it seems that `civet --typecheck` isn't getting the type declarations from Node, so probably failing to load `tsconfig.json` somehow. Once resolved, we might make this a CI process to help count the number of errors and watch it go down, as in the mission of #1283.

Upgrade TypeScript

---

source/parser.hera
test/throw.civet

Follow up to https://github.com/DanielXMoore/Civet/pull/1293#issue-2372895605
> We don't consider indented expressions that are normal expressions, only those that are expressionized statements. So `x =\n  if ...` is considered an indented expression, but `x =\n  y` isn't. I think this is broken.
Basically, I added a few `MaybeNested...Expression`s that check for a properly indented expression. And I reviewed all uses of `ExtendedExpression` and a few others and decided whether to add this prefix. Mostly right-hand sides of assignments get this new treatment.
However, because we fallback to not-properly-nested parsing, it's still the case that `a =\n  x\n  y` [parses as a function call](https://civet.dev/playground?code=YSA9CiAgeAogIHk%3D). As a result of this, I can't actually think up a …

MaybeNested expressions

---

source/cli.civet

In trying to get Civet to typecheck itself, I noticed that `import`ing a `.civet` file didn't resolve because of the dreaded "import `.js` to get a `.ts` file" issue.
Also add a bit of typing to CLI itself.
This PR reduces the number of self-check type errors from 722 to 635, most of which seem "real".
(These numbers are assuming https://github.com/microsoft/TypeScript-Website/pull/3165 gets merged; until then, the numbers are higher because Node isn't successfully imported. Though we work around that issue by adding `types: ['node']` to `tsconfig.json`.)

Fix extension for CLI's `--typecheck`

---

package.json
source/parser.hera
test/types/type-declaration.civet

Fixes #1181:
* Allow arbitrary spaces around colon in type ternary
* Support nested interface block in if/else types
The big example from #1181 now works correctly:
```js
export function compile<T extends CompileOptions>(src: string, options?: T): Promise<
if T extends { ast: true }
CivetAST
else
if T extends { sourceMap: true }
code: string
sourceMap: SourceMap
else
string
>
---
export function compile<T extends CompileOptions>(src: string, options?: T): Promise<
(T extends { ast: true }?
CivetAST
:
(T extends { sourceMap: true }? {
code: string
sourceMap: SourceMap
}
:
string))
>
```

Fix if types

---

source/parser.hera
source/parser/declaration.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/class.civet

Added the usage half of mixins.
```
class A with B,C
x = 3
---
class A extends C(B(Object)) {
x = 3
}
```

Add class with A, B mixin notation

---

civet.dev/config.md
package.json
source/config.civet

Allow reading config from `civetConfig` property in `package.json`.
Includes support for `pnpm` [`package.yaml`](https://github.com/pnpm/pnpm/issues/1100), and maybe a starting point for the implementation of support for different config file formats, as @STRd6 mentioned in https://github.com/DanielXMoore/Civet/issues/647#issuecomment-1693542267.
> Allow for parsing different config file extensions based on what modules exist in the local user project
Related to #1239.

Allow `civetConfig` in `package.`[`json`|`yaml`]

---

integration/unplugin/src/index.ts

3 fixes for `civet --typecheck`, and `typecheck: true` in the unplugin:
1. Fix default JSX setting for TypeString engine. Not sure if this was always broken, or the lines got re-ordered, but we need to give a default value via an enum instead of a string here.
2. Include errors/warnings from `tsconfig.json` parsing. I noticed that errors such as `No inputs were found in config file 'tsconfig.json'.` were lying around in the parsed config output when debugging. Now we emit them along with (before) all the other errors, to better match `tsc` behavior.
3. Mangle [`imports` field](https://nodejs.org/api/packages.html#subpath-imports) in `package.json` for TypeScript. As reported by @danielbayley on Discord, it's reasonable to expect something like `"#types": "./src/types.civet"` to work, and …

Typecheck fixes

---

civet.dev/config.md
civet.dev/getting-started.md
integration/unplugin/src/index.ts
source/cli.civet
source/config.civet

CLI config files:
* Avoid using `package.json` as config file when it doesn't have `civetConfig` key.
* Enforce config filename checks to occur in our desired priority order, instead of being filesystem-specific. So e.g. `civetconfig.json` takes priority over `package.json`.
* Allow `civetconfig.js` (and all other config files can use `.js` — even `package.js` though this isn't documented)
* Allow `civetconfig.yaml` (and all other config files can use `.yaml`/`.yml` — previously was just `package.yaml`/`package.yml`)
* Fix `options.run` getting clobbered when any config file got read (which was particularly bad with `package.json`). Fixes #1303
Typechecking:
* Types in `node_modules/@types` are now automatically read, via a workaround until …

More CLI/typechecking fixes

---

source/cli.civet

Fix `civet < foo.civet > bar.tsx` accidentally turning on `js: true` and `inlineSourceMaps: true`
Introduced in #1304, as reported by @STRd6 on Discord

Fix pipe mode in CLI

---

README.md
civet.dev/integrations.md
integration/jest/.gitignore
integration/jest/README.md
integration/jest/index.civet
integration/jest/jest.config.mjs
integration/jest/package.json
integration/jest/test/example.civet

New `civet-jest` NPM package that makes it easy to run `.civet` tests and code with Jest.
I tested that the caching setup detects changing versions of the Civet compiler.

Jest integration

---

source/parser.hera
test/binary-op.civet

Prevent BinaryOp function shorthand from shadowing arrow functions.

---

.mocharc-self.json
.mocharc.json
package.json
tsconfig.json

Depends up updated Hera: https://github.com/DanielXMoore/Hera/pull/19

Use register to avoid experimental loaders deprecation warning

---

source/parser.hera
test/types/unique-symbol.civet

Fixes:
```civet
const callbacks: unique symbol = Symbol("eventCallbacks")
```
Where it fails to detect that `unique symbol` is a type.
https://civet.dev/playground?code=Y29uc3QgY2FsbGJhY2tzOiB1bmlxdWUgc3ltYm9sID0gU3ltYm9sKCJldmVudENhbGxiYWNrcyIp

support for 'unique symbol' type in TS

---

civet.dev/config.md
civet.dev/reference.md
notes/Comparison-to-CoffeeScript.md
source/parser.hera
source/parser/helper.civet
test/binary-op.civet
test/compat/coffee-div.civet
types/types.d.ts

Civet has `%%` (nice modulo) from CoffeeScript, but lacked `//` (integer division) from CoffeeScript/Python/etc. because it conflicts with JavaScript comments.
In Discord we came up with `%/` and `÷` for integer division, because:
* `%/` is parallel to `%%` (both are like adding a `%` prefix)
* `%/` doesn't mess up regexes (a previous proposal of `/%` would prevent the regular expression `/% /`)
* `%/` is different from Nim's different operator `/%` (unsigned division).
* `%/` looks somewhat similar to Unicode `÷` (which is how Julia represents integer division, and seems nice).
* Only downside is that `%/` is maybe hard to remember... but often used with `%%` so it will probably look reasonable.
I also added CoffeeScript `//` via `coffeeDiv` compatibility flag. This might break code that …

Add `%/`/`÷` integer division, fix `%%` precedence

---

source/parser/op.civet
source/parser/types.civet
test/binary-op.civet

As reported by Steffan on Discord, the `&&`s emitted to chain together relational ops have a lower precedence than those relational ops, which caused problems when surrounding them with ops that have precedence in between `&&` and relational (namely, `&`, `|`, `^`, and any custom `operator`s set to have those precedence).
I'm not sure this is the cleanest solution. (Initially I thought we could do something when expanding chains, when we already have the `&&` chain assembled — but parens are hard to add in there while maintaining the correct pattern of `[data, ws, op, ws, data, ws, op, ws, ...]`.) This PR adds a custom operator type and ties into the existing precedence logic, which at least seemed simple to implement.

Fix `&&` chain precedence with bitwise `&`/`|`/`^`

---

source/cli.civet
test/cli.civet

Fixes #1333
Demo:
`-e` doesn't work with `--typecheck`; we'd need to extend the unplugin interface to support strings instead of files.
If you specify multiple `-e` flags, currently just the last `-e` gets executed. This is how Node behaves. Oddly, Coffee executes the first one. We could easily run all of them with an `options.evals` array instead of a single string...
Also haven't implemented `-p` (print last expression) from Node.

CLI -e/--eval for running/compiling a string

---

CHANGELOG.md
README.md
build/changelog.civet
package.json

* Finds commits for all Civet versions via `git log -p`
* Finds all PR commits and assigns them to versions
* Looks up current PR titles so we can improve bullets in this changelog via the GitHub GUI
* Rewrites `CHANGELOG.md` from scratch
Currently this isn't part of any workflow. I think the following would work for manual update + release:
* Update `version` in `package.json`
* `git commit -a -m <version>` (version commit)
* `npm run changelog`
* `git commit -a --amend` (add CHANGELOG changes to same commit)
* `npm publish`
I'm very open to better workflows though; it'd be nice for this to be as automatic as possible.

Automatic changelog creation

---

civet.dev/reference.md
source/parser.hera
test/at.civet
test/call-expression.civet
test/class.civet
test/optional-chain.civet
test/types/non-null-assertion.civet

As proposed in #1327 thread, and Discord, and as in Coco.
Fixes #1327 in particular.

Optional dot in `?.` and `!.` property access: `x?y` and `x!y`

---

CHANGELOG.md
build/changelog.civet

This is a quick performance boost for changelog generation.
It now takes 1-2 seconds on my machine to generate a changelog. I'd be curious what it is for you (and whether you have a different bottleneck).

changelog generation: fetch PRs mostly in parallel

---

source/parser.hera
source/parser/function.civet
source/parser/types.civet
source/parser/util.civet
test/function-block-shorthand.civet

Reported by @bbrk24 on Discord
Also add some more types. Total number of errors reduced from 641 to 627 (as measured by `civet --typecheck source/**/*civet`).

Add missing parens in ampersand functions starting with object literal

---

civet.dev/integrations.md
integration/metro/README.md

Based on https://github.com/DanielXMoore/Civet/issues/536#issuecomment-2282182234 by @etherealHero
Instead of including a large block in `integrations.md`, I opted to make a new file to link to. It could go in `notes` or `integrations`; I opted for the latter. It's maybe a little weird to have a directory with just a README, but `integrations` is already a bit of a grab-bag... Other ideas welcome!

Document how to use with React Native / Metro bundler

---

civet.dev/getting-started.md
integration/unplugin-examples/esbuild/esbuild.js
integration/unplugin-examples/esbuild/tsconfig.json
source/unplugin/unplugin.civet

Currently, using our unplugin with esbuild and `ts: 'esbuild'` crashes (as reported by @bbrk24 on Discord), because:
* esbuild returns a string sourcemap
* We parse this as JSON (necessarily)
* unplugin attaches a `toUrl` but not `toString` method, accidentally accepting `Object.prototype.toString`
* It ends up encoding `[object Object]` (the output of the `toString` method) as the sourcemap.
This will be fixed by https://github.com/unjs/unplugin/pull/399, but here's a workaround until then.

Fix esbuild unplugin sourcemap bug

---

civet.dev/reference.md
source/main.civet
source/parser.hera
test/array.civet
test/partial-placeholder.civet

Bulleted arrays with `.` or `•`

---

CHANGELOG.md
build/changelog.civet

First run generates this output:
```
Tagging v0.1.0 -> 5f2c466ea03360efa6461784e57a7702a1dfbbf9
Tagging v0.1.1 -> 63f0e43ab17b9c1f54b52ffafd015d621e3bfd6f
Tagging v0.2.0 -> 570be10a179c8f348a7f776991b2e2033684d141
Tagging v0.2.2 -> a6fe0838d0198e65dd331dcec61092f048fdbc3e
...
Tagging v0.7.20 -> 1f6b8c4c86780a7db396a662a9603f3b3e5c0e4f
Tagging v0.7.21 -> ffa327c2488dfb20e06b70718afa4b78c4909cde
Tagging v0.7.22 -> 2911264c014135f356955967f0085352ed569f64
Tagging v0.7.23 -> a57ef22f8a53c53268afeacf570ab41a80711434
```
Second run generates no output (all tags verified pointing to the correct place).
Once approved, I'll push all the tags to the repo.
In the future, upon release, we'd do `git push --follow-tags` to push the new release tag.

Generate tags for Civet releases

---

source/parser.hera
test/if.civet

This PR explores the proposal from https://github.com/DanielXMoore/Civet/issues/1090#issuecomment-2291837213 :
> I wonder if it would work (and be unambiguous) to allow an *indented condition* to use (further) indented function calls:
>
> ```js
> // if/then/else
> if
>   (and)
>     x
>     y
>   console.log 'yes'
> else
>   console.log 'no'
> 
> // postfix unless
> return unless
>   (and)
>     x
>     y
> ```
It does seem to work quite well! I think this is a natural extension of various settings where we allow indented expressions (e.g. after `return` or `yield`). It looks a little weird when you don't have an indented application, but the expression still has a clear "end" (from the line break):
```js
if
a + b < 10
console.log 'small'
```
I'd like to propose that this fixes #1090, but …

Indented if/unless conditions to enable indented function calls (e.g. `(and)`)

---

build/perf-compare.sh
source/parser.hera
source/parser/lib.civet
test/if.civet

Inspired by https://github.com/DanielXMoore/Civet/pull/1364#pullrequestreview-2244181171
> There’s probably more we can do here eventually [...]
and specifically https://github.com/DanielXMoore/Civet/issues/1090#issuecomment-1981438104
> Perhaps we could make an exception when there's an explicit `then`.
This PR allows for indented function calls in an `if` condition when there's an explicit `then` to indicate the `then` block. Unlike usual `then`, this one allows for an indented block after it, symmetric to `else`. This lets us write:
```js
if (and)
cond1
cond2
then
// match
else
// no match
```
as well as #1090's original request:
```js
return if (and)
upper.test exactOrAny.toString()
lower.test exactOrAny.toString()
then exactOrAny
else undefined
```
One potential issue is that this …

Indented calls in `if` conditions with explicit `then` clause (#1090)

---

CHANGELOG.md
CONTRIBUTING.md
build/changelog.civet
package.json

This PR improves the release process to the following:
* Increment `version` in `package.json` (e.g. `npm version patch` / `yarn version --patch`)
* *(don't manually run `git commit`)*
* `npm publish`, which runs `yarn changelog --release`
* In this new "release" mode of the changelog script, it asks whether to run `git commit -a -m <version>` with the new changes. For example, if I increment `version` in the current state, it makes this commit:
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 194968bd..797efd81 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -4,7 +4,7 @@ This changelog is generated automatically by [`build/changelog.civet`](build/cha
For each version of Civet, it lists and links to all incorporated PRs,
as well as a full diff and commit list.
-## Unreleased …
```

Improved release process and changelog generation

---

source/parser.hera
test/binary-op.civet

Fixes #681 by supporting
```js
import operator { ... } from ...
// and implicit form
operator { ... } from ...
```
Precedence can be specified next to `operator` (to specify a default) or after the individual operators.
I didn't yet implement `import operator foo from bar` (default import).

`import operator` bulk import of operators

---

civet.dev/reference.md
source/parser.hera
source/parser/pattern-matching.civet
source/parser/types.civet
test/switch.civet

Part of #661
I realize the original request was for fall through in the pattern matching case. That will require more work... But at least this is a start.

`continue switch` to fall through at the end of `when` clause

---

civet.dev/comparison.md
civet.dev/reference.md
source/parser.hera
test/label.civet

Svelte 5 no longer uses `$:` labels.
If you need `$:` labels in Civet, use `:$` instead.

Remove Svelte label `$:` exception

---

source/parser.hera
test/do.civet
test/for.civet
test/switch.civet

Fixes #1168 in a surprisingly simple way: don't parse `if`/`switch`/`try`/iterations as `Statement`s if they're followed by an `AllowedTrailingCallExpression` or `Pipe` operator, leaving them to be parsed as expressions later on.
Also found a simpler way to avoid `async do` and `async for` from being parsed as calls to a function `async`: swapping the order so that `ExpressionizedStatement` gets checked before `UpdateExpression` (which includes `CallExpression`). This brings these into alignment with `async function` and so on which had no special handling.  (This was also a necessary step; the workaround from before didn't work with the rest of this PR.)

Expressionize statements followed by trailing member access/call or pipe

---

civet.dev/reference.md
source/parser.hera
test/object.civet

I was looking back at old Discord messages and noticed this feature suggestion by @esthedebeste. (She also suggested spaces, but that seems harder.)
Hyphenated names are at least a small improvement that's nice for dealing with HTTP headers. Existing support for numbers take priority, so e.g. `-0n:` still turns into a key of `0`, while `-0n-x:` doesn't parse. Basically you need to start with a letter or a hyphen followed by a letter.

Hyphenated object keys like `Content-Type:`

---

integration/eslint/esbuild.civet
integration/eslint/example/package.json
integration/eslint/package.json
integration/eslint/source/index.civet
integration/eslint/yarn.lock
lsp/source/lib/typescript-service.mts
source/unplugin/unplugin.civet

This started as a deps update for the eslint plugin (so apologies for the large `yarn.lock` update), but then turned into bug fixes:
* The unplugin wasn't using specified `parseOptions` if TS mode was off (no `emitDeclaration` or `typecheck`).
* The eslint plugin was using old-style import assertions (`import...assert`) which I just learned have been *removed* from Node 22. I switched it to import attributes (`import...with`) which has been around longer now so is hopefully sufficiently backward compatible.
* The VSCode plugin was also using import assertions. I tested on NodeJS 20.14.0 used by current VSCode, and it supports import attributes, so I changed the code. (I think this wasn't the case last time I checked.) We don't need to release yet, but we should release sometime before …

Fix unplugin `parseOptions`, fix eslint plugin for Node 22

---

package.json

Should allow dependabot to fetch the changelog

Add `repository` to `package.json`, fixing Dependabot changelog detection

---

source/parser.hera
source/parser/binding.civet
source/parser/declaration.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/types/destructuring.civet

Fixes #126 by implementing a long-sought syntax for typing individual object properties and array elements in left-hand-side patterns (including function arguments and assignment). Basically, `:: type` can come at the end of any existing object property or array element.  For example:
```js
function Component({
name: [first:: string, last:: string, ...rest:: string[]],
counter:: number
setCounter: sc:: (number) => void
})
↓↓↓
function Component({
name: [first, last, ...rest],
counter,
setCounter: sc
}: {
name: [ string, string,... string[],],
counter: number,
setCounter: (number) => void,}){}
```
Why this notation?
* `name:: type: value` is ambiguous: it could be interpreted as `name:: {type: value}` (typing as object). (I tried to include this as an option at first, but ran into this …

Typing of object/array pattern components via `::`

---

source/parser/pattern-matching.civet
source/parser/types.civet
test/if.civet

```js
if {
type
name, value
} := node
console.log type, name
```
```js
if ((node) && typeof node === 'object' && 'type' in node && '
name' in node && 'value' in node) {const {
type,
name, value
} = node;
console.log(type, name)
}
```
```js
if ((node) && typeof node === 'object' && 'type' in node && 'name' in node && 'value' in node) {const {
type,
name, value
} = node;
console.log(type, name)
}
```
More typing fixes (reducing number of TS errors from 611 to 607) and Civetification

Fix pattern matching with indented object patterns

---

civet.dev/config.md
civet.dev/reference.md
source/parser.hera
test/jsx/code.civet
types/types.d.ts

This PR should finish the rest of and thus fixes #561.
* `"civet jsxCode"` treats all JSX children as Civet expressions.
* I went with my original proposal where each Civet line of code is treated as a separate expression wrapped in braces. I think this is the most common case, where you have many consecutive `if`s and such, each of which needs to render. And it's easy to make a larger block, using a `do` block. (See example in documentation.)
* I was less sure whether children on the same line should be treated as code, so I made it an option!
* `"civet jsxCodeNested"` just enables the code mode for nested (indented) children.
* `"civet jsxCodeSameLine"` just enables the code mode for same-line children (not sure why you'd do this, but I originally had in mind `"civet jsxCode …

`"civet jsxCode"` directive treats JSX children as Civet code

---

civet.dev/reference.md
source/parser.hera
test/jsx/code.civet

One more idea from #561: This PR allows for lexical declarations as JSX code children (as braced expressions, `>` expressions, or automatic code children). In particular, this example now works:
```js
<div>
user := getUser()
if user?
{name} := user
<h1> `Welcome ${name}!`
<h2>Posts</h2>
for post of posts
<div .post> post.jsx()
```
Somewhat unusual for Civet is that the declaration is *not* treated as an expression, as that would cause it to render in the JSX, which seems rarely desired. Instead we automatically add `,void 0` at the end to prevent rendering and just do the assignment. The declaration itself gets lifted (though there's no way to preserve `const` semantics here).

Lexical declarations as JSX code children

---

integration/eslint/CHANGELOG.md
integration/eslint/package.json

This changelog is manually maintained, and currently no tags or explicit links. But I think it's a pretty small effort to manually update changelogs for these smaller subprojects, and seems less crucial to have tags. (`git log integration/eslint` can be used to see all relevant commits; it's what I used to make this changelog.)

Add changelog to eslint plugin

---

source/main.civet
source/parser.hera
test/types/type-declaration.civet

Fixes #1355
* As expected, some `__`s needed to be `NotDedented`. I just changed the minimal amount here, around binary operators. (Plausibly more should change, but not for this issue.)
* I added a special rule for matching properly indented binary-operator chains like this:
```ts
| T1
| T2
```
* All this still wasn't enough, because the indentation level was already 2 in this case. I needed to add an indentation level of +1 for these items so that `NotDedented` doesn't allow for grabbing the second item.
This feels related to https://github.com/DanielXMoore/Civet/issues/1121#issuecomment-2292132835 as well. (I could use feedback on those ideas too, though doesn't need to happen before this PR lands.)

Improve indentation handling with union/intersection types

---

source/parser.hera
test/function-application.civet
test/function-block-shorthand.civet
test/pipe.civet
test/property-access.civet

Currently, nested implicit arguments create an extra implicit comma at the end of the arguments.
I had to fix this for #1391 because type arguments can't have a trailing comma in TypeScript.
This led the way to fixing it for function calls too.

Remove final implicit comma in nested arguments, better matching source

---

civet.dev/reference.md
source/parser.hera
test/function-application.civet

As reported by @bbrk24 
Also add missing documentation for `?` and `!` shorthands for `?.` and `!.`.

Fix `!` negated indented argument in function call

---

civet.dev/reference.md
source/parser.hera
source/parser/function.civet
source/parser/types.civet
source/parser/util.civet
test/for.civet
test/loop.civet

Fixes #1395
TODO: Documentation
An issue with TypeScript is clear in the `loop` example: we have `let results = []` but later `results = 'done'`. Perhaps we could detect specifically a `loop` that has no plain `break` and thus will only be exited via `break with`, and then we could just write `let results`.

`break with` and `continue with` for modifying results array in a loop

---

source/cli.civet
source/main.civet
source/parser.hera

Traces have been incorrectly indented for a while because of uncacheable rules; they dedented without a matching indent. Perhaps we should log them, but for now I've just made `exit` match `enter` by not logging in both.
Also realized we no longer need the `getStateKey` hack, thanks to Hera's ` ``` `.

`--trace` fixes and documentation, cleanup of `getStateKey`

---

README.md
build/esbuild.civet
civet.dev/integrations.md
integration/script/README.md
integration/script/test.civet
integration/script/test.html
package.json
source/browser-shim.civet
source/browser.civet
source/sourcemap.civet
yarn.lock

Similar to [CoffeeScript](https://coffeescript.org/#scripts), added support for automatically running `<script type="text/civet">` code that appears in the HTML that loads the browser build of Civet.
The new `source/browser.civet` in general allows us to add code specific to the browser build.
I renamed `source/browser.civet` to `source/browser-shim.civet` but the diff doesn't show it that way.
**Motivation:** Easy to run Civet in online sandboxes without any build tools.

Run `<script type="text/civet">` in browser build

---

source/unplugin/README.md

I just did some testing with getting `.civet` files to work as Web Workers using [Vite's Web Worker support](https://vitejs.dev/guide/features.html#web-workers).
1. Thanks to chee on Discord, it seems that the first method (with constructors) works if we add a `.tsx` extension to the `.civet` filename.  I'm not really sure why this is necessary. 
2. Unfortunately, the `?worker` import syntax doesn't seem to work, perhaps because our plugin needs to do something special in this case.  (I get complaints of no default export, despite it seeming like it should be created automatically.)
This PR documents the current state, and also raises the opportunity for anyone to chime in on how the above two issues could be improved by modifying the plugin.
Annoyingly, for `vite build` to work, it seems …

Document how to use Civet Web Workers in Vite

---

package.json
source/config.civet
types/types.d.ts

Latest esbuild had a warning about our order when declaring exports so I changed it:
```
▲ [WARNING] The condition "types" here will never be used as it comes after both "import" and "require" [package.json]
../package.json:49:6:
49 │       "types": "./dist/unplugin/rollup.d.ts"
╵       ~~~~~~~
```
I also added default exports to config, and fixed up the types for the default export.

change types order in package.json exports; default config exports

---

civet.dev/public/shiki/languages/coffee.tmLanguage.json
lsp/syntaxes/civet.json

I just replaced all instances of "gimuy" (full list of RegExp flags as of ES2017) with "dgimsuvy" (full list of RegExp flags as of current ES2024), since regex literals with the `d` or `v` flags are not currently highlighted as regexen.

Add syntax highlighting support for /d, /s and /v RegExp flags

---

source/parser/function.civet
test/types/function.civet

Fixes #1401
I incorrectly claimed that you can mix `export`ed and non-`export`ed function overrides in TypeScript. That's actually an error, but it's better to support it and let TypeScript report the error.
Previously, we never added a blank body to an `export`ed function. But this isn't really what we want. `export function ...` should always provide an implementation. Now we correctly skip over the `ExportDeclaration`s to compare functions.

Fix implicit empty body for exported functions

---

source/main.civet
source/parser.hera
source/parser/binding.civet
source/state-cache.civet
test/function.civet
test/types/function.civet

Fixes #1402
The main challenge here was fixing a caching bug. By `Object.freeze`ing the cache result, I found that the `value` of a cache result for `ArrayBindingPattern` was getting overwritten when `ShortArrowParameters` got parsed, via this line:
https://github.com/DanielXMoore/Hera/blob/d2aff817973973ace404b7fbe8ec705b4653e807/source/machine.ts#L443
This is specific to the `ShortArrowParameters` rule having just one thing in it (`$TS`). For example, adding a `""` to the rule fixes the problem. Though I don't see much difference between how `$TS` works and the other cases do; they all seem to modify `result.value` in-place.
I'm not sure if Hera is supposed to guarantee any kind of immutability in this case. In Civet, we already did `{...result}` on cache `get`, but didn't yet do it on …

Fix typed patterns in arrow function with unparenthesized parameter

---

source/parser.hera
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/types/type-declaration.civet

* Adds missing parenthesization in type `=>?`
* Previously: `()=>void | undefined` which didn't respect how it actually parsed
* Now: `(()=>void) | undefined`
* Clean up type AST nodes a little bit

Fix arrow type with `?` postfix

---

source/unplugin/README.md
source/unplugin/unplugin.civet

Fix `import MyWorker from './worker.civet?worker'` by preserving query/hash in unplugin.
Also Civetify `unplugin.civet` a little.
(followup to #1403)
I also tried to get the URL notation to work with `.civet` instead of `.civet.tsx`, but it doesn't seem to reach the unplugin at all in that case...

Enable `worker.civet?worker` import in Vite

---

source/parser.hera
source/parser/declaration.civet
source/parser/function.civet
source/parser/types.civet
test/if.civet

Fixes #1422
We had a bunch of places where we add a semicolon to the `then` block of an `IfStatement` to separate it from an `else` block, but none that applied universally. Now apply the logic when building the AST, instead of when doing implicit returns from functions. There are still a couple of places with the add-semicolon logic, where we add extra `else` clauses.
Also improve more typing. This PR reduces the number of type errors from 718 to 673! (via `civet --typecheck source/*.civet`)

Fix missing semicolon in if/unless followed by else

---

civet.dev/reference.md
notes/Comparison-to-CoffeeScript.md
source/parser/function.civet
test/class.civet
test/compat/coffee-classes.civet
test/comptime.civet
test/do.civet
test/function-block-shorthand.civet
test/function.civet
test/jsx/objects.civet
test/object.civet
test/semicolon.civet

This PR turns off implicit `return` at the end of generator functions (`function*`, implicit or explicit).
I think it's extremely common not to want to have implicit `return` in generators, especially when you have loops (very common in generators); it creates a wasteful array. As you can see in this PR, an example is in the docs, where I previously had to add an explicit `return` to prevent a final `return`.
I've not yet used the special final return value of generators (which is what gets set by `return`ing a value). It's pretty hard to use, because the standard way to consume generators (`for x of gen()`) skips it completely. So I think this is the normal case that's desired.
This is a breaking change, though, so worth thinking about. It's also an incompatibility with CoffeeScript …

Stop implicitly returning final value from generators

---

civet.dev/reference.md
source/parser.hera
source/parser/lib.civet
source/parser/types.civet
source/parser/unary.civet
source/parser/util.civet
test/await.civet
test/function-application.civet

As suggested in #1429 and #1431, adds support for
```js
await
indented expression
↓↓↓
await (
indented expression
)
```
Then as further suggested by @STRd6 on Discord, you can list multiple expressions too. They get bundled into an array:
```js
await
e1
e2
↓↓↓
[
await e1,
await e2]
```
Bulleted arrays behave the same, too, in case you think that looks nicer:
```js
await
. e1
. e2
```
This is in parallel to a previous way to use `await.op`. You can use those without bullets too:
```js
await.op
e1
e2
↓↓↓
await.op([
e1,
e2])
```
Note that there's a bit of asymmetry here: with a single argument, it's passed directly into `await.op`, in case it's an array.  More than one argument gets wrapped into an array. I think this is the most useful behavior, but I'm not certain.

`await` with indented argument, or multiple arguments as array

---

civet.dev/reference.md
source/parser.hera
source/parser/unary.civet
test/await.civet

This PR brings `await [x, y]` into alignment with
```js
await
. x
. y
```
and
```js
await
x
y
```
(but `await x, y` remains as is, for JS compatibility)
It's mostly a 1-word change (`NestedBulletedArray` → `ArrayExpression`), but I added a little more code to make the spacing come out better.

`await` with array literal awaits the items

---

source/parser.hera
source/parser/function.civet
test/compat/coffee-do.civet

Fixes #763 by using `PushIndent`/`PopIndent` or `_` instead of `__`, which prevents a second equally indented line from appearing to be strictly indented.
Fixes #1432 by moving `CoffeeDo` handling from `UnaryExpression` to `UnaryBody`, keeping precedence but allowing unary operators before `do`.

CoffeeScript `do` allows unary operators beforehand, and handles nested body better

---

source/main.civet
source/parser.hera
source/parser/lib.civet
test/binary-op.civet

Fixes #1121 at least, as outlined in https://github.com/DanielXMoore/Civet/issues/1121#issuecomment-2331851911
#1280 shows that we also have the issue with the pipe operators, and this doesn't fix that yet. I think it could, with the same flag, but we'd first need to do `PushIndent`/`PopIndent` to recognize the indentation level of the first `|>` so that the future ones are recognized as being `Nested` and thus not valid continuations of an argument.
There *might* be other places where we need to `ForbidNestedBinaryOp`, but none come to mind yet... at least, this makes it easy to add more if necessary.

Binary operators continue arguments only if strictly indented

---

source/main.civet
source/parser.hera
source/parser/function.civet
source/parser/lib.civet
test/array.civet
test/function-application.civet
test/function.civet
test/pipe.civet

Fixes #1280 by adding a new `ForbidPipeline` flag, as discussed in #1440.
This new feature also let us unify `ArgumentList` and `NonPipelineArgumentList`. The former had gotten out-of-date, so I updated to match `NonPipelineArgumentList`, then removed the latter.
I tried removing more `NonPipeline...` rules, but it's tricky specifically for parsing pipelines: `PipelineHead` needs to parse everything up to a `Pipe` operator (to avoid left recursion), but it doesn't work to use `ForbidPipeline` for this, because then it breaks code like
```js
=> x |> y
```
With `ForbidPipeline`, we'd end up parsing `=> x` as the head, which isn't what we want. But we also don't want to just `AllowPipeline` when we enter a non-indented function body, because then we'd misparse something like this:
```js
f => …
```

Forbid pipes in non-nested implicit arguments

---

source/parser.hera
test/for.civet

Fixes #1439. The problem stemmed from `ExtendedExpression` calling `NonAssignmentExtendedExpression` which calls `ExpressionizedStatementWithTrailingCallExpressions` which doesn't allow for pipes.
What was confusing was that this version worked:
```js
t =
for [0..1]
;
|> foo
```
The reason is that the newline prevents `ExpressionizedStatementWithTrailingCallExpressions` from matching, so this rule gets completely ignored. And then everything works!
This suggested a radical solution: remove `NonAssignmentExtendedExpression` and related rules entirely. They're not actually needed, because `UnaryBody` directly calls `NestedNonAssignmentExtendedExpression` and `RHS` directly calls `ExpressionizedStatementWithTrailingCallExpressions`. (It looks like this redundancy began way back in #475.) So …

Assigned expressionized statement followed by pipe, grammar cleanup

---

source/parser/types.civet
source/parser/util.civet
test/do.civet

Fixes #888
Most cases were already handled by IIFE unwrapping. `yield*` ought to do the right thing in expression contexts, though the behavior is admittedly weird; at least it seems to match Babel output.

`yield` in `do` yields in parent in all cases

---

source/parser.hera
source/parser/function.civet
test/function-application.civet

Fixes #869 by re-allowing trailing member/call in *properly nested* arguments (where it's no longer ambiguous whether the trailing applies to the argument or the function result).
A breaking change is that this parse changes:
```js
f
a
.b
```
[Previous transpilation](https://civet.dev/playground?code=ZgogIGEKICAuYg%3D%3D):
```js
f(
a,
$ => $.b)
```
New transpilation:
```js
f(
a
.b)
```
I'm not totally sure which is more intuitive; this is a fundamental ambiguity we've had for a while. But perhaps a good analogy is this:
```js
=>
a
.b
```
This returns `a.b`, not `$ => $.b`. This PR matches that behavior in arguments too.
An alternative would be to do different things depending on whether `.b` is indented the same or further than `a`. This would be harder to implement, though, and I guess …

Nested function arguments support trailing member access/call

---

source/parser.hera
test/types/try.civet

Fix `catch` type annotation by forbidding indented type arguments in `catch`

---

civet.dev/reference.md
source/parser.hera
test/function-block-shorthand.civet

Fixes #1225 similar to the proposal in https://github.com/DanielXMoore/Civet/issues/1225#issuecomment-2096399611: Only `TypePrimary` is allowed as a `&` type annotation, unless the type is nested in which case it can be anything. This means that any use of operators (including `|`, `&`, and ternary `?:`) need to be wrapped in parentheses.
BREAKING CHANGE: `&: number | string` is now treated as `(&: number) | string`, and `&: T ? a : b` is consistently treated as `(&: T) ? a : b`

Require parentheses in complex `&` type annotation

---

source/cli.civet

I was thinking about https://github.com/DanielXMoore/Civet/issues/1195#issuecomment-2081269154, and noticed that the CLI had two bugs when running code with top-level `await` (where it builds an IIFE wrapper):
* It no longer correctly found the `BlockStatement` of the IIFE, instead getting distracted by the (relatively new) `BlockStatement` at the very top of the AST and the extra braced block wrapper.
* The search for `BlockStatement` was also broken in `coffee-do` mode.
* All declarations not wrapped in functions were lifted, instead of just the top-level ones (not inside a nested block). Should now match the non-async behavior (except `const` becomes `var`).
Tests:
This probably wants to be a separate function, with tests, but at least it's working for now. I'm hoping to add this as a …

CLI exposes top-level declarations with top-level `await`

---

build/build.sh
build/esbuild.civet
civet.dev/getting-started.md
integration/unplugin-examples/esbuild/esbuild.js
integration/unplugin-examples/esbuild/tsconfig.json
source/cli.civet
source/unplugin/README.md
source/unplugin/unplugin.civet
tsconfig.json

Fixes #1316 
CLI:
* `civet` CLI still defaults to `.civet.tsx` and `.civet.d.ts` output files.
* `civet -o .js --emit-declaration` will now produce `.js` and `.d.ts` files.
unplugin gains a `declarationExtension` option that defines the output `.d.ts` extension, effectively defaulting to `.civet.d.ts` (generated by TypeScript given that our filenames are internally `.civet.ts`).
Incidentally, unplugin's `outputExtension` option seems poorly named. This is really an extension appended to the `.civet` filename to represent the intermediate file, but it's never actually saved with this name; the actual output is determined by the bundler. Is it worth renaming? I actually can't think of a purpose for setting it manually, except perhaps triggering certain other plugins in the toolchain (e.g. a …

`.d.ts` matches output extension in CLI; `declarationExtension` option in unplugin

---

source/cli.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet

* Move error handling attachment outside the main loop so we don't add *n* error handlers (when not running code so might be compiling several files)
* For stdin inputs (including `-e` argument), fix `filename` not being exposed to rest of code, which caused a crash whenever running ESM code
* Fix ESM detection to do an actual AST analysis, and consider code with top-level `await` to be ESM (as it crashes in CJS mode)

Fix CLI executing ESM code from stdin or `-e`

---

source/cli.civet
source/generate.civet
source/main.civet

As reported by @bbrk24 in Discord.
Also fixed some type errors that might have been actual bugs (don't pass in a `boolean` `sourceMap` option to `generate` by setting it to `undefined`, but then handle `undefined` `sourceMap`).

CLI REPL supports (strips) TypeScript

---

source/parser.hera
test/types/interface.civet

Variance annotations (`in`/`out`) in type parameters

---

source/parser/function.civet
source/parser/pipe.civet
test/pipe.civet

Fixes #1172
I opted to keep the ampersand function a function here, instead of unwrapping and using refs, because:
* it was easier to implement
* it seems slightly closer to the input

Pipeline doesn't unwrap in multi-`&` function shorthand

---

source/parser/op.civet
source/parser/util.civet
test/array.civet
test/binary-op.civet
test/property-access.civet

Fixes #1456
Also removed some unnecessary parens around array expressions.
~~I'm not a fan of the extra parens in `x ++ y ++ z`: it previously compiled to `x.concat(y).concat(z)`, and now compiles to `(x.concat(y)).concat(z)`. But I didn't see an easy way to fix, because the binary expression precedence handler doesn't construct "correct" AST nodes.~~  I fixed some of the AST node types to fix this.

Add missing parentheses with `++` concat operator

---

civet.dev/public/playground.worker.js
civet.dev/reference.md
source/cli.civet
source/parser.hera
source/parser/comptime.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/comptime.civet
types/types.d.ts

Fixes #1195 as shown here:
More generally, I followed the idea in https://github.com/DanielXMoore/Civet/issues/1195#issuecomment-2081269154 to add two general mechanisms for wrapping programs in IIFEs:
* `"civet iife"` adds a wrapper similar to CoffeeScript, except that we also support `import` (via dynamizing `import`). This can be useful when running non-module scripts in the browser (to avoid `var` becoming a global) or when concatenating CJS scripts together (to avoid declarations from earlier scripts from being visible to later scripts). But in particular a step toward:
* `"civet repl"` additionally pulls top-level declarations out, like we had a ton of gross code to do in both the CLI and Playground. Now it's just adding an option and we get exactly the code we need to `eval`!
This …

Compiler directives `iife` and `repl` for wrapping program, fix `comptime` implicitly returned from function

---

source/parser.hera
source/parser/function.civet
source/parser/lib.civet
source/parser/traversal.civet
source/parser/types.civet
source/parser/util.civet
test/function.civet
test/if.civet
test/iife.civet
test/switch.civet

Follow-up to #1463 to also hoist `function` and `class` declarations like JavaScript does:
* Top-level `function`s gets declaration and value hoisted to outside, by physically moving the declaration
* Inner `function`s get declaration hoisted outside but value remains where it is.
* `class` declarations get hoisted like `let`: only top-level get hoisted.
* Also fixed: inner `var` declarations get hoisted to outside.
As a result, the CLI behaves like this:
```
🐱> f()
... function f() console.log 'hi'
...
hi
[Function: f]
🐱> f()
...
hi
undefined
🐱> if true
...   function g() console.log 'yes'
... else
...   function g() console.log 'no'
... g()
...
yes
undefined
🐱> g()
...
yes
undefined
🐱> class C
...
[class C]
🐱> new C
...
C {}
```
A necessary step to get here was to clean up how …

`repl` directive hoists function and class declarations too, fix one-line declarations in `if`

---

civet.dev/comparison.md
source/parser.hera
test/class.civet
test/do.civet
test/if.civet
test/object.civet

Fixes #1465 by allowing for single line of statements inside one-line braces in `class`es and `if`/`else` blocks.
For `if`/`else` blocks, I could actually make the grammar a bit smaller by using some existing rules we had for `BracedContent` (from a different branch of the tree where blocks always need to be braced, such as function bodies).

One-line braced blocks with single-line statements

---

source/parser.hera
test/if.civet

During #1467, I noticed that our implicit function application magic did the following:
```js
f(x) if x
{
x
}
↓↓↓
if (x) { f(x) }
({
x
})
//not:
f(x)(x ? {x} : undefined)
```
I think this is reasonable, because we only need to implement braced-blocks backward compatibility with natural JS constructs, and `if` expressions are not such a construct.
This PR extends this functionality for other common patterns with `yield` and `return`:
```js
return if x
{
x
}
↓↓↓
if (x) { return }
({
x
})
//as opposed to the current behavior:
return x ? {x} : undefined
```
This brings argumentless `return`/`yield` into alignment with having an argument:
```js
return x if x
{
x
}
↓↓↓ (before and after this PR)
if (x) { return x }
({
x
})
```

Forbid next-line braced blocks after `return if` and `yield if`

---

civet.dev/reference.md
source/parser.hera
source/parser/function.civet
source/parser/types.civet
test/types/class.civet

Fixes #549
Fixes #970
TODO (not for this PR): Handle type suffix of entire complex parameter pattern, e.g. `[@name, @id]: [string, number]`. I'm imagining this might compile to something like `name: [string, number][0]; id: [string, number][1]`, leaving the type computation to TypeScript. But for now we support these forms:
* Straight arguments like `@name: string`
* Individually typed pattern components like `[@name:: string, @id:: number]`

Automatically type fields using `@arg` in constructor

---

civet.dev/reference.md
source/parser.hera
source/parser/function.civet
test/for.civet
test/types/as.civet

This PR originally aimed to implement (and achieves) the suggestion from https://github.com/DanielXMoore/Civet/issues/1135#issuecomment-2032593949 to support
```js
t = for i of [1..3]
Math.sqrt i
as [number, number, number]
```
Along the way it implements:
* Binary operators after loops/ifs (building on #1375 which added pipes)
* Postfix operators after loops/ifs (`as` is one of these)
* TypeScript postfix operators (including `as`) on a following line (at same or further indentation level). It turns out that TypeScript [doesn't support this](https://www.typescriptlang.org/play/?#code/BTCUF4D4G8GMHsB2BnALgAgE4FNkFcAbVZcAbQF0BuAM3k3WARQwA915r1SByAQ2-Kh00ALAAodFlyFiAOgAOeZAAtgLUOIC+OVHkyIp+Isk2gw43snS9EATwpA), so I eat the newline in order to make TS happy.

Loops followed by binary operators, `as` on next line

---

source/parser/declaration.civet
source/parser/function.civet
source/parser/util.civet
test/for.civet
test/loop.civet

Fixes #1471
Also a couple little cleanups I noticed:
* Remove unnecessary bracing in one-line loop generators (`for*` etc)
* Remove no-longer-used "outer" mechanism in `insertReturn` and `wrapIteration...`. `insertReturn` hasn't used `outerNode` in a while, and this PR removed the use in `wrapIteration...`
* New `asserts.notNull` with a TypeScript assertion to make guarding automatic

Fix bracing in implicitly returned one-line for loops

---

source/parser/function.civet
test/types/class.civet

@bbrk24 reported that [private fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties) need `#field` in the class body, and these were absent from such fields created automatically via `@(#field)` (#1469) when outputting JavaScript (not TypeScript).
They now match the behavior of regular field definitions in Civet: the name remains in JavaScript mode (even when not private), but the type suffix disappears in JavaScript mode.

Fix automatic private fields from constructor `@args`

---

civet.dev/reference.md
source/generate.civet
source/parser.hera
source/parser/for.civet
source/parser/lib.civet
source/parser/types.civet
test/compat/coffee-for-loops.civet
test/for.civet
test/range.civet
test/slice.civet
types/types.d.ts

Fixes #999 by allowing inequalities in `..` ranges/slices, inspired by [Swift's `a..<b` half-open range operator](https://developer.apple.com/documentation/swift/range):
* Each endpoint can be marked `<` or `<=` (or the Unicode equivalent, `≤`) for increasing loops, or `>` or `>=`/`≥` for decreasing loops.
* Inclusive (as in `<=` or `>=`) is the default behavior, but it forces a loop order, which can be useful.
* Slices forbid `>`, as we don't have a nice way to reverse slice (when dealing with strings).
Because we can now specify direction, the ranges and loops can be a bit more efficient (as well as more consistent/reliable). Compare the old `...`:
```js
[0...array#]
for i of [0...array#]
↓↓↓
((s, e) => {
let step = e > s ? 1 : -1;
return Array.from(
{ length: Math.abs(e - s) },
(_, i) …
```

Ranges and slices with inequalities such as `[a<..<b]`

---

civet.dev/reference.md
source/parser.hera
source/parser/helper.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/compat/examples.civet
test/for.civet
test/function-block-shorthand.civet
test/slice.civet

This was mostly for fun, and for code golfers to be able to reverse a string with `x[..>=]`. It ended up a little bigger than I expected, to get the many cases working...
* Slices remain increasing by default (even without `<`/`<=` modifier)
* With explicit `>` or `>=`, slices are reversed, similar to a range, so normally left ≥ right. For example, `x[..>=]` is equivalent to `x[-1 ..>= 0]` which is equivalent to `x[x.length - 1 ..>= 0]`
* Also fix increasing slices with implicit parts, like `x[..<]`

Reverse slices and inequality slices with implicit parts

---

source/parser.hera
test/types/type-declaration.civet

Allow indented type after a binary operator, avoiding `__` in this case. This is important because otherwise implicit type arguments can apply.
Context: I noticed that `source/types.civet` wasn't parsing correctly. The relevant snippet is now a test case.

Indented types after binary type operators

---

build/build.sh
civet.dev/reference.md
package.json
source/parser.hera
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/try.civet
test/types/try.civet
yarn.lock

Fixes #1473 by following Plan 2 from https://github.com/DanielXMoore/Civet/issues/1473#issuecomment-2420337249, which seemed the most versatile.
This PR early-rewrites multiple `catch` blocks into a `catch(e) { switch(e)` with corresponding pattern matching, so any extensions to pattern matching will automatically apply.

Pattern matching `catch`

---

.civet/hera-plugin.mjs
lsp/build/build.civet
source/cli.civet
source/main.civet

For some reason, the CLI was adding `NODE_OPTIONS` as a command-line option when running Node. This isn't necessary (`NODE_OPTIONS` is already treated by Node as a command-line prefix), and it has long broke LSP building from VSCode on my Windows machine because VSCode set `NODE_OPTIONS= --require c:/Users/edemaine/AppData/Roaming/Code/User/workspaceStorage/1f20d4e8ff5068acfb8c92639172c1b4/ms-vscode.js-debug/bootloader.js` which is multiple arguments, not one, and we were adding it as one.
I also improved the Hera plugin slightly to use ESM mode (removing the common "`parse` isn't exported" error), and to use sourcemaps.
Originally I was aiming to fix the crash in the LSP when loading `source/main.civet`, or any file that `import`s from `parser.hera`, but I haven't been able to track that …

Fix CLI with complex `NODE_OPTIONS`, LSP cleanup

---

source/parser.hera
test/if.civet

Fixes #690
I think just `switch` needs `ForbidNewlineBinaryOp` (because of pattern matching conditions like `> 0`), so I moved it there.

`if` conditions continued by binary op on next line

---

civet.dev/reference.md
source/parser.hera
test/export.civet
test/import.civet

Fixes #320
Fixes #800
Also cleanup some old `import`/`export` rules (merging `type`/no `type` for regular `import`, and merging explicit/implicit `import` in `operator` case)

`from ... import/export` (reversed `import`/`export`)

---

source/parser/comptime.civet
test/comptime.civet

preventExtensions on comptime functions

---

integration/unplugin-examples/astro/package.json
integration/unplugin-examples/esbuild/package.json
integration/unplugin-examples/nextjs/next.config.js
integration/unplugin-examples/nextjs/package-lock.json
integration/unplugin-examples/nextjs/package.json
integration/unplugin-examples/nextjs/pages/about.civet
integration/unplugin-examples/nextjs/tsconfig.json
integration/unplugin-examples/rollup/package.json
integration/unplugin-examples/vite-lib/package.json
integration/unplugin-examples/vite/package.json
integration/unplugin-examples/webpack/package.json
source/unplugin/unplugin.civet

[tough on HN](https://news.ycombinator.com/item?id=41919111) reported that the NextJS example wasn't working. I'd never tried it, but they were right! I needed to fix two things:
* NextJS makes extensive use of `resolve.alias`es. Sadly, `resolveId` doesn't seem to get the id after such aliases are resolved, so I reimplemented the alias resolver so that they function again.
* unplugin transforms our fake filenames into virtualized filenames, but the `importer` argument didn't get correctly unvirtualized. So I added this. (Will hopefully fix upstream as well.)
The source code links to the specifics that I referred to.
With all this, I can go to `integration/unplugin-examples/nextjs`, `npm install`, (`npm link @danielx/civet` to use this new unplugin), `npm run build`, and `npm run start` to …

Fix unplugin's webpack mode: `resolve.alias`, virtual modules

---

civet.dev/reference.md
notes/Comparison-to-CoffeeScript.md
source/generate.civet
source/parser.hera
source/parser/for.civet
source/parser/types.civet
source/parser/unary.civet
source/parser/util.civet
test/compat/coffee-for-loops.civet
test/for.civet

I apparently already tried to add this, because the parse rules were all there. They just didn't activate ever because `by` wasn't in `ReservedBinary`. Now fixed, and fixed the actual code that handled `by` (previously, `by` was in the output).
I also cleaned up some literal handling code, in particular to deal with these new step values, and let us figure out whether we're stepping upward or downard when the step is a literal.

Range loops can provide custom skip via `by` (not just in CoffeeScript)

---

civet.dev/reference.md
source/parser.hera
source/parser/for.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
test/for.civet
test/function-application.civet
test/function.civet
test/loop.civet

* The automatic unwrapping of loops at the top level of a block (to avoid IIFEs) wasn't triggering when there were multiple such loops in a row (since #1474). This is now fixed.
* Expressionized `for x of y` loops with an empty body now have an implicit body of `x`, giving a simple way to arrayify (or generatorify) a given iterable `y`. The previous behavior was to return an empty array, which didn't seem helpful
* `for some/every/count/sum/product/min/max` reduction loops!
~~TODO: not working with `when` yet~~ Now works with `when` and `own`!

`for some/every/count/sum/product/min/max` reduction loops, empty for loop default behavior, fix unwrapping multiple loops ina  row

---

source/parser.hera
source/parser/pipe.civet
test/pipe.civet

Fixes #1513 
Currently, always wraps it in an IIFE, since there's no easy way to tell whether it's in statement vs expression position.

Allow `|> throw`

---

civet.dev/reference.md
source/parser/auto-dec.civet
source/parser/block.civet
source/parser/for.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/do.civet
test/for.civet
test/loop.civet
test/while.civet

This started as an optimization to not wrap top-level iterations in IIFEs, which also enables use of `break`/`continue`/`return` in more cases.
As a bonus, it changes the behavior of generator iterations (e.g. `for*`) when at the top level: they now directly `yield` to the parent function, instead of only being useful as immediately returned generators. This makes it a lot easier to make generator functions without having to type `yield`!
This is also a breaking change, but only in the case of unreturned generator expressions, which should have been a bug in your code anyway (as previous discussed with @bbrk24 in Discord).
Also fix implicit `for` loop bodies in two cases (separate commits):
* Range iteration
* Generator `for*`

Multiple generator loops at top level, unwrap top-level iterations, fix implicit loop bodies

---

civet.dev/reference.md
source/parser.hera
test/symbol.civet

`:"symbol name"` symbol shorthand with quotes

---

civet.dev/reference.md
source/parser.hera
source/parser/block.civet
source/parser/lib.civet
source/parser/pipe.civet
source/parser/types.civet
test/pipe.civet

Follow-up to #1517 to
* use `StatementExpression` instead of manual `makeIIFE`
* when dealing with `StatementExpression`, use new `blockContainingStatement` helper from #1518 to determine whether to wrap with IIFE
I tried *always* doing the latter, but it led to some broken outputs such as `check := if & then x else &` turning into the incorrect `const check = $ => if ($) x; else $`. So it only happens when explicitly requested via `maybe: true` flag.
---
I also noticed that #1517 forbade regular `throw` expressionized statements in pipelines, which could be useful when using placeholders. So I also extended `.` placeholder to lift above `await`/`throw`, which seems very similar to lifting above unary operations (indeed, `await` is mostly considered a unary operator in Civet, but …

`await`/`throw` with placeholders in pipeline, trailing `|> throw` makes statement without IIFE

---

civet.dev/reference.md
source/parser.hera
source/parser/function.civet
source/parser/helper.civet
source/parser/lib.civet
source/parser/types.civet
test/function.civet
test/types/function.civet
test/types/type-declaration.civet

Fixes #1516 by making the type `async => Foo` equivalent to `() => Promise<Foo>`
I realized that this was inconsistent with how we type the return values of actual `async function`s, though, and made it consistent. So now `async function f(): Foo` is equivalent to `async function f(): Promise<Foo>`. We've discussed this before, and were worried about the case when `Foo` was already a `Promise`-wrapped type. Luckily, this [doesn't affect type checking](https://www.typescriptlang.org/play/?#code/IYZwngdgxgBAZgV2gFwJYHsLwBQQFwwQIC2ARgKYBOAlAQAqXrGojkA8DTL7RZVAfPxgBvALAAoGFJjAA7sFTIYnZqwB0lciHQAbAG7ls1CdJibkCSlggSAvifgSA9E4B6AfiA) (though it does affect hover documentation, annoyingly).
In both cases, wrapping is suppressed if the type is already `Promise`-wrapped right there. In the distant …

`async` functions and arrow types auto-wrap return type in `Promise`

---

civet.dev/reference.md
source/parser.hera
source/parser/function.civet
source/parser/types.civet
source/parser/util.civet
test/function.civet

Fixes #1515
Also fix `deepCopy` to preserve aliasing, which is pretty important in our AST.

Fix typing of `return.value` in `async` function

---

source/parser.hera
test/for.civet

Fixes #1529
`each` is a long-standing issue. All fixed by trying to parse without the new syntax first.

Fix `sum`/`count`/`each`/`own`/etc. as loop iteration variables

---

source/parser/binding.civet
source/parser/for.civet
source/parser/types.civet
source/parser/util.civet
test/for.civet

Fixes #1527
Also finished off the last of `ASTNodeBase` → `ASTNodeObject` transition.

Ensure space after `for..of/in`

---

source/parser.hera
test/pipe.civet

Fixes #1525
#1520 introduced some extra situations to not trigger an `await` step, which unfortunately included (via `MaybeNestedExpression`) an arbitrary `Expression` following the `await`, but `Expression` allows starting with `__`. 😱 
This PR instead uses `MaybeParenNestedExpression`, which is what e.g. `throw` actually uses. Despite the similar name, this rule is much more careful about initial newline, and seems to work. 🤞

Fix `await` step vs. expression detection in pipeline

---

source/parser/for.civet
source/parser/lib.civet
source/parser/pipe.civet
source/parser/types.civet
source/parser/util.civet
test/assignment.civet
test/function-block-shorthand.civet
test/pipe.civet

Fixes #1528
Consolidated some pipe-specific code that did some checks, and fixed one existing test case that said we ought to fix this.
I'm slightly worried that we're modifying in-place during `processForInOf`, which could affect the cache, but I think these error cases would be consistent... I wasn't sure how else to structure `checkValidLHS`.

Check for valid left-hand sides, forbidding lone placeholder

---

civet.dev/.vitepress/components/Playground.vue
civet.dev/.vitepress/utils/compileCivetToHtml.ts

New behavior:
* Editing the code turns `comptime` toggle back off, to prevent running code that you're still in the middle of editing
* Restart worker after each `comptime` execution, for more consistent behavior. Fixes #1495

Playground `comptime` restarts playground worker and resets toggle after editing

---

civet.dev/config.md
civet.dev/reference.md
source/parser.hera
test/prologues.civet
types/types.d.ts

Fixes #1481
If we ever want a "Civet strict mode", we might want to call this `jsStrict` instead of `strict`. But maybe two "strict" modes would be confusing, so in this hypothetical scenario, it might be better to call our thing something else (like "stern mode").

"civet strict" directive to enable JS strict mode

---

source/parser.hera
test/function-block-shorthand.civet

Fixes #1541
I'm not sure this is perfect in all cases (or even that we can be), but it seems to better handle `1 & &` vs. `& & 1`.
Previously, we forbid an implicit call starting with a `&` that could be interpreted as a binary operator, unless the right-hand side started with a `&`. This correctly handled `& & 1`, but didn't correctly handle `1 & &`. Now the "unless" case further requires that the second `&` can also be interpreted as a binary operator (i.e. has a right-hand side).
(There's many nested levels of negation here, making it very confusing...)

Fix `& &` disambiguation (placeholder vs. bitwise and)

---

civet.dev/reference.md
source/parser.hera
test/slice.civet

As suggested by @STRd6 on Discord

Inequality slicing without `..`: `x[<i]` etc.

---

source/parser.hera
test/array.civet

Argument parsing redux, part 721.
@bbrk24 reported that we couldn't mix bulleted arrays with other indented arguments. This was a holdover from CoffeeScript-style argument where we required commas between implicit objects and other items, because that's all that could work.
I ended up being able to make commas optional before indented blocks of arguments (which can be regular arguments, bulleted list, or an implicit object). This simplified the grammar somewhat, even. And with a bit of work, it lets you flexibly switch between the different styles of indented argument blocks.

Allow multiple indented blocks of arguments in function call

---

lsp/source/extension.civet

Useful for when installing packages, or changing Civet parse options, or e.g. changing to `"type": "module"` (as reported in Discord)

Restart LSP when `package.json` or Civet config file changes

---

civet.dev/.vitepress/components/PlaygroundFull.vue
source/parser/lib.civet
test/iife.civet

Fixes #1550
It turns out the input caused a `let ref` which had an empty `names` field, which let to `"civet repl"` creating an invalid statement `var ;`. Now such declarations are skipped from hoisting, so the `ref`s don't get exposed and they don't cause a crash.
Also, future `SyntaxError` crashes will cause the code to be output to console, for easier diagnosis.

Fix REPL support for `ref`s created by Civet

---

civet.dev/reference.md
package.json
source/parser.hera
source/parser/lib.civet
source/parser/pattern-matching.civet
source/parser/ref.civet
source/parser/types.civet
test/property-access.civet
yarn.lock

Part of #909
Also simplify the use of `maybeRefAssignment` so that you don't need to include the `hoistDec` yourself; it's automatically included in the `AssignmentExpression` for the `ref`. So ref work should be a bit easier.

`array[i%]` modulo index shorthand

---

source/bun-civet.civet

Added a step to load plugin, without executing which the user gets an unobvious error

Bun docs: improve getting started guidance

---

source/parser.hera
source/parser/function.civet
source/parser/lib.civet
source/parser/op.civet
source/parser/pattern-matching.civet
source/parser/ref.civet
source/parser/types.civet
source/parser/util.civet
test/binary-op.civet
test/chained-comparisons.civet
test/property-access.civet

Fixes #50, but I still need to think about the TODO (out of time for now).

Avoid duplicate calls in relation chains and `@` bind shorthand via refs 

---

lsp/source/lib/textRendering.mts
lsp/source/server.mts

The LSP protocol has a way to ask for more details about completions. I struggled through recreating what the TypeScript LSP does, forwarding the request on to TypeScript and then redoing the format completely (ugh). This roughly duplicates a bunch of code from https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/util/textRendering.ts in particular, but I didn't see a way around it (and it's MIT licensed at least, but maybe needs a better credit?).
It crashes for some completions where the completion provides a "source" (like the `mocha` example above). I don't really know what the issue is. (It says `Cannot read properties of undefined (reading 'options')` but the error occurs within TypeScript.) Maybe we should catch the error and …

LSP completions show details and documentation

---

civet.dev/reference.md
source/parser/for.civet
test/types/for.civet

Helps with #1562
Before:
```js
for x: T, y in z
console.log x, y
---
for (const key in z) {const x: T = key;const y = z[key];
console.log(x, y)
}
```
After:
```js
for x: T, y in z
console.log x, y
---
for (const key in z) {const x: T = key;const y = z[x];
console.log(x, y)
}
```
This allows us to manually fix the type of the key to `keyof typeof z`, for example, which helps get the right type for `y`.

Fix `for key: T, value in` loop to define `value` using typed `key`

---

civet.dev/reference.md
source/parser.hera
source/parser/block.civet
source/parser/lib.civet
source/parser/types.civet
test/try.civet

As discussed on Discord, this seems like a more ergonomic form of `using` in many cases, and quite intuitive. Also matches [Swift's `defer`](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/statements/#Defer-Statement)) and [Zig's `defer`](https://ziglang.org/documentation/master/#defer).
Only supported at the statement level.
[Performance penalty seems minimal](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiIxNFNkYTVpZW42dk95RS1RZ3E0MGwiLCJjb2RlIjoidHJ5IHtcbiAgREFUQS5mb28oKVxufSBmaW5hbGx5IHtcbiAgREFUQS5mb28oKTtcbiAgREFUQS5mb28oKTtcbn0iLCJuYW1lIjoiMSB0cnkgd3JhcHBlciIsImRlcGVuZGVuY2llcyI6W119LHsiaWQiOiJVWFgxR0N3eEtkc0QtcG95My1JRVUiLCJjb2RlIjoidHJ5IHtcbiAgdHJ5IHtcbiAgICBEQVRBLmZvbygpXG4gIH0gZmluYWxseSB7XG4gICAgREFUQS5mb28oKTtcbiAgfVxufSBmaW5hbGx5IHtcbiAgREFUQS5m …

Lone `finally` block provides cleanup for rest of block

---

civet.dev/.vitepress/components/Playground.vue

Provide a way to copy compile output in cases where the fragment significantly exceeds the window size.

Docs (playground): provide copy button for large text fragments

---

integration/unplugin-examples/esbuild/src/main.civet
source/parser.hera
source/parser/declaration.civet
source/parser/types.civet
source/unplugin/README.md
source/unplugin/unplugin.civet
types/types.d.ts

Fixes #1567 by undoing the effects of `rewriteCivetImports` (by mangling the AST) before giving TypeScript code to TypeScript. I split up the `parse` and `generate` stages so that this can be done efficiently (without having to build twice). This also improved performance in other cases, e.g., when using Civet to generate JavaScript (`ts: "civet"` or the default) but also using TypeScript to typecheck; previously, Civet's full compilation ran twice, but now it's just `generate` that runs twice.
I also noticed some cases where we were not setting the `sourceMaps` map correctly, and fixed those.
I also did a more thorough Civetification of `unplugin.civet`. This results in a rather large diff. If you'd like to see the more meaningful changes, look at the individual commits other than …

Fix unplugin `typecheck`: source mapping and `rewriteCivetImports` combination

---

civet.dev/.vitepress/components/Playground.vue
civet.dev/.vitepress/components/PlaygroundFull.vue

Follow up to #1569 to
* Buttons for copying both input or output to clipboard
* Show buttons in all cases, not just when it's long
* Improve looks somewhat: `copy` text wasn't obviously a button; now it's a clipboard icon, with feedback via a green checkmark or a red X

Playground buttons to copy input or output

---

source/parser/helper.civet
source/parser/lib.civet
test/function-block-shorthand.civet
test/slice.civet

Fixes #1568
Also cleanup helpers' delimiters in statement tuples, to avoid unneeded ASI in some cases (including the added test).

Fix modulo access with placeholders: `x[& %]`

---

source/parser.hera
test/function-block-shorthand.civet

Fixes #1570
Placeholders followed by binary operators seem to already be correctly handled (because they're not valid expressions)

Fix parenthesized `&` followed by type postfix

---

source/parser.hera
test/function-block-shorthand.civet

Follow up to #1574
> Placeholders followed by binary operators seem to already be correctly handled (because they're not valid expressions)
Turns out I was wrong about this. Custom binary operators are at least one example.

Fix parenthesized `&` followed by binary op

---

source/parser.hera
test/numbers.civet

Fix the equivalent of https://github.com/jashkenas/coffeescript/issues/5469 by giving priority to `1.e1` as a number, not an access (`(1).e1`), as suggested by @STRd6.
Improves JavaScript compatibility.
Technically this is a breaking change, but it's also reasonably a bug fix.

Scientific numeric literals take priority over access

---

source/parser.hera
test/function-block-shorthand.civet

Fix parenthesized `⧺` and `—` shorthands for `++` and `--`

---

source/parser.hera
source/parser/declaration.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/unary.civet
test/iife.civet
test/object.civet

* REPL wrapping of object destructuring assignments (#1581)
* Object literals with unary suffixes, in general and in fat arrow bodies (#1582)

Fix wrapping of braced objects in parentheses

---

civet.dev/reference.md
source/parser.hera
source/parser/function.civet
test/object-comprehensions.civet
test/object.civet

Work-in-progress to address the "object comprehension" part of issue #439.
Implementation rationale is that whenever  the following is seen:
```
{ 
for identifier of expression 
[a] : b
[c]:  d
//...
}
```
Then it should be recognized as object comprehension (instead of being recognized as a block containing a ForOf statement).
This works because `for identifier of expression` being followed by a computed property key-value pair is invalid syntax in js.
I need some guidance:
My rules recognize the syntax but it isn't prioritized over "block containing a for-of" rule when the [a] : b are indented. This results in the following input-output pair:
```
{ for x of [1, 2, 3]
[x]:  2 * x
[x * 2]: 4 * x
}
// Becomes:
for (const x of [1, 2, 3]) {
({[x]:  2 * x,
[x * 2]: 4 * x})
}
}
```
This is …

Object comprehensions via loops in braces

---

notes/Comparison-to-CoffeeScript.md

Not only is `CoffeeOf` the wrong capitalization, `coffeeOf` is the wrong directive.

Fix typo in Coffeescript comparison

---

source/parser.hera
test/types/function.civet
test/types/type-declaration.civet

Require postfix `if`/`unless` in a type context to be on the same line, not a following indented line. Fixes #1590
Allowing indentation seems terribly ambiguous with implicit type arguments. This is also how postfix `if` already behaves in expression context: the following example [fails to parse](https://civet.dev/playground?code=Zm9vCiAgaWYgY29uZGl0aW9u):
```js
foo
if condition
```

Type's postfix `if` must be on the same line

---

lsp/source/server.mts

Fixes #1588 by
* Catching errors and just logging them instead of the popup
* Seem to have fixed the underlying error here by specifying an actual formatting options object (despite docs claiming it's optional)

LSP: fix autocompletion details error message

---

source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/comptime.civet
test/for.civet

Fixes #1586 by preserving aliasing in our objects during `insertTrimmingSpace`. This was tricky to debug! Hopefully this fixes everything.

Fix reduction inside conditions, and other subtle aliasing issues

---

source/parser.hera
test/call-expression.civet
test/compat/examples.civet

Fixes #1597
BREAKING CHANGE: A chain of trailing member accesses must now be consistently indented.

Track indentation of trailing member/call expressions

---

source/parser.hera
test/function-application.civet

Fixes @bbrk24's reported regression (which is now a test).
* Call arguments now check for trailing call expressions instead of trailing member expressions.
* I never understood why we had both trailing member and trailing call rules. We no longer use the member ones, so the grammar got a bunch simpler.
* Missing `.flat()` in handling trailing call expressions (else a JSX test would fail).

Fix trailing member/call behavior

---

source/parser.hera
source/parser/lib.civet
source/parser/types.civet
test/import.civet
test/jsx/attr.civet
test/object.civet

The following examples weren't working before:
* `<Component {f()?.{nx,ny}}>` (ref caused trouble — I encountered this in the real world which is what sent me down this path)
* `{x().{a,b}, y()?.{c,d}}` (didn't properly merge with multiple refs)
Also improved globs to not use refs if we only need one property, which occurs in a bunch of dynamic `import` examples.

Fix complex property globs

---

source/parser.hera
test/if.civet

This example came up in Discord: (where `1` and `2` are placeholders for more complex expressions)
```js
if
1 for every x in y
then
2
```
Without this PR:
```js
if(
1) (()=>{let results=true;for (const x in y)if (!(void 0)) {results = false; break};;return results})()(
2)
```
With this PR:
```js
if((()=>{let results=true;for (const x in y) { if (!(
1)) {results = false; break} }return results})()) {
2
}
```

Allow postfix in indented `if` conditions

---

source/parser.hera
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/switch.civet

Fixes #1602
This was trickier than expected. One fun issue is that SemicolonDelimiter can end with a trailing Comment. This hasn't been an issue in the past because we avoid adding `return` in such scenarios. But now we need to, so I added a `hasTrailingComment` helper for this.

Fix fallthrough in implicitly returned switch with semicolon, improve `hasExit` heuristic

---

source/parser.hera
source/parser/lib.civet
source/parser/types.civet
source/parser/util.civet
test/types/type-declaration.civet

Fixes #1607
Previously, we supported handled `?`/`!` type suffixes if they were at the end of a suffix sequence. Now we handle them in arbitrary position, potentially splitting one TypeUnary into two.

Type postfix `?` and `!` work in long postfix sequence

---

source/parser/helper.civet
test/function.civet
test/types/function.civet
test/types/type-declaration.civet

Our current `AutoPromise` wrapper is [broken in many cases](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAggrsA9gBQE6ILYEsDOEA8AKgHxQC8UhUEAHsBAHYAmOUamuBcDA1g4gHcGpAPyUoALjbpseIsQDcAWABQq0JCgARcrAQoZnfFoCG9YqqhWA9NYB6I1SZwgGAYygAzbm+BZEDFBMABQAlFLwSOyyBKbmUADellCoEMBwqIEmAiZYwFAMEALaZhDKKgC+qurg0FoAqrqRBhxycdAAPlDcTBCeWIVMFipWULYOTi7uXj5+AUFwYRH60UbtUF09fQMQQ4nJqemZUNm5+YXF7eVVaioa0DBNK4ZyJgwgw6PjjirOrh7edxzLJLPRRF4EN4ffYjFJpDJZHJ5ApFEr0a6qIA). TS seems to be splitting up `AutoPromise<A | B>` into `AutoPromise<A> | AutoPromise<B>` which fails the check for a single `Promise<...>` wrapper.
But the arguably simpler `Promise<Awaited<T>>` wrapper [seems to work great](https://www.typescriptlang.org/play/?ssl=1&ssc=23&pln=1&pc=43#code/C4TwDgpgBAggrsA9gBQE6ILYEsDOEA8AKgHxQC8UamuBMA7gIZbA …

Fix automatic `Promise` wrapping of async return types

---

source/parser/helper.civet
test/assignment.civet
test/binary-op.civet
test/function-block-shorthand.civet
test/property-access.civet

`%%` operator types support `bigint` in addition to `number`

---

source/parser/pipe.civet
source/parser/types.civet
source/parser/util.civet
test/pipe.civet

Fixes #1624
* `NewExpression`s need parentheses if they don't have a call in them
* But now we need to handle `|> new Foo` specially

Fix `new` expression at start of pipeline

---

source/parser.hera
test/call-expression.civet
test/jsx/attr.civet
test/pipe.civet

The `MaybeNested...Expression` rules were surprisingly quite broken. Can you spot the bug?
```js
MaybeNestedExpression
NestedBulletedArray
PushIndent ( Nested Expression )? PopIndent ->
if ($3) return $3
return $skip
Expression
```
"Luckily" `PopIndent` was always false, so the indented rule never applied. But we weren't correctly tracking indentation in this case.
With this fixed, we no longer supported dedented trailing call expressions after a nested expression. So I added `AllowedTrailingCallExpression?` after `PopIndent` in the rule above (and its friends).
But adding that revealed a different bug.  In particular, the following was treated as a call before:
```js
x =
a
b
```
So I modified `AllowedTrailingCallExpression` to not check for implicit calls; they shouldn't be relevant for …

Fix object literals and bulleted lists in JSX indented attributes, fix indentation detection

---

source/parser/for.civet
source/parser/lib.civet
source/parser/types.civet
test/function-block-shorthand.civet

Fixes #1603
There might be other situations where we need to `implicitLift` (and maybe it will need to be a number instead of just 1 or 0) but at least we have a mechanism now.
(also open to better names than "`implicitLift`")

Fix placeholders in `for each` loops

---

source/parser.hera
test/function-application.civet

Fix implicit objects in indented arguments after other arguments

---

source/parser.hera
source/parser/binding.civet
source/parser/function.civet
source/parser/types.civet
test/class.civet
test/types/class.civet

Fix mixing access modifiers (e.g. `readonly`) with `@` arguments in constructors

---

civet.dev/config.md
civet.dev/reference.md
notes/Comparison-to-CoffeeScript.md
source/parser.hera
source/parser/for.civet
source/parser/types.civet
test/compat/coffee-range.civet
test/for.civet
test/range.civet
types/types.d.ts

Now that we have the ability to change the range literal direction via `<`/`>`/`<=`/`>=` modifiers, change the default behavior to `<=`. Old behavior available via `"civet coffeeCompat"` or `"civet coffeeRange"`.
Arguments for this change in default behavior from Discord:
* Brings range literal `[a..b]` into alignment with slices `x[a..b]` (which were already increasing by default, unless you explicitly write `>` or `>=`)
* Avoids bugs where you write e.g. `[1...n]` and fail to consider the case `n = 0`, so you end up with `[1, 0]` whereas you meant `[]`.
BREAKING CHANGE: `[a..b]` and `[a...b]` no longer creates a decreasing range without an explicit `>` or `>=`; add one where needed.
~~TODO: fix tests~~
~~TODO: some character loops are breaking~~

Range literal `[a..b]` defaults to increasing; adaptive behavior behind `"civet coffeeRange"` directive

---

source/parser/function.civet
source/parser/pipe.civet
test/function-block-shorthand.civet
test/function.civet
test/pipe.civet

Fixes #1339
Functionally equivalent, but good for linting. Also generates somewhat nicer looking code, because implicit `return`s get moved to the end of a chain.
It was a little trickier than the idea in https://github.com/DanielXMoore/Civet/issues/1339#issuecomment-2495547043 because of implicit returns.

Fat pipe `||>` uses semicolons at statement level

---

source/parser/function.civet
test/switch.civet

`node` is sometimes the Statement tuple so using `exp` which is always the actual block. TS actually caught the error.
Note that this is being interpreted as a block statement not an object literal at present.

Fix #1637: prevent parser crash on blocks inside switch

---

civet.dev/reference.md
source/parser.hera
test/label.civet

Fixes #1638
* Allow reserved words in `:label`
* JavaScript reserved words will fail on output
* Civet reserved words like `loop` and `and` are useful
* `:void` remains untouched for possible return type annotation...
* `break :label` can also use a reserved word, with the same caveats
* `break loop` also works like `break :loop`, because it's "natural" meaning `while (true) break` isn't useful.
It's debatable to me whether `:void` should be allowed as a return-type annotation. It's extremely fragile; for example, `:number` doesn't work as a return-type annotation at the beginning of a line (it's treated as a label). UPDATE: But I guess `:void` is common enough to be worth keeping.
We could allow JavaScript reserved words in `:label` (possibly excepting `:void`) by transpiling them to …

`:label` supports Civet reserved words (but not JS reserved words)

---

civet.dev/reference.md
source/parser.hera
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
test/label.civet

As mentioned in Discord, this seems in line with `continue switch` and fairly intuitive.
It is technically a breaking change, but these seem like unlikely constructions:
* old `break loop` (infinitely many `break`s) is equivalent to `break`
* old `break while cond()` is equivalent to `break if cond()` (and is now a parse error)
* old `break until cond()` is equivalent to `break unless cond()` (and is now a parse error)

`break/continue loop/while/until/for/do` refer to anonymous containing iteration

---

package.json
yarn.lock

[unplugin changelog](https://github.com/unjs/unplugin/releases)
I originally thought updating to v2 was important because of "Support Vite 6" but it turns out all that changed was some testing. 😅 But it looks like there's at least one bug fix in rspack, and some other cleanup.
I tested this with one of my Solid projects (on both Vite 5 and 6), and with `integration/unplugin-examples`.

Update unplugin to v2.1.0

---

source/parser.hera
source/parser/binding.civet
source/parser/declaration.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/pattern-matching.civet
source/parser/traversal.civet
source/parser/types.civet
source/parser/util.civet
test/function.civet
test/types/function.civet

Fixes #929 by
* Typing new end rest parameter as tuple type
* Add type casting of `splice` return value
* Add ref to type cast remaining array, but only for TypeScript output
Lots of other internal cleanup along the way:
* Fix traversal functions to allow non-`Predicate` arguments instead of erroring. In this case, they just don't filter.
* Move `NonEmptyParameters` handler into `processParams`
* Uniform use of `PostRestBindingElements` in `blockPrefix`
* `Parameters` node now has `parameters` property with array of actual parameters
* Internal type fixes

Non-end rest parameters support types

---

civet.dev/reference.md
source/parser.hera
source/parser/auto-dec.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
test/compat/coffee-classes.civet

Improved compatibility with CoffeeScript under `coffeeClasses` mode:
* Private static classic fields via `x = y` within a class body, by wrapping body in an IIFE and adding some local variables. Probably only works with `autoVar` enabled (like various other `coffeeCompat` features). Fixes #457
* Bound methods via `f: =>` within a class body, by adding to the constructor (after `super` call if there is one). Also rewrite into method, similar to `f: ->`. Fixes #55.
* Fix `constructor` getting an automatically inserted return [in most cases](https://civet.dev/playground?code=ImNpdmV0IGNvZmZlZUNsYXNzZXMiCmNsYXNzIFgKICBjb25zdHJ1Y3RvcjogKHgpIC0%2BCiAgICB4KCk%3D). (Recent regression perhaps? This would make `coffeeClasses` pretty unusable.)
Compilations should match CoffeeScript's compilations.

`coffeeClasses` improved compatibility: private static class fields via `=`, bound methods via `=>` , `constructor` shouldn't `return`

---

civet.dev/reference.md
source/parser.hera
source/parser/binding.civet
source/parser/function.civet
source/parser/types.civet
test/function.civet

As discussed on Discord, this seems like a natural extension of our pinned patterns. Originally motivated by simulating `Promise.withResolvers` in this natural way:

Pin parameter `^p` assigns function parameter to outer variable

---

civet.dev/reference.md
source/parser.hera
source/parser/declaration.civet
source/parser/types.civet
source/parser/util.civet
test/types/let-declaration.civet

Previously, `let x?` compiled to the invalid TypeScript `let x?`. Now it compiles to `let x = undefined`. As [this playground shows](https://www.typescriptlang.org/play/?#code/CYUwxgNghgTiAEA3W8wHsB2wBc8BGaaEIUGAsAFDEAu8AHvALzwCuWIAZgJYYjCXoMAZyIgAdBDQBzABR0AlJXjKVqgPRqAegH5KXDvBmDg8+AG8l9JvACslhgGpmARgAMlAL4DMI4hOlyihSqIfAaOkA), this seems to allow for the initial `undefined` value (no error about access before initialized) as well as type inference.
This PR also makes `let x? = 5` compile to `let x = 5` (instead of leaving the invalid `?` in there). I wanted to compile it to `let x: undefined | typeof 5 = 5`, but sadly this [isn't valid TypeScript](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html#limitations):
> TypeScript intentionally limits the sorts of expressions …

`let x?` allows initial `undefined` value + type inference; `let x? = y` for simple `y`

---

source/unplugin/unplugin.civet

I noticed some old code that worked around unplugin bugs that have since been fixed (https://github.com/unjs/unplugin/pull/362 and https://github.com/unjs/unplugin/pull/430), and removed that.
But webpack also wasn't building because of some assumptions in automatic extensions. Should be fixed now (with a hard-coded default).

Extension bug fix for unplugin on webpack; cleanup old bug workarounds

---

civet.dev/reference.md
source/parser.hera
source/parser/declaration.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/types.civet
test/for.civet
test/if.civet

Fixes #439 
Includes optimization for `...for` inside `for`, as suggested by @bbrk24 
During self-test, I also found that `z = (if x then {y})` was incorrectly compiled to `z = ((x?y:void 0))` (note missing braces). That's fixed here too.

Multiple items and spreads in array comprehensions

---

civet.dev/reference.md
source/parser.hera
source/parser/function.civet
source/parser/types.civet
test/for.civet

`for concat` concatenates using `++`. Like #1656, this is another approach to flattening, which I imagine would be useful in some cases. For example, `array.flat(1)` is equivalent to
```js
for concat subarray of array
```
---
`for first` returns the first body, as suggested in #1649, or else `undefined`. For example, this can simulate `Array.prototype.find`: `array.find(cond)` is equivalent to
```js
for first item of array when cond(item)
```
If `cond` isn't already a function, though, it can make nicer code (no function wrapper necessary).
`for first` also lets you choose *what* to return when found. For example, you can simulate `array.findIndex(cond)` like so:
```js
for first item, i of array when cond(item)
i
```
I wasn't sure whether to return the first *truthy* body. This would …

`for concat` reduction for concatenating arrays, `for first` reduction for finding elements

---

source/parser.hera
source/parser/for.civet
source/parser/function.civet
source/parser/types.civet
test/for.civet

Fixes two `for` reduction bugs
TODO: `for* concat` could make sense, but we'd need to detect whether the item is an array or `isConcatSpreadable` and either `yield*` or `yield` accordingly. Worth adding?

`for` reduction fixes: `each` supports implicit body, `for*` is an error

---

source/parser.hera
source/parser/lib.civet
source/parser/types.civet
test/iife.civet

Fix #1659 by skipping top-level `yield*` in the `iife` wrapper, same as we did for `await`.
I also noticed that `topLevelAwait` (and now `topLevelYield`) were computed before we processed `async do` and `do*` which can shield the top level from these. So now we build the IIFE wrapper after `do` processing, but before function processing so we still get implicit return etc. Added some tests for these flags.

Fix top-level `await`/`yield` in `iife` mode (including REPL and Playground)

---

civet.dev/reference.md
source/parser.hera
source/parser/pattern-matching.civet
source/parser/types.civet
test/if.civet
test/switch.civet
test/try.civet

Fixes #1660 by no longer binding `name` in object pattern properties with literal values: `name: "string"`, `name: 42`, or `name: /regex/`. The general rule is now this: if a property has a value, then it doesn't get bound. This seems like a natural extension of how destructuring assignment works.
New feature `name^: value` binds `name`. This also works when checking other properties. For example, the pattern `{parent^: {type: "BlockStatement", expressions}}` binds `parent` and `expression` in two destructurings: `{parent} = x, {expressions} = parent`.
BREAKING CHANGE: Pattern matching with `{name: literal}` no longer binds `name`; use `{name^: literal}` to bind.

Pattern `name^: value` binds `name`, while `name: value` never does

---

CONTRIBUTING.md
build/test.sh

`CIVET_THREADS=4 yarn test` currently crashes. I'm guessing Mocha doesn't like our spawning of workers within tests?
As a workaround to this, I modified the test script to translate `CIVET_THREADS` into the corresponding Mocha options: `--parallel -j 4`. This seems to speed things up. (On my machine, tests go from 21.3s to 14s.)
Now you can set `export CIVET_THREADS=4` globally and both `yarn build` and `yarn test` will speed up.

Parallel testing via `CIVET_THREADS` (Mocha's `--parallel`)

---

source/parser/for.civet
source/parser/helper.civet
source/parser/lib.civet
test/compat/coffee-range.civet
test/range.civet

Started out as an efficiency improvement -- the difference is modest in Safari, but drastic in Chromium and Firefox -- see [this benchmark](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiJ5ZVJycDVXNjYwN2ZBWFQxYllycy0iLCJjb2RlIjoiKChzKSA9PiBBcnJheS5mcm9tKHsgbGVuZ3RoOiA5OTk5IC0gcyArIDEgfSwgKF8sIGkpID0-IHMgKyBpKSkoMCkiLCJuYW1lIjoiQ2l2ZXQgd2F5IiwiZGVwZW5kZW5jaWVzIjpbXX0seyJpZCI6InZ3MWhVa3RnSURZVGNtQUNteGNtTSIsImNvZGUiOiJsZXQgeCA9IDEwMDAwO1xuY29uc3QgYXJyID0gW107XG53aGlsZSAoeC0tKSB7XG4gIGFyclt4XSA9IHg7XG59XG5hcnIiLCJuYW1lIjoid2hpbGUoeC0tKSIsImRlcGVuZGVuY2llcyI6W119LHsiaWQiOiJRd3F2MkZoTE8tZ1pXVXl3OWJRanUiLCJjb2RlIjoiWy4uLkFycmF5KDEwMDAwKS5rZXlzKCldIiwiZGVwZW5kZW5jaWVzIjpbXSwibmFtZSI6IlNwcmVhZCBBcnJheSgpLmtleXMifSx7ImlkIjoieFZUcHFod1ZOcHM0ZWNpcUJndFJKIiwiY29kZSI6IkFycmF5KDEwMDAwKS5maWxsKCkubWFwKCh …

Range literal improvements: faster, fix doubly strict

---

build/test.sh
civet.dev/public/playground.worker.js
integration/eslint/source/index.civet
lsp/source/lib/typescript-service.mts
lsp/source/lib/util.mts
lsp/test/util.civet
source/cli.civet
source/esm.civet
source/generate.civet
source/main.civet
source/node-worker.civet
source/sourcemap.civet
source/ts-diagnostic.civet
source/unplugin/unplugin.civet
source/worker-pool.civet
test/integration.civet
test/sourcemap.civet
test/util/locations.civet
types/types.d.ts

**Worker threads** (`CIVET_THREADS` feature) was broken in a few ways:
* Errors weren't serialized, so we got the empty `{}` exception if there was an error
* `errors` option didn't properly modify the array
* SourceMap outputs were crashing when serializing into a worker response message (because of function properties), which caused an error (see below). This caused `yarn test` to fail (before #1665), and also caused `civet filename.civet` to fail. 🙀 
**Internal API change:** `SourceMap` is now a `class`. This seems cleaner overall, and helps with serialization for worker messages. But it changes the API:
* Instead of `SourceMap(source)` we need to use `new SourceMap(source)`.
* `lines` etc. are properties instead of part of the `data` field. In code that deals with multiple versions of …

Worker threads fixes and SourceMap revamp

---

civet.dev/reference.md
source/parser.hera
source/parser/binding.civet
source/parser/declaration.civet
source/parser/for.civet
source/parser/function.civet
source/parser/lib.civet
source/parser/op.civet
source/parser/pattern-matching.civet
source/parser/ref.civet
source/parser/types.civet
test/assignment.civet
test/for.civet
test/function.civet
test/switch.civet
test/try.civet

New features:
* `name^pattern` or `name^ pattern` is equivalent to `pattern`, but also binds the whole value to `name`.
* For example, `function Comp(props^{a, b})` binds `props`, `a`, and `b`
* This is like `name@pattern` in Haskell, and `pattern as name` in Ocaml and Python. It's motivated by our existing `{name^: pattern}` syntax.
* It works in pattern matching, function parameters, and declarations (`:=`, `.=`, `const`, `let`, `var`).
* It works in `=` assignment, ~~but not yet at the top level~~. Note a small **ambiguity**: `x^{y} = z` previously meant `x ^ ({y} = z)`. I think this is worth overriding, as it's not useful to binary XOR with an object or array. (It's also not particularly critical at the top level, as all it's doing is making a copy of `z`. But I think it's cleaner and …

Named binding patterns `name^pattern` in pattern matching, function parameters, declarations, `for` loops; fix complex bindings in `for` loops

---

source/parser/binding.civet
source/parser/lib.civet
source/parser/ref.civet
source/parser/types.civet
test/types/class.civet

Fixes #1667 
Also move `populateRefs` to ref.civet where it seems to belong.  (No functional changes to this function, just Civetification.)

Fix property `::` typing with private fields

---

source/parser/function.civet
source/parser/pipe.civet
test/pipe.civet

Fix implicit return of pipeline with `return`/`throw`

---

source/parser/lib.civet
test/function-block-shorthand.civet

Fix immediately called `(op)` in pipeline context 

---

source/parser/pipe.civet
test/pipe.civet

Fix pipe into certain `new` expressions

---

civet.dev/.vitepress/components/Playground.vue
civet.dev/public/playground.worker.js

Before:
After:
This was clearly intended by the CSS, but the red variable wasn't assigned; fixed to choose an existing variable.
Before:
After:

Improve Playground error styling

---

source/parser.hera
source/parser/lib.civet
source/parser/op.civet
test/binary-op.civet

Handle invalid precedence in operators

---

source/parser.hera
source/parser/types.civet
test/function-block-shorthand.civet

Fixes #1683
New `spaced` property on binary operators to ensure spaces around the operator.

Allow spaces in `(op)`, force spaces in `(in)` and `(instanceof)`

---

source/parser/lib.civet
source/parser/pipe.civet
test/function-block-shorthand.civet

Fixes #1682
This is pretty subtle: `replaceChild` doesn't preserve the aliasing in our grandparent's `body`. Because of `Wrapper` nodes in this context, it doesn't work (easily) to put this check into `replaceChild`. I *hope* this is the only place we need to do this (where we replace the top level of an ampersand block), but plausibly there are other uses of `replaceChild` with this issue.
An alternative would be to remove ampersand block's `body` properties altogether, and just use the block's first expression. Plausibly, we can decide whether to unwrap even without the `ampersandBlock` hint, checking for a single expression that uses the argument once. Then we could unwrap non-shorthand arrow functions too. Maybe an approach to try in the future.

Fix unwrapping of operator sections with placeholders

---

.github/workflows/build.yml
source/parser.hera
test/array.civet
test/object.civet

Fixes #1687. This bug was introduced by #1628 which innocently added checking for `NestedImplicitObjectLiteral`s next to `NestedBulletedArray`s in `MaybeNestedExpression`.
It turns out the "right" answer is to check for neither! Otherwise, we don't allow for binary operators after dedent after the nested object literal / bulleted array. Conveniently, we already check for `NestedImplicitObjectLiteral` and `NestedBulletedArray` within `PrimaryExpression` (as part of `ObjectLiteral` and `ArrayLiteral` respectively), so we don't need to do anything special here, except for *stopping* the `PushIndent Nested PopIndent` check in `MaybeNestedExpression`.
Along the way, I fixed another issue with the concat operator `++` followed by a bulleted array. Previously, this broke for two reasons: (1) …

Allow binary operators after nested object literals and bulleted arrays, fix `++` with bulleted arrays

---

source/parser/binding.civet
test/types/destructuring.civet

Property `::` types with initializers are optional

---

civet.dev/reference.md

Fixes #1697 
When writing this, I wondered one thing: should we instead use the following existing syntax? (though it doesn't currently compile)
```js
class Civet extends Animal |> Mixin1 |> Mixin2
```
(Or maybe we discussed this already?)
It's more annoying if you want to write `class Civet with Mixin1, Mixin2`:
```js
class Civet extends Object |> Mixin1 |> Mixin2
```

Document `class with A, B` mixins

---

source/parser/util.civet
test/switch.civet

Fixes #1710
Previously, I believe we accidentally claimed that some `switch` statements were exiting when they weren't, because `break` is considered an exit, but in the context of a `switch` they do the opposite of exit (they go to the statement after the `switch`). Now this is correctly detected as not exiting, and the remaining cases are correctly handled as fallthroughs: we check that the default clause, or one of the clauses it falls through to, has an actual exit (not a `break`).

Fix exit detection for `switch` with fallthrough

---

civet.dev/reference.md
source/parser.hera
test/export.civet
test/import.civet

**New behavior:** `a import b` means `a(import(b))`
**Old behavior:** `a import b` means `import b from a`
In particular, this is definitely what we want when `a` is `await`, fixing #1712.
BREAKING CHANGE: `module import spec` needs to written as `from module import spec` (`from` can no longer be omitted)

Require `from` in backwards `import`/`export` to fix ambiguity with dynamic `import`

---

source/parser/declaration.civet
test/export.civet

Fixes #1708 
The attempt to lift statement expressions out of the initializers of declarations was missing a check to see whether the declaration is top level. I think we didn't think about this case because declarations are mostly forced to be top-level because of the grammar, but `ExportDeclaration` is at least one thing that could surround them. By contrast, assignments (see `processAssignments`) already had such a check (`blockContainingStatement`), so I basically just copied that.
We could of course consider a smarter compilation specific to `export`:
```js
export x := if a then b else c
---
let ref
if (a) { x = b }
else { x = c }
export const x = ref
```
This could still be done in the future. In any case I think we should have this check.

Fix `export`ing statement expressions

---

civet.dev/reference.md
source/parser.hera
test/class.civet

Fixes #1707 by adding a nested list form of both `implements` and `with`.
Also convert some `__` to `NotDedented`, allow spaces before commas, etc.

Indented forms of `implements` and `with`

---

source/parser.hera
test/jsx/indent.civet

Fixes #1691 
Implicit JSX fragments still need to start with a "tag" (`<foo>` or ``), but then they can continue with a `>code` sibling.
I'm still not allowing text (or enabled code) to continue an implicit JSX fragment, as that seems a little fragile. But at least now there's a simple workaround of writing `>'text'`.

Allow `>code` to continue an implicit JSX fragment

---

source/unplugin/unplugin.civet
test/integration.civet

This adds the directory paths to the sourcemaps so they don't all end up at the root.

Fix unplugin source map directories

---

build/changelog.civet

Changelog script wasn't working for me unless I was explicit about the shell.

Explicit changelog build script shell

---

.gitignore
.mocharc-self.json
.mocharc.json
build/build.sh
civet.dev/config.md
civet.dev/getting-started.md
package.json
register.js
source/cli.civet
source/esm.civet
source/unplugin/README.md
source/unplugin/unplugin.civet
test/cli.civet
test/infra/config.civet
test/infra/config/civetconfig.json
test/infra/config/needs-coffee.civet
test/infra/esm.civet
test/integration.civet

* ESM loader by default now looks for civetconfig files in the directory of the source file and its ancestors, like the CLI already did for CJS files. This should also fix the CLI in ESM mode, which relied on the ESM loader. Fixes #1315 and part of #1239.
* `@danielx/civet/register-noconfig` disables this new behavior, but otherwise acts like `@danielx/civet/register`.
* ESM loader more generally supports configuration via `initialize` hook, specifiable via `data` option in [`module.register`](https://nodejs.org/api/module.html#moduleregisterspecifier-parenturl-options). This lets you build custom register modules with custom parse options, e.g. for testing.
Also fix a small issue with tests not working in Windows.
BREAKING CHANGE: If you don't use civetconfig files and want to be robust …

ESM loader supports civetconfig by default, and overriding configuration

---

source/parser.hera
test/function.civet

Fixes #1732
This change makes the following code no longer parse:
```js
switch x
^a: b
```
But I'd argue that the current compilation isn't very helpful, as object literals will never equal a given object.
```js
if(x === {a: b}) {}
```

Typed pinned arguments such as `(^x: T) =>`; forbid implicit object literals in pinned patterns

---

lsp/source/lib/typescript-service.mts
lsp/source/server.mts

Hey, this PR addresses a crucial race condition that prevented `civetconfig.json` from being applied on initial project load.
On startup, the Civet LSP would often initialize and perform an initial lint of open files *before* the `civetconfig.json` file was fully parsed and loaded.
This resulted in incorrect diagnostics being shown to the user. For example, features enabled in the config (like `coffeeIsnt`) would be incorrectly ignored. The correct diagnostics would only appear after the user edited the file, which forced the LSP to re-evaluate the document with the now-loaded configuration.
This PR refactors the `TSService` initialization to be asynchronous. By using `async/await`, we now ensure that the configuration is fully loaded and applied *before* the service reports that it's …

lsp: Make TSService initialization async to fix config loading race condition

---

source/cli.civet

On Node 24 (.4.1 and .5 at least), the REPL is broken in that it no longer correctly detects a blank line to execute or compile the code.  Apparently new Nodes provide an input that contains `\r` for newlines for all but the final `\n`.  (Tested on both Windows and Linux, so doesn't seem to be OS dependent.)

Fix REPL handling of blank lines on Node 24

---

lsp/source/server.mts

While implementing the `renameProvider`, I discovered a limitation. When an operation would affect multiple files at once, the old `executeQueue` would process each file change sequentially.
This created a race condition where the TypeScript service would analyze the project in an inconsistent state (e.g., with file A updated but file B not yet updated), leading to temporary but blocking linter errors and incorrect diagnostics. This made cross-file operations not robust at all
This PR refactors the document update mechanism to be **project-aware and atomic**.
Instead of a simple sequential queue, the new `executeQueue` works in two phases:
1.  **Group & Stage:** It first groups all pending document changes by their parent project. Then, for each project, it stages *all* relevant file …

lsp(refactor): rearchitect update queue for atomic, project-based changes to handle conflicts and race conditions

---

source/unplugin/unplugin.civet

I think this was an oversight in #1733.

Fix source map's `sources` using unplugin with `outputExtension`

---

types/types.d.ts

I was building Hera and saw these errors from TypeScript (as a consumer of Civet's types):
```
node_modules/@danielx/civet/dist/types.d.ts:120:24 - error TS2693: 'ParseError' only refers to a type, but is being used as a value here.
120     ParseError: typeof ParseError
~~~~~~~~~~
node_modules/@danielx/civet/dist/types.d.ts:121:25 - error TS2693: 'ParseErrors' only refers to a type, but is being used as a value here.
121     ParseErrors: typeof ParseErrors
~~~~~~~~~~~
node_modules/@danielx/civet/dist/types.d.ts:152:18 - error TS2714: The expression of an export assignment must be an identifier or qualified name in an ambient context.
152   export default {
~
153     findInDir,
~~~~~~~~~~~~~~
...
155     loadConfig,
~~~~~~~~~~~~~~~
156   }
~~~
```
These changes seem to fix all these …

Fix errors in TypeScript types
